= Prerequisites
:nginx-url: https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/
:traefik-url: https://doc.traefik.io/traefik/
:apache-rev-url: https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html

== Hardware

=== Ram Considerations

// harvested from https://owncloud.dev/architecture/efficient-stat-polling/

Every client polls the virtual root ETag (every 30 sec). The gateway will cache the virtual root ETag of every storage for 30 sec as well. That way every storage provider is only stated once every 30 sec (can be throttled dynamically to adapt to storage IO load).

Since the active clients will poll the ETag for all active users, the gateway will have their ETag cached. This is where sharing comes into play: The gateway also needs to stat the ETag of all other entry points or mount points. That may increase the number of stat like requests to storage providers by an order of magnitude.

For a single machine using a local posix storage, the Linux kernel already caches the inodes that contain the metadata that is necessary to calculate the ETag (even extended attributes are supported). With 4k inodes 256 nodes take 1 MB of RAM, 1k inodes take 4 MB and 1M inodes take 4 GB to completely cache the file metadata. For distributed file systems a dedicated cache might make sense to prevent hammering it with stat like requests to calculate ETags.

=== Bandwidth Considerations

The bandwith for a single machine might be another bottleneck. Consider a PROPFIND request with roughly 500 bytes and a response with roughly 800 bytes in size:

* At 100 Mbit (~10MB/s) you can receive 20 000 PROPFIND requests
* At 1000 Mbit (~100MB/s) you can receive 200 000 PROPFIND requests
* At 10 Gbit (~1GB/s) you can receive 2 000 000 PROPFIND requests

This can be scaled by adding more gateways and sharding users because these components are stateless.

== Software

For _best performance_, _stability_, _support_, and _full functionality_ we officially support oCIS running on the following Linux distributions:

* Debian 10 and 11
* Fedora 32 and 33
* Red Hat Enterprise Linux/Centos 7.5 and 8
* SUSE Linux Enterprise Server 12 with SP4/5 and 15
* openSUSE Leap 15.2 and 15.3
* Ubuntu 20.04

In addition, we strongly recommend a reverse proxy for security reasons, load balancing and high availability, e.g., {traefik-url}[Traefik], {apache-rev-url}[Apache] or {nginx-url}[NGINX].

== Storage

In addition to well known metadata like name size and mtime, oCIS allows users to add arbitrary metadata like tags and comments. Therefore oCIS works with POSIX-compliant file systems where this metadata can be mapped to extended attributes. S3 storage is supported but requires POSIX for meta data persistance.

The main POSIX-compliant file systems are:

* EXT4
* BTRFS
* ZFS
* XFS
* CephFS
* NFS

