= Extended Attributes (xattr)
:toc: right
:noindex:
:nfs-utils-url: https://mirrors.edge.kernel.org/pub/linux/utils/nfs-utils/
:ubuntu-nfs-url: https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=nfs-common&searchon=names

== Introduction

IMPORTANT: This document is only valid when using Infinite Scale version 2.0. Starting with version 3.0, Infinite Scale has switched to the messagepack backend for metadata.

== Check xattr Support

Check if extended attributes are supported if selected as metadata backend::
--
When selecting the `xattrs` backend for storing metadata, the used POSIX-compliant filesystem from the tables above must support it. You can check this with the following commands, change to a location in the mounted filesystem you want to check before:

[source,bash]
----
touch foo.txt && attr -s mix -V bar foo.txt
----

[source,plaintext]
----
Attribute "mix" set to a 3 byte value for foo.txt:
bar
----

[source,bash]
----
attr -g mix foo.txt
----

[source,plaintext]
----
Attribute "mix" had a 3 byte value for foo.txt:
bar
----

[source,bash]
----
rm foo.txt
----
--

[[nfs_notes_prerequisites]]
NFS Notes::
+
[NOTE]
====
When using NFS and the `xattrs` backend, you have to take care that the NFS server *AND* the NFS client provides `Extended Attributes`.

NFS Storage Based on Linux Servers::
When using a kernel version 5.9 or higher, extended attributes for the NFS server and the NFS client are part of the system. To check, run the command:
+
[source,bash]
----
uname -r
----
+
On the system providing the NFS server AND on the NFS client check the displayed version number.

NFS Client::
If you have an NFS server capable of extended attributes but you are unsure if your client accessing the server supports it, check the *nfs-utils* or *nfs-common* package version of your NFS client with the command:
+
[source,bash]
----
mount.nfs -V
----
+
You need at minimum NFS version 2.6.1. For more details see the general {nfs-utils-url}[NFS Utils Release History] and the {ubuntu-nfs-url}[Ubuntu nfs-common Packages].

NFS Servers Provided from Storage Vendors::
A certification matrix will be provided when available.

NFS Protocol Version::
Note that if the kernel or the storage system supports extended attributes, you have to use *NFSv4* in order to use it.
====
