= Getting Started
:toc: right
:toclevels: 3


== oCIS online demo

We have an oCIS demo instance running on link:https://ocis.owncloud.com[ocis.owncloud.com] where you can get a first impression of it.

We also have some more variations of oCIS running and xref:../deployment/continuous_deployment.adoc[continuously deployed] to reflect different scenarios in that oCIS might be used.

== Run oCIS

We are distributing oCIS as binaries and Docker images.

[WARNING]
====
The examples in this document assume that oCIS is accessed from the same host as it is running on (`localhost`). If you would like
to access oCIS remotely please refer to the xref:../deployment/basic-remote-setup.adoc[Basic Remote Setup] section. Especially
to the notes about setting the `PROXY_HTTP_ADDR` and `OCIS_URL` environment variables.
====


You can find more deployment examples in the xref:../deployment.adoc[deployment section].

=== Binaries

You can find the latest official release of oCIS at link:https://download.owncloud.com/ocis/ocis/stable/[our download mirror] or on link:https://github.com/owncloud/ocis/releases[GitHub].
The latest build from the master branch can be found at link:https://download.owncloud.com/ocis/ocis/daily/[our download mirrors daily section]. Pre-Releases are available at link:https://download.owncloud.com/ocis/ocis/testing/[our download mirrors testing section].

To run oCIS as binary you need to download it first and then run the following commands.
For this example, assuming version 2.0.0-beta.5 of oCIS running on a Linux AMD64 host:

[source,console]
----
# download
curl https://download.owncloud.com/ocis/ocis/testing/2.0.0-beta.5/ocis-2.0.0-beta.5-linux-amd64 --output ocis

# make binary executable
chmod +x ocis

# initialize a minimal oCIS configuration
./ocis init

# run with demo users
IDM_CREATE_DEMO_USERS=true ./ocis server
----

The default primary storage location is `~/.ocis` or `/var/lib/ocis` depending on the packaging format and your operating system user. You can change that value by configuration.

[NOTE]
====
When you're using oCIS with self-signed certificates, you need to answer the question for certificate checking with "yes" or set the environment variable `OCIS_INSECURE=true`, in order to make oCIS work.
====


[WARNING]
====
oCIS by default relies on Multicast DNS (mDNS), usually via avahi-daemon. If your system has a firewall, make sure mDNS is allowed in your active zone.
====


[WARNING]
====

==== Open Files on macOS

The start command `./ocis server` starts a runtime which runs all oCIS services in one process. On MacOS we have very low limits for open files. oCIS needs more than the default 256. Please raise the limit to 1024 by typing `ulimit -n 1024` within the same cli session where you start ocis from.
====


=== Docker

Docker images for oCIS are available on link:https://hub.docker.com/r/owncloud/ocis[Docker Hub].

The `latest` tag always reflects the current master branch.

[source,console]
----
docker pull owncloud/ocis
docker run --rm -it -v ocis-config:/etc/ocis owncloud/ocis init
docker run --rm -p 9200:9200 -v ocis-config:/etc/ocis -v ocis-data:/var/lib/ocis -e IDM_CREATE_DEMO_USERS=true owncloud/ocis
----

[NOTE]
====
When you're using oCIS with self-signed certificates, you need to set the environment variable `OCIS_INSECURE=true`, in order to make oCIS work.
====


[NOTE]
====
When you're creating the xref:./demo-users.adoc[demo users] by setting `IDM_CREATE_DEMO_USERS=true`, you need to be sure that this instance is not used in production because the passwords are public.
====


[WARNING]
====
We are using named volumes for the oCIS configuration and oCIS data in the above example (`-v ocis-config:/etc/ocis -v ocis-data:/var/lib/ocis`). You could instead also use host bind-mounts instead, eg. `-v /some/host/dir:/var/lib/ocis`.

You cannot use bind mounts on MacOS, since extended attributes are not supported (link:https://github.com/owncloud/ocis/issues/182[owncloud/ocis#182], link:https://github.com/moby/moby/issues/1070[moby/moby#1070]).
====


== Usage

=== Login to ownCloud Web

Open link:https://localhost:9200[https://localhost:9200] and xref:./demo-users.adoc[login using one of the demo accounts].

=== Basic Management Commands

The oCIS single binary contains multiple extensions and the `ocis` command helps you to manage them. You already used `ocis server` to run all available extensions in the xref:#run-ocis.adoc[Run oCIS] section. We now will show you some more management commands, which you may also explore by typing `ocis --help` or going to the xref:../config.adoc[docs].

To initialize the oCIS configuration:

ocis init
// SHORTCODE: {{< / highlight >}}

To start oCIS server:

ocis server
// SHORTCODE: {{< / highlight >}}

The list command prints all running oCIS services.
ocis list
// SHORTCODE: {{< / highlight >}}

The version command prints the version of your installed oCIS.
ocis --version
// SHORTCODE: {{< / highlight >}}

The health command is used to execute a health check, if the exit code equals zero the service should be up and running, if the exit code is greater than zero the service is not in a healthy state. Generally this command is used within our Docker containers, it could also be used within Kubernetes.

ocis health --help
// SHORTCODE: {{< / highlight >}}
