= Introduction to ownCloud Infinite Scale
:toc: right
:toclevels: 2

:description: Welcome to the ownCloud Infinite Scale (oCIS) documentation. This guide provides information on installation and administration tasks for oCIS, the next generation of open source file sharing and synchronization solutions.

== Introduction

{description}

oCIS key benefits:

* No need for PHP or a database
* High performance, flexibility and scalability
* Extended functionality
* Single binary delivery, shipped with the user interface `ownCloud Web`

// fixme: we should have a cross component link to owncloud web when available
// fixme: shall we have a feature list page ?

== Brief Overview

=== Architecture and Concepts

To learn more about oCIS, check out the xref:architecture/index.adoc[Architecture and Concepts] section first. This information may help deciding which installation options you would like to go for and which hardware fits your needs best.

=== Prerequisites

With oCIS, not much is needed to run your ownCloud server the way you want. Check out the short list of xref:prerequisites/index.adoc[prerequisites].

=== Installation

oCIS can be deployed via docker or you can run it manually installed on a physical or virtual machine. Take a look at the xref:deployment/index.adoc[deployment] options for more details.

=== Configuration

xref:configuration/index.adoc[Configuration] of oCIS is quite different to what you're used to and has never been easier. It works with environment variables and optional configuration files for you to create depending on your specific needs. The settings in configuration files can always be overruled by setting the respective environment variables manually on the command line.

=== Maintenance

Since the integrity and sovereignty of your data is the really important thing when it comes to working in a cloud, you'll need to perform regular backups of your data and keep your oCIS up to date. You'll find everything you need to know in the xref:maintenance/index.adoc[Maintenance] section.

== Upgrading from ownCloud 10

If you already have an ownCloud 10 server running, you'll find the xref:migration/index.adoc[Migration] section most interesting.
