= Introduction to Infinite Scale
:toc: right
:toclevels: 2
:description: Welcome to the Infinite Scale documentation. Infinite Scale is a data platform providing tools to integrate, organize, share and govern data and metadata. This guide provides information on general topics, on installation and administrative tasks for Infinite Scale.

:github-url: https://github.com/owncloud/docs-ocis/issues

:ocis_youtube_long_url: https://www.youtube.com/watch?v=C4a4q9IGyFQ&list=PLXpTv1ixYy3-b5LScHyYqMNwEsZYgejdX&index=16
:ocis_youtube_short_url: C4a4q9IGyFQ

== Introduction

{description}

// IMPORTANT: this permalink origins to: https://cloud.owncloud.com/index.php/apps/files/?dir=/Shared/owncloud/Product%20Management/Presentations/2023-05-22_Infinite%20Scale%20current%20state&fileid=6005441

See the following PDF document for a brief 
https://cloud.owncloud.com/index.php/s/S7W9NPfKSHAoEYB[overview of Infinite Scale,window=_blank].

=== Target Audience

This documentation addresses administrators and technically-oriented management:

* people responsible that services are up and running for users,
* people responsible that the IT infrastructure is in line with the organization's compliance regulations,
* technical advisors and technical buyers.

=== Infinite Scale Key Benefits

The Infinite Scale data platform is designed for multi-storage access, is cloud-native (microservices) and provides unified data access.

The key benefits are::

* Integration of distributed data sources into one cloud data ecosystem.
* A unified data access layer across all data.
* Combination of on-premises and cloud-operated environments into one user experience.
* No need for PHP or a database.
* High performance, flexibility and scalability.
* Extended functionality.
* Single binary or container delivery, shipped with the user interface `ownCloud Web`.

See the following in-line YouTube video for more details or use the link:{ocis_youtube_long_url}[link, window=_blank] to view it in a separate browser tab.

.Infinite Scale - A new era for ownCloud - ownCloud Conference 2021
video::{ocis_youtube_short_url}[youtube]

// fixme: we should have a cross-component link to ownCloud Web when available
// fixme: shall we have a feature list page ?

== Brief Overview

NOTE: In configuration variables and comments, you'll often come across the word oCIS or ocis, short for "ownCloud Infinite Scale", while the product is simply called Infinite Scale.

=== Architecture and Concepts

To learn more about Infinite Scale, check out the xref:architecture/architecture.adoc[Architecture and Concepts] section first. This information may help deciding which environment is optimal for your use case and which hardware fits your needs best.

=== Availability and Scalability

With knowledge about architecture and concepts, look at the different xref:availability_scaling/availability_scaling.adoc[Availability and Scalability] options to define the environment Infinite Scale should run on.

=== Prerequisites

With Infinite Scale, not much is needed to run your ownCloud server the way you want. Check out the details in the xref:prerequisites/prerequisites.adoc[Prerequisites] section. We strongly recommend to make up your mind about availability and scalability first.

=== Deployment

Infinite Scale can be deployed via container or you can run the binary installed on a physical or virtual machine. Take a look at the xref:deployment/index.adoc[deployment] options for more details.

NOTE: We highly recommend reading the xref:deployment/general/general-info.adoc[General Info] document first before starting to plan or deploy Infinite Scale. This document contains important topics relevant for all deployments.

=== Configuration Examples

Configuration of Infinite Scale might be quite different to what you are used to but it's very simple. It works with environment variables and optional configuration files for you to create depending on your specific needs. The settings in configuration files can always be overruled by setting the respective environment variables manually on the command line.

== Release Life Cycle

Starting with version 6 of Infinite Scale, releases are now split into `production` and `rolling`. See the https://owncloud.dev/ocis/release_roadmap/[Developer Docs Release Life Cycle] page for more details and impacts.

You can find more details on changes made in each release published in the https://doc.owncloud.com/ocis_release_notes.html[Infinite Scale Server Release Notes].

IMPORTANT: Rolling releases are published in a cycle of 3 weeks. Due to this relative short cycle, you will find the actual development and the current published rolling release documentation *not* separated. They are both part of the `next` segment in the URL. Compared to production releases where the respective release number is used, the actual rolling release number published can be found e.g. in each service description in section "Environment Variables".

== Try Online

You can try Infinite Scale before you install it locally to get hands-on experience and a feeling for how things work and integrate. Our development provides several instances with different setups to test. The instances are reset on a regular basis. See our https://owncloud.dev/ocis/deployment/continuous_deployment/[Continuous Deployment,window=_blank] page for more details.

== End-User License Agreement (EULA)

ownCloud provides an EULA to clarify, among various topics, who can use this software and which conditions apply to the groups of users defined. See the actual {compose_raw_url}{compose_url_component}/assets/End-User-License-Agreement-for-ownCloud-Infinite-Scale.pdf[EULA] for details.

////

=== Maintenance

Since the integrity and sovereignty of your data is the really important thing when it comes to working in a cloud, you'll need to perform regular backups of your data and keep your Infinite Scale up to date. You'll find everything you need to know in the xref:maintenance/index.adoc[Maintenance] section.

== Upgrading from ownCloud 10

If you already have an ownCloud 10 server running, you'll find the xref:migration/index.adoc[Migration] section most interesting.
////
