= Introduction to ownCloud Infinite Scale
:toc: macro
:toclevels: 2

image::root/beta-badge-1.svg[width=300]
image::root/beta-badge-2.svg[width=300]
image::root/beta-tools.svg[width=300]

:ocis_youtube_long_url: https://www.youtube.com/watch?v=C4a4q9IGyFQ&list=PLXpTv1ixYy3-b5LScHyYqMNwEsZYgejdX&index=16
:ocis_youtube_short_url: C4a4q9IGyFQ

:description: Welcome to the ownCloud Infinite Scale (oCIS) documentation. oCIS is a data platform providing tools to integrate, organize, share and govern data and metadata. This guide provides information on general topics, on installation and administrative tasks for oCIS.

toc::[]

== Introduction

{description}

=== Target Audience

This documentation addresses administrators and technically-oriented management:

* Responsible that services are up and running for users.
* Responsible that the IT infrastructure is in line with the organization's compliance regulations.
* The role as technical advisor / technical buyer.

=== ownCloud Infinite Scale Key Benefits

The oCIS data platform is designed for multi-storage access, is cloud-native (microservices) and provides unified data access.

The key benefits are::

* Integration of distributed data sources into one cloud data ecosystem.
* A unifed data access layer across all data.
* Combination of on-premises and cloud-operated environments into one user experience.
* No need for PHP or a database.
* High performance, flexibility and scalability.
* Extended functionality.
* Single binary or container delivery, shipped with the user interface `ownCloud Web`.

See the following in-line YouTube video for more details or use the link:{ocis_youtube_long_url}[link, window=_blank] to view it in a separate browser tab.

.Infinite Scale - A new era for ownCloud - ownCloud Conference 2021
video::{ocis_youtube_short_url}[youtube]

// fixme: we should have a cross-component link to ownCloud Web when available
// fixme: shall we have a feature list page ?

== Brief Overview

=== Architecture and Concepts

To learn more about oCIS, check out the xref:architecture/architecture.adoc[Architecture and Concepts] section first. This information may help deciding which environment is optimal for your use case and which hardware fits your needs best.

=== Availability and Scalability

With knowledge about architecture and concepts, look at the different xref:availability_scaling/availability_scaling.adoc[Availability and Scalability] options to define the environment oCIS should run on.

=== Prerequisites

With oCIS, not much is needed to run your ownCloud server the way you want. Check out the details in the xref:prerequisites/prerequisites.adoc[Prerequisites] section. We strongly recommend to make up your mind about availability and scalability first.

=== Deployment

oCIS can be deployed via container or you can run the binary installed on a physical or virtual machine. Take a look at the xref:deployment/index.adoc[deployment] options for more details.

=== Configuration

xref:configuration/index.adoc[Configuration] of oCIS is quite different to what you're used to and has never been easier. It works with environment variables and optional configuration files for you to create depending on your specific needs. The settings in configuration files can always be overruled by setting the respective environment variables manually on the command line.

=== Maintenance

Since the integrity and sovereignty of your data is the really important thing when it comes to working in a cloud, you'll need to perform regular backups of your data and keep your oCIS up to date. You'll find everything you need to know in the xref:maintenance/index.adoc[Maintenance] section.

== Upgrading from ownCloud 10

If you already have an ownCloud 10 server running, you'll find the xref:migration/index.adoc[Migration] section most interesting.
