= Container Setup
:toc: right

:docker-ocis-url: https://hub.docker.com/r/owncloud/ocis
:install-docker-server-url: https://docs.docker.com/engine/install/#server
:install-docker-desktop-url: https://docs.docker.com/engine/install/#desktop
:install-d-compose-url: https://docs.docker.com/compose/install/
:docker-cli-url: https://docs.docker.com/engine/reference/commandline/run/
:docker-logs-url: https://docs.docker.com/engine/reference/commandline/logs/
:docker-stop-url: https://docs.docker.com/engine/reference/commandline/stop/
:docker-ps-url: https://docs.docker.com/engine/reference/commandline/ps/
:docker-mount-url: https://docs.docker.com/storage/volumes/
:docker-mount-nfs-url: https://docs.docker.com/storage/volumes/#create-a-service-which-creates-an-nfs-volume
:docker-bindmount-url: https://docs.docker.com/storage/bind-mounts/
:docker-restart-url: https://docs.docker.com/engine/reference/commandline/restart/
:docker-multi-url: https://docs.docker.com/get-started/07_multi_container/
:docker-compose-url: https://docs.docker.com/get-started/08_using_compose/
:compose-examples-url: https://github.com/owncloud/ocis/tree/master/deployments/examples
:docker-desktop-url: https://docs.docker.com/desktop/
:docker-dashboard-url: https://docs.docker.com/desktop/dashboard/
:portainer-url: https://www.portainer.io
:docker-swarm-url: https://docs.docker.com/engine/reference/commandline/swarm/
:kubernetes-url: https://kubernetes.io
:swarm-v-kub-1-url: https://circleci.com/blog/docker-swarm-vs-kubernetes/#c-consent-modal
:swarm-v-kub-2-url: https://vexxhost.com/blog/kubernetes-vs-docker-swarm-containerization-platforms/
:helm-charts-ocis-url: https://github.com/owncloud/ocis-charts

:description: To have a container based setup, container images for oCIS are available on {docker-ocis-url}[Docker Hub]. You can easily download and start such an image with only a few commands. 

== Introduction

{description}

This description mainly focuses on Docker which you can take as template or starting point when using other container managing software products.

== Docker Prerequisites

To fetch and run oCIS in a Docker container, make sure the following packages are installed:

* docker,
* docker-compose,
* optionally kubernetes for more sophisticated container management.

=== Check if You Have Docker Installed

Use the following command to check if `docker` is installed on your system:

[source,bash]
----
which docker
----

If Docker is installed, you'll be informed. If not, you may get no output at all or a message that it couldn't be found. In that case you need to install Docker first.

Use the following command to check if `docker-compose` is installed on your system:

[source,bash]
----
which docker-compose
----

=== Install Docker and Docker-Compose

* On most Linux distributions you can simply install Docker and Docker-Compose via the package manager.
+
Alternatively, install Docker depending on your OS from the Docker site. See {install-docker-server-url}[Install Docker Engine] and {install-d-compose-url}[Install Docker Compose] for details.

* When using macOS, you have to install {docker-desktop-url}[Docker Desktop] which includes the Docker Engine, the Docker CLI client, Docker Compose, {docker-dashboard-url}[Docker Dashboard] and other tools.

== Image Management

=== Download the oCIS Image

// fixme: things are gonna change: after a call with mbarz and cdegen it turns out that latest is not a good idea to use as latest will always point to the master (!) but not to a stable version. atm to use a stable version you would need to use a tag! most likely a "stable" tag will be introduced pointing to the latest stable release and latest will point to the latest master release. this will also be anncounced/described on dockerhub. this means that we have to review the commands below regarding installation, version and upgrade.

To give some terminology guidance, images are unchangeable snapshots of live containers, while containers are running (or stopped) instances of an image.

* To download the latest oCIS image, run the following command. Note that this command will download the correct image suitable for your OS if available. For Windows, oCIS Docker images are not available, but might be in the future:
+
[source,bash]
----
sudo docker pull owncloud/ocis
----

* Check your oCIS image with:
+
[source,bash]
----
sudo docker images
----
+
[caption=]
.Example output
[source,plaintext]
----
REPOSITORY      TAG       IMAGE ID       CREATED       SIZE
owncloud/ocis   latest    fc4151802141   9 hours ago   98.3MB
----

* Check your oCIS version with the following command. Note that you need to have `jq` installed:
+
[source,bash]
----
sudo docker inspect owncloud/ocis:latest | \
   jq '.[] | .Config.Labels."org.opencontainers.image.version"'
----
+
[caption=]
.Example output
[source,plaintext]
----
latest
----

=== Update an Image

First check the current version of the image used with the command above and compare it with the versions available on {docker-ocis-url}[Docker Hub]. When a new image is available use these steps to upgrade the image:

* xref:stop-a-running-container[Stop] the running oCIS container
* xref:remove-an-ocis-image[Remove] the actual image
* xref:download-the-ocis-image[Download] the desired new image
* xref:start-the-ocis-runtime[Start] the oCIS runtime

For detailed commands see the corresponding sections.

=== Remove an oCIS Image

If you want to remove an oCIS image, run the following command:

[source,bash]
----
sudo docker images
----

[caption=]
.Example output
[source,plaintext]
----
REPOSITORY      TAG       IMAGE ID       CREATED        SIZE
owncloud/ocis   latest    22c455afc445   46 hours ago   98.3MB
----

Replace <image-id> with the ID you want to remove from the above printout:
[source,bash]
----
sudo docker rmi <image-id>
----

== Start the oCIS Runtime

When you run the oCIS container, you _must_ specify at least the `OCIS_URL` as environment variable to have browser access. This is  because `localhost` would point to a location inside the container and not to the server being accessed. For details see: xref:deployment/general/general-info.adoc#configurations-to-access-the-webui[Configurations to Access the WebUI].

In the example below, replace `<your-hostname>` with the host name or IP address of your server.

To run the Docker container, simply type:

[source,bash]
----
sudo docker run \
    --name ocis_runtime \
    --rm \
    -it \
    -p 9200:9200 \
    -e OCIS_INSECURE=true \
    -e PROXY_HTTP_ADDR=0.0.0.0:9200 \
    -e OCIS_URL=https://<your-hostname>:9200 \
    owncloud/ocis
----

TIP: Be aware when starting the container, that the xref:deployment/general/general-info.adoc#define-the-ocis-data-path[oCIS datapath] is by default _inside_ the container at `/var/lib/ocis` and therefore not persistent. All your data will be lost when the container stops. If you want to make the content of the oCIS datapath persistent, you need to either mount a {docker-mount-url}[Docker volume] (`--mount`) or use a {docker-bindmount-url}[bind-mount] (`--volume, -v`). For details see the Docker command line options below.

WARNING: While this is not used in production and for testing purposes only, you could run more than one oCIS runtime container concurrently. In such a case, you have to define different ports and data paths for each of the runtime containers to avoid any unexpected behaviour.

The following {docker-cli-url}[Docker command-line options] are quite helpful to know:

--env, -e: Set environment variables::
Use this to pass only a few environment variables to the run command.

--interactive, -i: Keep STDIN open even if not attached::
This keeps STDIN open to the container.

--tty, -t: Allocate a pseudo-TTY::
Allocate a virtual terminal session within the container.

--publish, -p: Publish a container's port(s) to the host::
Defines the port mapping `<hostPort>:<containerPort>`. Use the port mapping if you want to access the dockerized oCIS web user interface.

--rm: Automatically remove the container when it exits::
Tell the Docker daemon to clean up the container and remove the file system after the container exits.

--env-file: Read in a file of environment variables::
If you have more environment variables to hand over, put them all in a file and use this command-line option. Preferably have `/etc/ocis` as location. See xref:deployment/general/general-info.adoc#configuration-rules[Configuration Rules] for more details.

--name: Assign a name to the container::
By default, containers created with _docker run_ are given a random name like `small_roentgen` which may not be suitable to identify their purpose properly. Giving containers a meaningful name helps identifying them more easily.

--restart: Restart policy to apply when a container exits::
See the details in the _docker run_ documentation for available options. Consider `always` as a good starting point.

--mount: Attach a filesystem mount to the container::
{docker-mount-url}[Docker volumes] are completely managed by Docker and have no server OS dependency. See the {docker-mount-nfs-url}[Create a service which creates an NFS volume] for an example. Note to mount the volume with `target=/var/lib/ocis` which uses in the example the default data path.

--volume, -v: Bind mount a volume::
{docker-bindmount-url}[Bind mounts] are dependent on the directory structure and OS of your server. Use this type to mount a local path from your OS. Example: `-v /some/host/dir:/var/lib/ocis` which uses in the example the default data path.
+
NOTE: The filesystem at your OS mount point must be a xref:prerequisites/prerequisites.adoc#filesystems-and-shared-storage[supported filesystem] which supports extended attributes.
+
WARNING: macOS can not use bind mounts as it does not support extended attributes. Use a Docker volume for persistent data instead.

== Execute oCIS Commands

To execute oCIS commands, you have to enter the shell of the running container. To do so xref:list-running-containers[list the running containers] first and type the following command replacing the <container-id> accordingly:

[source,bash]
----
docker exec -it <container-id> sh
----

You can now use commands like `ocis --help` or others to  xref:deployment/general/general-info.adoc#managing-extensions[manage your runtime extensions].

To exit the container's shell, either type kbd:[exit] or kbd:[CTRL+D].

// fixme: after a call with @cdegen, it is currently not clear how to restart a runtime extension properly as the extension needs an extension yaml file (see --config-file) and the question is - where is the location of this file - it cant be inside the container!

== Useful Docker Commands

=== Start the Container Detached

Note that the _docker run_ command will bind the container to the shell you are using. If you want to detach it so it won't be stopped when the shell is closed or gets disconnected (SIGHUP), use the following _docker run_ command-line option:

-d or --detach: Run container in background and print container ID::
The Docker container runs in the background of your terminal. It does not receive input or display output.

=== List Running Containers

To {docker-ps-url}[list] all _running_ containers, type:

[source,bash]
----
docker ps
----

[caption=]
.Example output
[source,plaintext,options="nowrap"]
----
CONTAINER ID   IMAGE           COMMAND                  CREATED         STATUS         PORTS                                       NAMES
a0e4db3e91e8   owncloud/ocis   "/usr/bin/ocis server"   8 seconds ago   Up 6 seconds   0.0.0.0:9200->9200/tcp, :::9200->9200/tcp   ocis_runtime
----

=== Stop a Running Container

To {docker-stop-url}[stop] a runnig detached container, you need the container ID which you will get with the above command. Then type the following command and replace <container-id> with the ID of the container you want to stop:

[source,bash]
----
docker stop <container-id>
----

=== Restarting a Container

{docker-restart-url}[Restarting a Docker container] does an equivalent of `docker stop` and `docker start`. Note that the same parameters are used as before when the container has been started with the _run_ command. To restart a container, type the following and replace the <container-id> accordingly:

[source,bash]
----
docker restart <container-id>
----

=== Autostart oCIS Runtime on Boot

To autostart oCIS when the server boots or reboots, some steps need to be performed.

==== Autostart the Docker Service

Check if the Docker service is set to be automatically started on boot:

[source,bash]
----
systemctl is-enabled docker
----

* If the output is `enabled`, you can proceed with the section to autostart the container.

* If the output is `disabled`, follow the next steps to enable it:
+
[source,bash]
----
sudo systemctl enable --now docker
----
+
This will create an output like:
+
[source,plaintext,options="nowrap"]
----
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /lib/systemd/system/docker.service.
----
+
Then check if the service has started with:
+
[source,bash]
----
sudo systemctl status docker
----
+
This should display an output like:
+
[source,plaintext,options="nowrap"]
----
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     ...
----

==== Dependent Docker Service Startup

When using bind mounts and if you want to ensure that you have e.g. a necessary NFS mount point guaranteed up and running _before_ the Docker service and the Container starts up, see xref:deployment/tips/useful_mount_tip.adoc[Start a Service After a Resource is Mounted].

NOTE: This step can be an important measure, because if the container starts up but the mount point needed is not available, you may be in an undefined oCIS operating state.

==== Autostart the Container

To start the container automatically after the Docker service has started or when the container exits because of an error, add the `--restart=always` command line option to the _docker run_ command. You can replace `always` with other options suitable for your environment. If you do not want the container to autostart any longer, you have to xref:stop-a-running-container[stop] it manually first.

=== Print Logs From Detached Container

The {docker-logs-url}[docker logs] command shows information logged by a running container, which is useful if you have detached it. To show the logs and follow log output, type the following and replace the <container-id> accordingly:

[source,bash]
----
docker logs -f <container-id>
----

== Enhanced Usage

=== Multi-Container Environment

Containers run in isolation and don’t know anything about other processes or containers on the same machine. If containers are on the same network, they can talk to each other. See the {docker-multi-url}[Multi Container Apps] documentation to read more about this topic.

In a nutshell, you have to create a Docker network and reference this network in all the containers that should be able to talk to each other.

=== Docker Compose

Similar to when using _docker run_ and handing over command-line parameters for a single container, you can define a `docker-compose.yml` yaml file which defines all the environment variables for each container in one file. This is the next step of multi-container environments. When the configuration is done, start the application stack with `docker-compose up -d`. For more details see {docker-compose-url}[Docker Compose].

=== Example Compose Files

ownCloud provides some {compose-examples-url}[example docker compose] files as a starting point and guidance for your own setup. Change the data according your needs. Check the oCIS version when using a template for production environments.

=== Container Orchestration

There are many container orchestration tools like {docker-swarm-url}[Docker Swarm] and {kubernetes-url}[Kubernetes].

Container orchestration tools are necessary to meet the requirements described in xref:availability_scaling/#container[Availability and Scalability].

The pages +
{swarm-v-kub-1-url}[Docker Swarm vs Kubernetes: how to choose a container orchestration tool] and +
{swarm-v-kub-2-url}[Kubernetes Vs. Docker Swarm: A Comparison of Containerization Platforms] +
can give a brief overview of their purpose, advantages and disadvantages of both tools.

For Kubernetes, there are already {helm-charts-ocis-url}[Helm Charts] available that can be used and adjusted.

== GUI for Docker

* Docker on Linux does not have a dashboard by default, you have to use available tools like {portainer-url}[Portainer] or others which need manual installation.

* {docker-desktop-url}[Docker Desktop], which is available for macOS, includes the {docker-dashboard-url}[Docker Dashboard] without the need for additional installations.
