= Container Setup
:toc: right

:docker-ocis-url: https://hub.docker.com/r/owncloud/ocis
:install-docker-server-url: https://docs.docker.com/engine/install/#server
:install-docker-desktop-url: https://docs.docker.com/engine/install/#desktop
:install-d-compose-url: https://docs.docker.com/compose/install/
:docker-post-url: https://docs.docker.com/engine/install/linux-postinstall/
:docker-cli-url: https://docs.docker.com/engine/reference/commandline/run/
:docker-logs-url: https://docs.docker.com/engine/reference/commandline/logs/
:docker-stop-url: https://docs.docker.com/engine/reference/commandline/stop/
:docker-ps-url: https://docs.docker.com/engine/reference/commandline/ps/
:docker-mount-url: https://docs.docker.com/storage/volumes/
:docker-mount-nfs-url: https://docs.docker.com/storage/volumes/#create-a-service-which-creates-an-nfs-volume
:docker-bindmount-url: https://docs.docker.com/storage/bind-mounts/
:docker-restart-url: https://docs.docker.com/engine/reference/commandline/restart/
:docker-multi-url: https://docs.docker.com/get-started/07_multi_container/
:docker-compose-url: https://docs.docker.com/get-started/08_using_compose/
:compose-examples-url: https://github.com/owncloud/ocis/tree/master/deployments/examples
:docker-desktop-url: https://docs.docker.com/desktop/
:docker-dashboard-url: https://docs.docker.com/desktop/dashboard/
:portainer-url: https://www.portainer.io
:docker-swarm-url: https://docs.docker.com/engine/reference/commandline/swarm/
:kubernetes-url: https://kubernetes.io
:swarm-v-kub-1-url: https://circleci.com/blog/docker-swarm-vs-kubernetes/#c-consent-modal
:swarm-v-kub-2-url: https://vexxhost.com/blog/kubernetes-vs-docker-swarm-containerization-platforms/
:helm-charts-ocis-url: https://github.com/owncloud/ocis-charts

:description: Images for a container-based setup of Infinite Scale are available on {docker-ocis-url}[Docker Hub]. You can easily download and start such an image with only a few commands. 

== Introduction

{description}

This description mainly focuses on Docker which you can take as template or starting point if you are using different container managing software products.

== Docker Prerequisites

To fetch and run Infinite Scale in a Docker container, make sure the following packages are installed:

* docker,
* docker-compose

=== Check if You Have Docker Installed

* Note that when checking if software is installed on your system with the `which` command below, you might be shown links containing the queried names but pointing to a different program. After running a check via `which`, also try to execute the queried command and look if the output printed comes from docker like in the following example:
+
[source,plaintext]
----
Usage:  docker [OPTIONS] COMMAND
or
Usage:  docker compose [OPTIONS] COMMAND
----

* Use the following command to check if `docker` is installed on your system:
+
[source,bash]
----
which docker
----
+
If Docker is installed, you'll be informed. If not, you may get no output at all or a message that it couldn't be found. In that case you need to install Docker first.

* Use the following command to check if `docker-compose` is installed on your system:
+
[source,bash]
----
which docker-compose
----

=== Install Docker and Docker-Compose

* On most Linux distributions you can simply install Docker and Docker-Compose via the package manager, usually Kubernetes as well.
+
Alternatively, install Docker depending on your OS from the Docker site. See {install-docker-server-url}[Install Docker Engine] and {install-d-compose-url}[Install Docker Compose] for details.

* When using macOS, you have to install {docker-desktop-url}[Docker Desktop] which includes the Docker Engine, the Docker CLI client, Docker Compose, {docker-dashboard-url}[Docker Dashboard] and other tools.

=== Check the Docker Group Membership

Running a Docker container without root privileges (`sudo`), requires the user to be a member of the docker group.

First check if the docker group is already created and you are member of this group:

[source,bash]
----
cat /etc/group | grep docker
----

[source,plaintext]
----
docker:x:998:<your-user-name>
----

If the group does not exist or you are not a member, continue with {docker-post-url}[Post-installation steps for Linux] to create the group and add your user to it.

== Image Management

=== Download the Infinite Scale Image

// fixme: things are gonna change: after a call with mbarz and cdegen it turns out that latest is not a good idea to use as latest will always point to the master (!) but not to a stable version. atm to use a stable version you would need to use a tag! most likely a "stable" tag will be introduced pointing to the latest stable release and latest will point to the latest master release. this will also be anncounced/described on dockerhub. this means that we have to review the commands below regarding installation, version and upgrade. see: https://github.com/owncloud/ocis/issues/3578 [Proposal] Use stable tag for most recent stable release of ocis

// fixme: have other and more default registries (locations where you can download containers), means we have to add a url-prefix to define where to download, see: https://github.com/owncloud/ocis/issues/3577 [Proposal] Parallel pushing to multiple registries

To give some terminology guidance, images are unchangeable snapshots of live containers, while containers are running (or stopped) instances of an image.

* To download the _latest_ Infinite Scale image, run the following command. Note that this command will download the correct image suitable for your OS if available. For Windows, Infinite Scale Docker images are not available, but might be in the future. The _latest_ tag always reflects the current master branch:
+
[source,bash]
----
docker pull owncloud/ocis
----

* Check your Infinite Scale image with:
+
[source,bash]
----
docker images
----
+
[caption=]
.Example output
[source,plaintext]
----
REPOSITORY      TAG       IMAGE ID       CREATED       SIZE
owncloud/ocis   latest    fc4151802141   9 hours ago   98.3MB
----

* Check your Infinite Scale version with the following command. Note that you need to have `jq` installed:
+
[source,bash]
----
docker inspect owncloud/ocis:latest | \
   jq '.[] | .Config.Labels."org.opencontainers.image.version"'
----
+
[caption=]
.Example output
[source,plaintext]
----
latest
----

=== Update an Image

First check the current version of the image used with the command above and compare it with the versions available on {docker-ocis-url}[Docker Hub]. When a new image is available use these steps to upgrade the image:

* xref:stop-a-running-container[Stop] the running Infinite Scale container
* xref:remove-an-ocis-image[Remove] the actual image
* xref:download-the-ocis-image[Download] the desired new image
* xref:start-the-ocis-runtime[Start] the Infinite Scale runtime

For detailed commands see the corresponding sections.

=== Remove an Infinite Scale Image

If you want to remove an Infinite Scale image, run the following command:

[source,bash]
----
docker images
----

[caption=]
.Example output
[source,plaintext]
----
REPOSITORY      TAG       IMAGE ID       CREATED        SIZE
owncloud/ocis   latest    22c455afc445   46 hours ago   98.3MB
----

Replace <image-id> with the ID you want to remove from the above printout:
[source,bash]
----
docker rmi -f <image-id>
----

== Start the Infinite Scale Runtime

Infinite Scale is started in two steps:

* A first time start to initiate the system and
* a recurring start after initialization.

Refer to the xref:deployment/general/general-info.adoc#default-users-and-groups[Default Users and Groups] section if you want to have demo users created when initializing the system.

=== Preperation

In the examples shown below, bind mounts with the following folders are used to keep data persistent and located in your home directory. Change the locations according your needs:
 
* For the config we use the folder `~/ocis/ocis-config`.
* For data we use the folder `~/ocis/ocis-data`.

The Infinite Scale container runs internally with the default user and group ID of 1000. To check this, type:

[source,bash]
----
docker inspect owncloud/ocis | less | grep -i user | sort -u
----
[source,plaintext]
----
"User": "1000",
----

For the folders above, the following rules apply:

* Because _bind-mounts_ (used in the example below) create paths if they do not exist with the root user and group, the container user cannot write into them. To overcome this issue, you have to create both folders upfront manually to avoid a permission denied problem. To do so, type:
+
--
[source,bash]
----
mkdir -p ~/ocis/ocis-config
----
[source,bash]
----
mkdir -p ~/ocis/ocis-data
----
--

* The user you have logged in with must have the default user and group ID of 1000 to match the container user and group ID. If this does not match, you must take care that the container user can write into the created paths. You can do this for example with the command:
+
--
[source,bash]
----
sudo chown -Rfv 1000:1000 ocis/
----
In this case, you need to access the content of the `ocis` folder with root privileges or with a user matching the owner ID.
--

=== First Time Start

Infinite Scale needs a first time initialization to set up the environment. You will need to answer questions as basis for a default `ocis.yaml` file to be generated. This file you can edit later. Note that if you do not define a host directory with a bind mount as target location, the initial setup will get lost because the container ends after executing the command. ownCloud therefore recommends either using bind mounts or Docker volumes to make the initial setup, further changes and your data persistent.

[source,bash]
----
docker run --rm -it \
    -v ~/ocis/ocis-config:/etc/ocis \
    owncloud/ocis init
----

On success, you will see a message like:
 
include::partial$deployment/ocis_init.adoc[]

=== Recurring Start of Infinite Scale

When you run the Infinite Scale container, you _must_ specify at least the `OCIS_URL` as environment variable to have browser access. This is  because `localhost` would point to a location inside the container and not to the server being accessed. For details see: xref:deployment/general/general-info.adoc#configurations-to-access-the-webui[Configurations to Access the WebUI].

In the example below, replace `<your-hostname>` with the host name or IP address of your server.

To run the Docker container, simply type:

[source,bash]
----
docker run \
    --name ocis_runtime \
    --rm \
    -it \
    -p 9200:9200 \
    -v ~/ocis/ocis-config:/etc/ocis \
    -v ~/ocis/ocis-data:/var/lib/ocis \
    -e OCIS_INSECURE=true \
    -e PROXY_HTTP_ADDR=0.0.0.0:9200 \
    -e OCIS_URL=https://<your-hostname>:9200 \
    owncloud/ocis
----

To access Infinite Scale, open your browser and type `\https://<your-hostname>:9200`.

WARNING: While this is not used in production and for testing purposes only, you could run more than one Infinite Scale runtime container concurrently. In such a case, you have to define different ports and data paths for each of the runtime containers to avoid unexpected behavior.

=== Delete a Setup

If you want to delete your setup, which is _both_ the configuration and the data, just delete the `ocis-config` and the `ocis-data` folder and restart the process described in this chapter.

== Execute Infinite Scale Commands

To execute Infinite Scale commands, you have to enter the shell of the running container. To do so, xref:list-running-containers[list the running containers] first and type the following command replacing the <container-id> accordingly:

[source,bash]
----
docker exec -it <container-id> sh
----

You can now use commands like `ocis --help` or others to  xref:deployment/general/general-info.adoc#managing-extensions[manage your runtime extensions].

To exit the container's shell, either type kbd:[exit] or kbd:[CTRL+D].

// fixme: after a call with @cdegen, it is currently not clear how to restart a runtime extension properly as the extension needs an extension yaml file (see --config-file) and the question is - where is the location of this file - it cant be inside the container!

== Useful Docker Parameters

The following {docker-cli-url}[Docker command-line options] are quite helpful to know:

--env, -e: Set environment variables::
Use this to pass only a few environment variables to the run command.

--interactive, -i: Keep STDIN open even if not attached::
This keeps STDIN open to the container.

--tty, -t: Allocate a pseudo-TTY::
Allocate a virtual terminal session within the container.

--publish, -p: Publish a container's port(s) to the host::
Defines the port mapping `<hostPort>:<containerPort>`. Use the port mapping if you want to access the dockerized Infinite Scale web user interface.

--rm: Automatically remove the container when it exits::
Tell the Docker daemon to clean up the container and remove the file system after the container exits.

--env-file: Read in a file of environment variables::
If you have more environment variables to hand over, put them all in a file and use this command-line option. Preferably use `/etc/ocis` on your host as location. See xref:deployment/general/general-info.adoc#configuration-rules[Configuration Rules] for more details.

--name: Assign a name to the container::
By default, containers created with _docker run_ are given a random name like `small_roentgen` which may not be suitable to identify their purpose properly. Giving containers a meaningful name helps identifying them more easily.

--restart: Restart policy to apply when a container exits::
See the details in the _docker run_ documentation for available options. Consider `always` as a good starting point.

--mount: Attach a filesystem mount to the container::
{docker-mount-url}[Docker volumes] are completely managed by Docker and have no server OS dependency. See {docker-mount-nfs-url}[Create a service which creates an NFS volume] for an example. Note the volume mount target path `target=/var/lib/ocis` which uses the default Infinite Scale data path if not otherwise defined. Note that the directory on the host must already exist, it will not be created. 

--volume, -v: Bind mount a volume::
{docker-bindmount-url}[Bind mounts] depend on the directory structure and OS of your server. Use this type to mount a local directory of your OS. Example: `-v /some/host/dir:/var/lib/ocis`, which uses the default Infinite Scale data path if not otherwise defined. If the bind-mount points to a directory that does not yet exist on the host, the directory will be created automatically using the user the docker _service_ runs with, usually the root user.
+
NOTE: The filesystem at your OS mount point must be a xref:prerequisites/prerequisites.adoc#filesystems-and-shared-storage[supported filesystem] which supports extended attributes.
+
WARNING: macOS cannot use bind mounts, as Docker Desktop for macOS does currently not fully support extended attributes. Use a Docker volume for persistent data instead.

== Useful Docker Commands

=== Start the Container Detached

Note that the _docker run_ command will bind the container to the shell you are using. If you want to detach it so it won't be stopped when the shell is closed or gets disconnected (SIGHUP), use the following _docker run_ command-line option:

-d, --detach: Run container in background and print container ID::
The Docker container runs in the background of your terminal. It does not receive input or display output.

=== List Running Containers

To {docker-ps-url}[list] all _running_ containers, type:

[source,bash]
----
docker ps
----

[caption=]
.Example output
[source,plaintext,options="nowrap"]
----
CONTAINER ID   IMAGE           COMMAND                  CREATED         STATUS         PORTS                                       NAMES
a0e4db3e91e8   owncloud/ocis   "/usr/bin/ocis server"   8 seconds ago   Up 6 seconds   0.0.0.0:9200->9200/tcp, :::9200->9200/tcp   ocis_runtime
----

=== Stop a Running Container

To {docker-stop-url}[stop] a runnig detached container, you need the container ID which you will get with the above command. Then type the following command and replace <container-id> with the ID of the container you want to stop:

[source,bash]
----
docker stop <container-id>
----

=== Restarting a Container

{docker-restart-url}[Restarting a Docker container] does an equivalent of `docker stop` and `docker start`. Note that the same parameters are used as before when the container has been started with the _run_ command. To restart a container, type the following and replace the <container-id> accordingly:

[source,bash]
----
docker restart <container-id>
----

=== Autostart Infinite Scale Runtime on Boot

To autostart Infinite Scale when the server boots or reboots, some steps need to be performed.

==== Autostart the Docker Service

Check if the Docker service is set to be automatically started on boot:

[source,bash]
----
sudo systemctl is-enabled docker
----

* If the output is `enabled`, you can proceed with the section to autostart the container.

* If the output is `disabled`, follow the next steps to enable it:
+
[source,bash]
----
sudo systemctl enable --now docker
----
+
This will create an output like:
+
[source,plaintext,options="nowrap"]
----
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /lib/systemd/system/docker.service.
----
+
Then check if the service has started with:
+
[source,bash]
----
sudo systemctl status docker
----
+
This should display an output like:
+
[source,plaintext,options="nowrap"]
----
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     ...
----

==== Dependent Docker Service Startup

If you are using bind mounts and want to ensure that you have e.g. a necessary NFS mount point up and running _before_ the Docker service and the container starts up, see xref:deployment/tips/useful_mount_tip.adoc[Start a Service After a Resource is Mounted].

NOTE: This step can be an important measure, because if the container starts up but the necessary mount point is not available, you may be in an undefined Infinite Scale operating state.

==== Autostart the Container

To start the container automatically after the Docker service has started or when the container exits because of an error, add the `--restart=always` command line option to the _docker run_ command. You can replace `always` with other options suitable for your environment. If you do not want the container to autostart any longer, you have to xref:stop-a-running-container[stop] it manually first.

=== Print Logs From Detached Container

The {docker-logs-url}[docker logs] command shows information logged by a running container, which is useful if you have detached it. To show the logs and follow log output, type the following and replace the <container-id> accordingly:

[source,bash]
----
docker logs -f <container-id>
----

== Enhanced Usage

=== Multi-Container Environment

Containers run in isolation and don’t know anything about other processes or containers on the same machine. If containers are on the same network, they can talk to each other. See the {docker-multi-url}[Multi Container Apps] documentation to read more about this topic.

In a nutshell, you have to create a Docker network and reference this network in all the containers that should be able to talk to each other.

== GUI for Docker

* Docker on Linux does not have a dashboard by default, you have to use available tools like {portainer-url}[Portainer] or others which need manual installation.

* {docker-desktop-url}[Docker Desktop], which is available for macOS, includes the {docker-dashboard-url}[Docker Dashboard] without the need for additional installations.

== Container Orchestration

There are many container orchestration tools like {docker-swarm-url}[Docker Swarm] and {kubernetes-url}[Kubernetes].

Container orchestration tools are necessary to meet the requirements described in xref:availability_scaling/availability_scaling.adoc#container[Availability and Scalability].

The pages +
{swarm-v-kub-1-url}[Docker Swarm vs Kubernetes: how to choose a container orchestration tool] and +
{swarm-v-kub-2-url}[Kubernetes Vs. Docker Swarm: A Comparison of Containerization Platforms] +
can give a brief overview of their purpose, advantages and disadvantages of both tools.

// fixme: there should be a link instead of the next line to the upcoming Kubernetes documentation
 
For Kubernetes, there are already {helm-charts-ocis-url}[Helm Charts] available that can be used and adjusted.

== Docker Compose

Similar to when using _docker run_ and handing over command-line parameters for a single container, you can define a `docker-compose.yml` yaml file which defines all the environment variables for each container in one file. This is the next step of multi-container environments.

Create a project directory, e.g. `ocis-compose`. Depending on your deployment intentions, pick configurations from our {compose-examples-url}[example docker compose] files or a complete stack.

These are bundles of containers. For example, https://owncloud.dev/ocis/deployment/ocis_keycloak/[ocis_keycloak] delivers Keycloak and Infinite Scale, running behind Traefik as reverse proxy. Traefik generates self-signed certificates for a local setup or obtains valid SSL certificates for a server setup. Keycloak acts as Identity Provider (IDP) and comes with a PostgreSQL database. In total, this stack consists of four containers.

In this example, you'll need three domains set up. For experimenting with a local setup, you may want to simply add them to your `/etc/hosts` file.

[source,plaintext]
----
127.0.0.1 ocis.owncloud.test
127.0.0.1 traefik.owncloud.test
127.0.0.1 keycloak.owncloud.test
----

Download the `ocis_keycloak` files from GitHub into your project directory. Open the file `.env` file in a text editor and adjust the environment variables according to your wishes. The default configuration looks like this:

[source,plaintext]
----
# If you're on a internet facing server please comment out following line.
# It skips certificate validation for various parts of oCIS and is needed if you use self signed certificates.
INSECURE=true

# The demo users should not be created on a production instance
# because their passwords are public
DEMO_USERS=false

### Traefik settings ###
# Serve Traefik dashboard. Defaults to "false".
TRAEFIK_DASHBOARD=

# Domain of Traefik, where you can find the dashboard. Defaults to "traefik.owncloud.test"
TRAEFIK_DOMAIN=

# Basic authentication for the dashboard. Defaults to user "admin" and password "admin"
TRAEFIK_BASIC_AUTH_USERS=

# Email address for obtaining LetsEncrypt certificates, needs only be changed if this is a public facing server
TRAEFIK_ACME_MAIL=

### oCIS settings ###
# oCIS version. Defaults to "latest"
OCIS_DOCKER_TAG=

# Domain of oCIS, where you can find the frontend. Defaults to "ocis.owncloud.test"
OCIS_DOMAIN=

# owncloud Web openid connect client id. Defaults to "web"
OCIS_OIDC_CLIENT_ID=

# IDP LDAP bind password. Must be changed in order to have a secure oCIS. Defaults to "idp".
IDP_LDAP_BIND_PASSWORD=

# Storage LDAP bind password. Must be changed in order to have a secure oCIS. Defaults to "reva".
STORAGE_LDAP_BIND_PASSWORD=

# JWT secret which is used for the storage provider. Must be changed in order to have a secure oCIS. Defaults to "Pive-Fumkiu4"
OCIS_JWT_SECRET=

# JWT secret which is used for uploads to create transfer tokens. Must be changed in order to have a secure oCIS. Defaults to "replace-me-with-a-transfer-secret"
STORAGE_TRANSFER_SECRET=

# Machine auth api key secret. Must be changed in order to have a secure oCIS. Defaults to "change-me-please"
OCIS_MACHINE_AUTH_API_KEY=

### Keycloak ###
# Domain of Keycloak, where you can find the management and authentication frontend. Defaults to "keycloak.owncloud.test"
KEYCLOAK_DOMAIN=

# Realm which to be used with oCIS. Defaults to "oCIS"
KEYCLOAK_REALM=

# Admin user login name. Defaults to "admin"
KEYCLOAK_ADMIN_USER=

# Admin user login password. Defaults to "admin"
KEYCLOAK_ADMIN_PASSWORD=

# If you want to use debugging and tracing with this stack,
# you need uncomment following line. Please see documentation at
# https://owncloud.dev/ocis/deployment/monitoring-tracing/
#COMPOSE_FILE=docker-compose.yml:monitoring_tracing/docker-compose-additions.yml
----

If you are installing Infinite Scale on a server and Traefik will obtain valid certificates for you, remove `INSECURE=true` or set it to `false`.

If you want to use the Traefik dashboard, set `TRAEFIK_DASHBOARD=true`. Default is `false` and therefore the dashboard is not active. If you activate it, you must set a domain for the Traefik dashboard in `TRAEFIK_DOMAIN=`, e.g. `TRAEFIK_DOMAIN=traefik.owncloud.test`.

The Traefik dashboard is secured by basic auth. Default credentials are the user `admin` with the password admin. To set your own credentials, generate a htpasswd, e.g. by using an https://htpasswdgenerator.de/[online tool] or a command line tool.

Traefik will issue certificates with LetsEncrypt and therefore you must set an email address in `TRAEFIK_ACME_MAIL=`.

By default Infinite Scale will be started in the latest version. If you want to start a specific version set it with `OCIS_DOCKER_TAG=`. Available versions can be found on https://hub.docker.com/r/owncloud/ocis/tags?page=1&ordering=last_updated[Docker Hub].

Set your domain for the Infinite Scale frontend in `OCIS_DOMAIN=`, e.g. `OCIS_DOMAIN=ocis.owncloud.test`.

If you want to change the OIDC client ID of the ownCloud Web frontend, specify the name with `OCIS_OIDC_CLIENT_ID=`.

Set your domain for the Keycloak administration panel and authentication endpoints with `KEYCLOAK_DOMAIN=`, e.g. `KEYCLOAK_DOMAIN=keycloak.owncloud.test`.

Changing the used Keycloak realm can be done by setting `KEYCLOAK_REALM=`. This defaults to the Infinite Scale realm `KEYCLOAK_REALM=oCIS`. The Infinite Scale realm will be automatically imported on startup and includes our demo users.

You should secure your Keycloak admin account by setting `KEYCLOAK_ADMIN_USER=` and `KEYCLOAK_ADMIN_PASSWORD=` to values other than `admin`.

When you're done with the configuration, save the file and start the application stack from the project directory with `docker-compose up -d`. For more details see {docker-compose-url}[Docker Compose].

Check out the other container stacks on GitHub as well and adjust them to your needs.

ownCloud provides some {compose-examples-url}[example docker compose] files as a starting point and guidance for your own setup. Change the data according your needs. Check the Infinite Scale version when using a template for production environments.
