= Binary Setup
:toc: right
:toclevels: 3

:downloadpage_ocis_url: https://download.owncloud.com/ocis/ocis/stable/?sort=time&order=desc
:systemd-url: https://systemd.io/
:traefik-url: https://doc.traefik.io/traefik/getting-started/install-traefik/

:description: Infinite Scale can either be downloaded from ownCloud or installed via the package manger of your Linux system. Use the way you prefer, but keep in mind that the download version is updated more frequently than the package manager version.

== Introduction

{description}

Installing the Infinite Scale binary manually works well if you want to quickly test Infinite Scale without performing additional tasks like a container preparation or Kubernetes deployment. Of course you can use it for production in your environment, too. See the xref:availability_scaling/availability_scaling.adoc[Availability and Scalability] documentation for impacts. 

== Prerequisite

NOTE: Infinite Scale by default relies on Multicast DNS (mDNS), usually via `avahi-daemon`. If your system has a firewall, make sure mDNS is allowed in your active zone.

== Installation

* To get the stable binary from ownCloud, visit {downloadpage_ocis_url}[download.owncloud.com], select the version and the platform of choice and copy the link of the file. Check the sort order on the modification date to get the most recent releases on top. Depending on your system and preferences, you may want to save the binary in `/usr/bin/`
+
To download use:
+
[source,bash]
----
sudo wget -O /usr/bin/ocis <link>
----
+
Make the binary executable with:
+
[source,bash]
----
sudo chmod +x /usr/bin/ocis
----
+
Check the version installed:
+
[source,bash]
----
ocis version
----
+
The output looks like this:
+
[source,plaintext,subs="attributes+"]
----
ocis version {ocis-version}
----

// fixme: recommended directory possibly to be adjusted when we actually have a recommended or standard location.

* To install Infinite Scale via the package manager of your Linux system, use the package manager commands to search for ocis and install it accordingly.
+
[NOTE]
====
Package manager installation is in preperation and will be available soon.
====

== Getting Command Line Help

To get a list of available options and commands type:

[source,bash]
----
ocis
----

or

[source,bash]
----
ocis --help
----

== Accessing the Infinite Scale Runtime

When you have configured and started the Infinite Scale _runtime_ either xref:starting-infinite-scale[manually] or via xref:setting-up-systemd-for-infinite-scale[systemd] as described below, you can access it via a browser using `localhost:9200` or whatever URL and port you have defined.

== Start and Stop Infinite Scale

=== Starting Infinite Scale

Infinite Scale is started in two steps:

* A first time start to initiate the system and
* a recurring start after initialization.

Refer to the xref:deployment/general/general-info.adoc#default-users-and-groups[Default Users and Groups] section if you want to have demo users created when initializing the system.

==== First Time Start

Infinite Scale needs a first time initialization to set up the environment. You will need to answer questions as basis for a default `ocis.yaml` file to be generated. This file you can edit later. The default location for config files is, if not otherwise defined `$HOME/.ocis/config/`. For details see: xref:deployment/general/general-info.adoc#configuration-rules[Configuration Rules]. Type the following command to initialize Infinite Scale.

[source,bash]
----
ocis init
----

On success, you will see a message like:
 
include::partial$deployment/ocis_init.adoc[]

==== Recurring Start of Infinite Scale

After initializing Infinite Scale for the first time, you can start the Infinite Scale runtime which includes embedded extensions. See the sections xref:deployment/general/general-info.adoc#starting-infinite-scale-with-environment-variables[Starting Infinite Scale With Environment Variables] and xref:deployment/general/general-info.adoc#configurations-to-access-the-webui[Configurations to Access the WebUI] or xref:deployment/general/general-info.adoc#define-the-infinite-scale-data-path[Define the Infinite Scale Data Path] for basic environment variables.

The example commands shown below have no environment variables or command line options for ease of reading, add them according your needs.

To start the Infinite Scale runtime type:

[source,bash]
----
ocis server
----

Note that this will bind `ocis` to the shell you are running. If you want to detatch it and avoid it gets stopped when closing the shell or the shell gets disconnected (SIGHUP), use the following command:

[source,bash]
----
ocis server & disown -h
----

The same mechanism is true to start or instantinate extensions which are *not started as part of the runtime* like:

[source,bash]
----
ocis web server & disown -h
----

NOTE: Instantination of runtime extensions will cause errors, for more details see: xref:deployment/general/general-info.adoc#managing-extensions[Managing Extensions]

=== List Running Infinite Scale Processes

To list all running ocis processes type:

[source,bash]
----
ps ax | grep ocis | grep -v grep
----

[source,plaintext]
----
 221297 pts/1    Sl     0:04 ocis server
 221706 pts/0    Sl     0:00 ocis proxy
----

=== Stopping Infinite Scale

Depending what you want to stop, differnt commands need to be applied.

If a service is being terminated with its PID, the signal `SIGTERM` (-15) is used. Note that SIGTERM politely ask a process to terminate. It shall terminate gracefully, cleaning up all resources (files, sockets, child processes, etc.), deleting temporary files and so on.

Stopping an extension from the runtime::
Note that the ocis runtime (`ocis server`) needs to be active or a default error message will be returned, see xref:deployment/general/general-info.adoc#default-runtime-error-response[Default Runtime Error Response]
+
[source,bash]
----
ocis kill [extension name]
----

Stopping the complete runtime with all its running extensions::
Depending on the user you started `ocis` and with which user you are currently logged in, you may need to use `sudo` for proper permissions.
+ 
[source,bash]
----
ps ax | grep "ocis server" | grep -v grep | awk '{ print $1 }' | xargs kill -15
----

Stopping a particular ocis PID::
First identify which PID you want to terminate:
+
[source,bash]
----
ps ax | grep "ocis" | grep -v grep
----
+
This may give an output like the following:
+
[source,plaintext]
----
 221297 pts/1    Sl     0:04 ocis server
 221706 pts/0    Sl     0:00 ocis proxy
----
+
To terminate the `ocis proxy` service type the following command, where `sudo` may not be necessary depending on the permissions of the logged in user. Replace the PID according the output from above:
+
[source,bash]
----
sudo kill -15 221706
----

== Setting up systemd for Infinite Scale

To run the *Infinite Scale runtime* as a {systemd-url}[systemd] service, create the file `/etc/systemd/system/ocis.service` with the content provided below. The easiest way to do this is with the following command:

[source,bash]
----
sudo systemctl edit ocis.service
----

Then copy the content of the systemd file below into the editor and save it.

// info: we use the user ocis as example in the same way as users are created for apache, nginx mysql etc

* The user `ocis` is just a placeholder for any user to run Infinite Scale, the user must exist or be created first.
+
[NOTE]
====
This user can be a system user. The following example will create a system user and group named _ocis_ with no home directory, no login shell and no password. Depending on your OS type:

[source,bash]
----
sudo useradd --system --no-create-home --shell=/sbin/nologin ocis
----
====
+
* We strongly advise *against* using the user `root` for this purpose.
* Placing the environment file in `/etc/ocis/` is only a suggestion, but a good one.
** The directory `/etc/ocis/` must exist and `ocis` must be able to read it. For security reasons, this user should have restricted permissions. Create and set permissions, adjust the values according to your needs:
+
[source,bash]
----
sudo mkdir -p /etc/ocis
sudo chown -R ocis /etc/ocis
sudo chmod 0570 /etc/ocis
----

[caption=]
.systemd file
[source,plaintext]
----
[Unit]
Description=OCIS server

[Service]
Type=simple
User=ocis
Group=ocis
EnvironmentFile=/etc/ocis/ocis.env
ExecStart=ocis server
Restart=always

[Install]
WantedBy=multi-user.target
----

Now create the file `/etc/ocis/ocis.env` with the definitions of environment variables. See the following sections for additional environment variables like xref:deployment/general/general-info.adoc#configurations-to-access-the-webui[Configurations to Access the WebUI] or xref:deployment/general/general-info.adoc#define-the-infinite-scale-data-path[Define the Infinite Scale Data Path].

NOTE: This is just an example with a minimal set of environment variables used.

[source,plaintext]
----
OCIS_INSECURE=true
OCIS_URL=https://localhost:9200
PROXY_HTTP_ADDR=0.0.0.0:9200

OCIS_LOG_LEVEL=error
----

Run the following command to apply your changes:

[source,bash]
----
sudo systemctl daemon-reload
----

Now you can run Infinite Scale as a systemd service. Start it with:

[source,bash]
----
sudo systemctl enable --now ocis
----

With this setup, Infinite Scale is restarted automatically after a reboot.

If you need to restart Infinite Scale because of configuration changes in `/etc/ocis/ocis.env`, run:

[source,bash]
----
sudo systemctl restart ocis
----

The logs of Infinite Scale can be displayed by issuing:

[source,bash]
----
sudo journalctl -f -u ocis
----

=== Dependent Infinite Scale Service Startup

If you want to ensure that you have e.g. a necessary NFS mount point up and running _before_ the Infinite Scale service starts up, see xref:deployment/tips/useful_mount_tip.adoc[Start a Service After a Resource is Mounted].

NOTE: This step can be an important measure, because if the Infinite Scale service starts up but the necessary mount point is not available, you may be in an undefined Infinite Scale operating state.
