= Binary Setup
:toc: right
:toclevels: 3

:systemd-url: https://systemd.io/
:traefik-url: https://doc.traefik.io/traefik/getting-started/install-traefik/

:ocis_bin: /usr/local/bin
:ocis_env: /etc/ocis
:ocis_data: /var/lib/ocis
:ocis_url: ocis.example.com
:ocis_port: 9200

:description: Installing the Infinite Scale binary manually works well if you want to quickly test Infinite Scale without performing additional tasks

== Introduction

This description gives a brief overview and can be used as basic template running the ocis binary, including an example of how to configure systemd. It does not cover extended deployment tasks

{description} like a container preparation, Kubernetes deployment or using a reverse proxy. Of course you can use it for production in your environment, too. See the xref:availability_scaling/availability_scaling.adoc[Availability and Scalability] documentation for impacts. 

Infinite Scale can either be downloaded from ownCloud or installed via the package manager of your Linux system. Packages will be available soon. Use the way you prefer, but keep in mind that the download version is updated more frequently than the package manager version.

IMPORTANT: ownCloud highly recommends reading the xref:deployment/general/general-info.adoc[General Info] as it contains valuable information about configuration rules, managing services and default paths - just to mention some of the useful topics.

== Prerequisite

NOTE: Infinite Scale by default relies on Multicast DNS (mDNS), usually via `avahi-daemon`. If your system has a firewall, make sure mDNS is allowed in your active zone and http and https ports are open.

== Installation

* To get the stable binary from ownCloud, visit {ocis-downloadpage-url}?sort=time&order=desc[download.owncloud.com,window=_blank], select the version and the platform of choice and copy the link of the file. Check the sort order on the modification date to get the most recent releases on top. Depending on your system and preferences, you may want to save the binary in `{ocis_bin}`.
+
To download use:
+
[source,bash,subs="attributes+"]
----
sudo wget -O {ocis_bin}/ocis <file_url>
----
+
Make the binary executable with:
+
[source,bash,subs="attributes+"]
----
sudo chmod +x {ocis_bin}/ocis
----
+
Check the version installed:
+
[source,bash,subs="attributes+"]
----
ocis version
----
+
The output looks like this:
+
[source,plaintext,subs="attributes+"]
----
ocis version {ocis-version}
----

// fixme: recommended directory possibly to be adjusted when we actually have a recommended or standard location.

* To install Infinite Scale via the package manager of your Linux system, use the package manager commands to search for ocis and install it accordingly.
+
[NOTE]
====
Package manager installation is in preparation and will be available soon.
====

== Getting Command Line Help

To get a list of available options and commands type:

[source,bash]
----
ocis
----

or

[source,bash]
----
ocis --help
----

== Accessing the Infinite Scale Runtime

When you have configured and started the Infinite Scale _runtime_ either xref:starting-infinite-scale[manually] or via xref:setting-up-systemd-for-infinite-scale[systemd] as described below, you can access it via a browser using `https://localhost:{ocis_port}` or whatever URL and port you have defined.

== Start and Stop Infinite Scale

=== Starting Infinite Scale

Infinite Scale is started in two steps:

* A first time start to initialize the system and
* a recurring start after initialization.

Refer to the xref:deployment/general/general-info.adoc#default-users-and-groups[Default Users and Groups] section if you want to have demo users created when initializing the system.

==== First Time Start

Infinite Scale needs a xref:deployment/general/general-info.adoc#initialize-infinite-scale[first time initialization] to set up the environment. You will need to answer questions as the basis for generating a default `ocis.yaml` file. You can edit this file later. The default location for config files is, if not otherwise defined, `$HOME/.ocis/config/`. For details see: xref:deployment/general/general-info.adoc#configuration-rules[Configuration Rules]. Type the following command to initialize Infinite Scale.

[source,bash]
----
ocis init
----

On success, you will see a message like:

:init_path: pass:[<your-user>/.ocis/config/ocis.yaml]

include::partial$deployment/ocis_init.adoc[]

[NOTE]
====
If you get an error message like the following:

[source,plaintext]
----
Could not create config: config in ~/.ocis/config/ocis.yaml already exists
----

you already have created a configuration once. As you cannot overwrite the existing configuration, you must delete the old configuration first to proceed. For more details, see: xref:deployment/general/general-info.adoc#initialize-infinite-scale[Initialize Infinite Scale].
====

==== Recurring Start of Infinite Scale

After initializing Infinite Scale for the first time, you can start the Infinite Scale runtime which includes embedded services. See the sections xref:deployment/general/general-info.adoc#starting-infinite-scale-with-environment-variables[Starting Infinite Scale With Environment Variables] and xref:deployment/general/general-info.adoc#configurations-to-access-the-webui[Configurations to Access the WebUI] or xref:deployment/general/general-info.adoc#base-data-directory[Base Data Directory] for basic environment variables.

The example commands shown below have no environment variables or command line options for ease of reading, add them according your needs.

To start the Infinite Scale runtime type:

[source,bash]
----
ocis server
----

Note that this will bind `ocis` to the shell you are running. If you want to detach it and avoid it being stopped when closing the shell or the shell gets disconnected (SIGHUP), use the following command:

[source,bash]
----
ocis server & disown -h
----

The same mechanism is true to start or instantiate services which are *not started as part of the runtime* like:

[source,bash]
----
ocis web server & disown -h
----

NOTE: Instantiation of runtime services will cause errors, for more details see: xref:deployment/general/general-info.adoc#managing-services[Managing Services]

=== List Running Infinite Scale Processes

To list all running ocis processes type:

[source,bash]
----
ps ax | grep ocis | grep -v grep
----

[source,plaintext]
----
 221297 pts/1    Sl     0:04 ocis server
 221706 pts/0    Sl     0:00 ocis proxy
----

=== Stopping Infinite Scale

Depending on what you want to stop, different commands need to be applied.

If a service is being terminated with its PID, the signal `SIGTERM` (-15) is used. Note that SIGTERM politely asks a process to terminate. It will terminate gracefully, cleaning up all resources (files, sockets, child processes, etc.), deleting temporary files and so on.

Stopping the complete runtime with all its running services::
Depending on the user you started `ocis` with and which user you are currently logged in as, you may need to use `sudo` for proper permissions.
+ 
[source,bash]
----
ps ax | grep "ocis server" | grep -v grep | \
   awk '{ print $1 }' | xargs kill -15
----

Stopping a particular ocis PID::
First identify which PID you want to terminate:
+
[source,bash]
----
ps ax | grep "ocis" | grep -v grep
----
+
This may give an output like the following:
+
[source,plaintext]
----
 221297 pts/1    Sl     0:04 ocis server
 221706 pts/0    Sl     0:00 ocis proxy
----
+
To terminate the `ocis proxy` service type the following command, where `sudo` may not be necessary depending on the permissions of the logged-in user. Replace the PID according the output from above:
+
[source,bash]
----
sudo kill -15 221706
----

== Setting up systemd for Infinite Scale

=== Create a Service User

In your operating system, create a user and group who will run the ocis service and own all the files of the Infinite Scale service but is not allowed to log in, has no shell and no home directory.

[source,bash]
----
sudo useradd --system --no-create-home --shell=/sbin/nologin ocis
----

* We strongly advise *against* using the user `root` for this purpose.
* Placing the environment file in `{ocis_env}` is only a suggestion, but a good one.
** The directory `ocis_env` must exist and the user `ocis` must be able to read it.
+
--
[source,bash,subs="attributes+"]
----
sudo mkdir -p {ocis_env}
----

[source,bash,subs="attributes+"]
----
sudo chown -R ocis:ocis {ocis_env}
----
--

Create the file `{ocis_env}/ocis.env` with the definitions of environment variables. See the following sections for information on additional environment variables: xref:deployment/general/general-info.adoc#configurations-to-access-the-webui[Configurations to Access the WebUI] and xref:deployment/general/general-info.adoc#base-data-directory[Base Data Directory].

NOTE: This is just an example with a minimal set of environment variables used.

[source,plaintext,subs="attributes+"]
----
OCIS_INSECURE=true
OCIS_URL=https://localhost:{ocis_port}
PROXY_HTTP_ADDR=0.0.0.0:{ocis_port}

OCIS_LOG_LEVEL=error
----

=== Setup systemd Service

include::partial$deployment/systemd.adoc[]

include::partial$deployment/dependent_startup.adoc[leveloffset=+2]
