== Roles & Permissions
:toc: right
:toclevels: 1

:description: Like ownCloud server, oCIS distinguishes between regular users and the admin user with extended configuration and administration priviledges. However, with the new spaces concept, regular users can have different roles with different permissions for individual spaces.

{description}

=== Available Roles and Permissions

==== Viewer

Users with the role `viewer` for a certain space can only read documents, view images, play videos, etc., but not change anything.

==== Editor

Editors of a space have additional permissions. They can:

* modify documents and even delete them,
* upload content to a space,
* edit the space name,
* edit the space description,
* add or change the image for the space,
* empty the trash bin of the space.

==== Manager

In addition to the viewer and editor permissions, the manager can:

* invite additional members,
* edit the quota of a space,
* change the roles of members, including those of other managers. A downgrade to viewer or editor is possible. 

The creator of a space becomes manager and can delegate this role to another member.

// Unclear if only Admin can create spaces or everyone.

=== Admin

The admin user is created during the setup of on oCIS instance. Check out the ownCloud Web section of the documention for details on all configuration options for admins.

With regard to spaces, roles and permissions, the admin user can create a new space and is then automatically assigned the manager role. After inviting more members to a space, the manager role can be delegated to another person. If an admin then downgrades his or her role to editor or viewer, this role can only be changes by the manager. The admin has no special priveledges with regard to spaces.

TIP: It's a good idea to have two users in the manager role, in case one of them can no longer take care of the space.

// Likely there will be a way for admins to change the roles, but we don't know yet for sure and how it will work.

=== How to Map Roles and Permissions to Users?

(integrated IDM, external IDM)
