= Backup Consistency

The backup consistency command allows inspecting the consistency of an Infinite Scale storage:

[source,bash]
----
ocis backup consistency -p /base/path/storage/users
----

This will check the consistency of the storage and output a list of inconsistencies. Inconsistencies can be:

* *Orphaned Blobs* +
A blob in the blobstore that is not referenced by any file metadata.
* *Missing Blobs* +
A blob referenced by file metadata that is not present in the blobstore.
* *Missing Nodes* +
A node that is referenced by a symlink but doesn't exist.
* *Missing Link* +
A node that is not referenced by any symlink but should be.
* *Missing Files* +
A node that is missing essential files (such as the `.mpk` metadata file).
* *Missing/Malformed Metadata* +
A node that doesn't have any (or malformed) metadata.

This command provides additional options:

* `-b` / `--blobstore` +
Allows specifying the blobstore to use. Defaults to `ocis`. Empty blobs will not be checked. Can also be switched to `s3ng`, but needs addtional envvar configuration (see the `storage-users` service for more details).

* `--fail` +
Exits with non-zero exit code if inconsistencies are found. Useful for automation.
