= Maintenance Commands
:toc: right
:description: There are commands availabe to maintain the Infinite Scale instance. This document gives an overview of the available commands and links to the related services where they are implemented for more details.

== Introduction

{description}

[NOTE]
====
* Calling a service in the examples is made via the single binary.
* Generic call: +
`ocis <service name> arguments options`.
* This changes if some services are available as executable on their own, then it would be: +
`<service name> arguments options`. +
This could happen if services are developed which are not shipped as part of the single binary.
====

== Manage Expired Uploads

Compared to unfinished uploads which are handled by the system, managing expired uploads can be a necessity as those files can pile up, blocking storage resources and need to be removed by command regularly. See the xref:{s-path}/storage-users.adoc#manage-unfinished-uploads[Manage Unfinished Uploads] section at the _Storage Users_ service for details.

== Purge Expired Space Trash-Bin Items

This command is about purging old trash-bin items of `project` spaces (spaces that have been created manually) and `personal` spaces. See the xref:{s-path}/storage-users.adoc##purge-expired-space-trash-bin-items[Purge Expired Space Trash-Bin Items] section at the _Storage Users_ service for details.

== Reindex a Space for Search

In rare circumstances, it can be necessary to initiate indexing manually for a given space or user. Though the search service handles exception cases automatically, it can happen that the search service was not able to complete indexing due to a dirty shut-down of the service or because of a bug. Re-indexing should *only* be run on explicit request and supervision by ownCloud support. See the xref:{s-path}/search.adoc#manually-trigger-re-indexing-a-space[Manually Trigger Re-Indexing a Space] section at the _Search_ service for details.

== Inspect and Manipulate Node Metadata

Infinite Scale provides a CLI command where you can inspect and manipulate node metadata.

WARNING: Use this command with absolute care. It is not intended to play around and should only be used on request of ownCloud support. 

[source,bash]
----
ocis decomposedfs metadata
NAME:
   ocis decomposedfs metadata - cli tools to inspect and manipulate node metadata

USAGE:
   ocis decomposedfs metadata command [command options] [arguments...]

COMMANDS:
   dump     print the metadata of the given node. String attributes will be enclosed in quotes. Binary attributes will be returned encoded as base64 with their value being prefixed with '0s'.
   get      print a specific attribute of the given node. String attributes will be enclosed in quotes. Binary attributes will be returned encoded as base64 with their value being prefixed with '0s'.
   set      manipulate metadata of the given node. Binary attributes can be given hex encoded (prefix by '0x') or base64 encoded (prefix by '0s').
   help, h  Shows a list of commands or help for one command

OPTIONS:
   --root value, -r value  Path to the decomposedfs
   --node value, -n value  Path to or ID of the node to inspect
   --help, -h              show help
----

== Resume Post-Processing

If post-processing fails in one step due to an unforseen error, current uploads will not be retried automatically. Starting with Infinite Scale release 3.1, a system administrator can instead run a xref:{s-path}/postprocessing.adoc#resume-post-processing[CLI command] to retry the failed upload.
