# note that this site.yml file is for local building and testing only
site:
  title: Infinite Scale Documentation
  url: https://doc.owncloud.com
  start_page: ocis::index.adoc

content:
  sources:
  - url: .
    branches:
    - HEAD

ui:
  output_dir: assets
  bundle:
    snapshot: true
    url: https://minio.owncloud.com/documentation/ui-bundle.zip

output:
  clean: true
  dir: public

asciidoc:
  attributes:
#   branch-specific-variables: 'see antora.yml'
#   build relevant
    # asciidoctor prefix for section IDs
    idprefix: ''
    idseparator: '-'
    # Antora User Interface Macros (btn, menu)
    experimental: true
    # Antora pagination (prev page, next page)
    page-pagination: true
#   common
    docs-base-url: 'https://doc.owncloud.com'
    oc-complete-base-url: 'https://download.owncloud.com/server/stable'
    oc-contact-url: 'https://owncloud.com/contact/'
    oc-help-url: 'https://owncloud.com/docs-guides/'
    oc-marketplace-url: 'https://marketplace.owncloud.com'
    oc-central-url: 'https://central.owncloud.org'
    oc-support-url: 'https://owncloud.com/support'
#   ocis
    latest-ocis-version: 'next@'   # do not change, soft set, correctly defined via antora.yml
    previous-ocis-version: 'next@' # do not change, soft set, correctly defined via antora.yml
    # These versions are just for printing like in docs-main release info, but not used in docs-ocis.
    # Versions in the ocis docs need to be defined in the branch specific docs-ocis/antora.yaml file.
    # To do so, change the values in docs-ocis/antora.yml like compose_tab_1_tab_text.
    ocis-actual-version: '5.0.4'
    ocis-former-version: '4.0.7'
    ocis-compiled: '2024-05-14 00:00:00 +0000 UTC'
    ocis-downloadpage-url: 'https://download.owncloud.com/ocis/ocis/stable/'
  extensions:
    - ./ext-asciidoc/tabs.js
    - ./ext-asciidoc/remote-include-processor.js
    - asciidoctor-kroki

antora:
  extensions:
    - ./ext-antora/generate-index.js
