# note that this site.yml file is for local building and testing only
site:
  title: Infinite Scale Documentation
  url: https://doc.owncloud.com
  start_page: ocis::index.adoc

content:
  sources:
  - url: .
    branches:
    - HEAD

ui:
  output_dir: assets
  bundle:
    snapshot: true
    url: https://minio.owncloud.com/documentation/ui-bundle.zip

output:
  clean: true
  dir: public

asciidoc:
  attributes:
#   branch-specific-variables: 'see antora.yml'
#   global attributes loaded via antora extension
#   ocis
    latest-ocis-version: 'next@'   # do not change, soft set, correctly defined via antora.yml
    previous-ocis-version: 'next@' # do not change, soft set, correctly defined via antora.yml
    # Versions mainly for printing like in docs-main release info.
    # Versions in the ocis docs need to be defined in the branch specific docs-ocis/antora.yaml file.
    # To do so, change the values in the branch of docs-ocis/antora.yml like service_xxx and compose_xxx.
    ocis-actual-version: '7.1.0'
    ocis-former-version: '7.0.0'
    # Needed in docs-ocis to define which rolling release to print like in the envvars table
    ocis-rolling-version: '6.6.1'
  extensions:
    - ./ext-asciidoc/tabs.js
    - ./ext-asciidoc/remote-include-processor.js
    - asciidoctor-kroki # integrated via npm

antora:
  extensions:
    - ./ext-antora/generate-index.js
    #- ./ext-antora/comp-version.js
    - require: ./ext-antora/load-global-site-attributes.js
      attributefile: https://raw.githubusercontent.com/owncloud/docs/refs/heads/master/global-attributes.yml
      #attributefile: ./global-attributes.yml
      enabled: true
    - require: ./ext-antora/find-orphaned-files.js
      #printavailable: true
      #excludeextension: ['.png', '.gif']
      #falsepositives: ./false-positives.txt
      #pathfilter: ['modules/owncloud_web', 'modules/classic_ui']
      #excludecomponents: ['webui']
      stopafterfind: true
      enabled: false
    # for testing only, prints attributes used
    # use only one or the other, output can be big
    #- ./ext-antora/attributes-used-in-site-yml.js
    #- ./ext-antora/attributes-used-in-antora-yml.js
