= Auth Machine Service Configuration
:toc: right
:description: The Infinite Scale Auth Machine service

:service_name: auth-machine

== Introduction

{description}

// fixme: source description is still missing, and a better description is needed

== Default Values

* Auth Machine listens on port 9166 by default.

include::partial$deployment/services/auth-service-family.adoc[]

== User Impersonation

When one ocis service is trying to talk to other ocis services, it needs to authenticate itself. To do so, it will impersonate a user using the `auth-machine` service. It will then act on behalf of this user. Any action will show up as action of this specific user, which gets visible when e.g. logged in the audit log.

== Deprecation

Note that with the upcoming xref:{s-path}/auth-service.adoc[auth-service] service, the `auth-machine` service will be used less frequently and is probably a candidate for deprecation.

== Configuration

include::partial$deployment/services/env-and-yaml.adoc[]
