= Auth App Service Configuration
:toc: right

:service_name: auth-app

:description: The Infinite Scale Auth App service provides authentication for 3rd party apps.

== Introduction

{description}

With the `auth-app` service, you can create tokens that can be used to authenticate 3rd party apps accessing Infinite Scale.

To enable `{service_name}`, you first must set `PROXY_ENABLE_APP_AUTH` to `true`.

== Default Values

* Auth Basic listens on port 9245 by default.

include::partial$deployment/services/auth-service-family.adoc[]

== Service Startup

* Because this service is not started automatically, a manual start needs to be initiated which can be done in several ways, only one example is shown below. For more details see the xref:deployment/general/general-info.adoc#start-infinite-scale[Start Infinite Scale] section.
* To configure the service usage, an environment variable for the proxy service needs to be set to allow app authentication.

[source,bash]
----
OCIS_ADD_RUN_SERVICES=auth-app  # deployment specific. Alternatively you can start the service explicitly via the command line.

PROXY_ENABLE_APP_AUTH=true      # mandatory, allow app authentication. In case of a distributed environment, this envvar needs to be set in the proxy service.
----

== App Tokens

App Tokens are used to authenticate 3rd party access via https like when using curl (apps) to access an API endpoint. These apps need to authenticate themselves, as no logged in user authenticates the request. To be able to use an app token, one must first create a token via the cli. Replace the `user-name` with an existing Infinite Scale user. For the `token-expiration`, you can use any time abbreviation from the following list: `h, m, s`. Examples: `72h` or `1h` or `1m` or `1s.` Default is `72h`.

[source,bash]
----
ocis auth-app create --user-name={user-name} --expiration={token-expiration}
----

Once generated, these tokens can be used to authenticate requests to ocis. They are passed as part of the request as `Basic Auth` header.

== Configuration

include::partial$deployment/services/env-and-yaml.adoc[tag=envvars-yaml]
