= Auth Service Configuration
:toc: right
:description: The Infinite Scale Auth Service is used to authenticate service accounts. Compared to normal accounts, service accounts are Infinite Scale internal only and not available to ordinary users like via LDAP.

:service_name: auth-service

== Introduction

{description}

== Default Values

* Auth Server listens on port 9198 by default.

include::partial$deployment/services/auth-service-family.adoc[]

== Service Accounts

Service accounts are user accounts that are only used for inter-service communication. These users have no personal space, do not show up in user lists and cannot login via the UI. Service accounts can be configured in the settings service. Only the `admin` service user is available for now. In addition to the actions it can do via its role, all service users can stat all files on all spaces.

== Configuring Service Accounts

By using the envvars `OCIS_SERVICE_ACCOUNT_ID` and `OCIS_SERVICE_ACCOUNT_SECRET`, one can configure the ID and the secret of the service user. The secret can be rotated regulary to increase security. For activating a new secret, all services where the envvars are used need to be restarted. The secret is always and only stored in memory and never written into any persistant store. Though you can use any string for the service account, it is recommmended to use a UUIDv4 string.

== Configuration

include::partial$deployment/services/env-and-yaml.adoc[]
