= Collaboration
:toc: right
:description: The collaboration service connects Infinite Scale with document servers such as Collabora and ONLYOFFICE using the WOPI protocol.

:service_name: collaboration

== Introduction

{description}

IMPORTANT: Since this service requires an external document server, it won't start by default when using `ocis server` (xref:deployment/general/general-info.adoc#infinite-scale-supervised-services[supervised mode]). You must start it therefore manually with the `ocis collaboration server` command.

== Default Values

* The collaboration service listens on port 9300 by default.

== Requirements

The collaboration service requires the target document server (ONLYOFFICE, Collabora, etc.) to be up and running. Additionally, some Infinite Scale services are also required to be running in order to register the GRPC service for the `open in app` action in the webUI. The following internal end external services need to be available:

* External document server
* xref:{s-path}/gateway.adoc[gateway] service.
* xref:{s-path}/app-provider.adoc[app provider] service.

If any of the named services above have not been started or are not reachable, the collaboration service won't start. For the binary or the docker release of Infinite Scale, check with the xref:deployment/general/general-info.adoc#infinite-scale-supervised-services[List running services] command if they have been started. If not, you must start them manually upfront starting the collaboration service.

== WOPI Configuration

There are a few variables that you need to set:

* `COLLABORATION_WOPIAPP_ADDR`: +
The URL of the WOPI app (onlyoffice, collabora, etc). +
For example: `\https://office.example.com`.

* `COLLABORATION_HTTP_ADDR`: +
The external address of the collaboration service. The target app (onlyoffice, collabora, etc) will use this address to read and write files from Infinite Scale. +
For example: `\https://wopiserver.example.com`.

* `COLLABORATION_HTTP_SCHEME`: +
The scheme to be used when accessing the collaboration service. Either `http` or `https`. This will be used to finally build the URL that the WOPI app needs in order to contact the collaboration service.

The rest of the configuration options available can be left with the default values.

== Configuration

include::partial$deployment/services/env-and-yaml.adoc[]
