= Frontend Service Configuration
:toc: right
:toclevels: 4
:description: The frontend service translates various ownCloud-related HTTP APIs to CS3 requests.

:service_name: frontend

== Introduction

{description}

== Default Values

* Frontend listens on port 9140 by default.

== Endpoints Overview

Currently, the frontend service handles requests for three functionalities, which are

* xref:appprovider[appprovider], 
* xref:archiver[archiver], 
* xref:datagateway[datagateway] and 
* xref:ocs[ocs].

=== appprovider

The appprovider endpoint, by default `/app`, forwards HTTP requests to the CS3 https://cs3org.github.io/cs3apis/#cs3.app.registry.v1beta1.RegistryAPI[App Registry API].

=== archiver

The archiver endpoint, by default `/archiver`, implements zip and tar download for collections of files. It will internally use the CS3 API to initiate downloads and then stream the individual files as part of a compressed file.

=== datagateway

The datagateway endpoint, by default `/data`, forwards file up- and download requests to the correct CS3 data provider. OCIS starts a dataprovider as part of the storage-* services. The routing happens based on the JWT that was created by a storage provider in response to an `InitiateFileDownload` or `InitiateFileUpload` request.

=== ocs

The ocs endpoint, by default `/ocs`, implements the ownCloud 10 Open Collaboration Services API by translating it into CS3 API requests. It can handle users, groups, capabilities and also implements the file sharing functionality on top of CS3. The `/ocs/v[12].php/cloud/user/signing-key` is currently handled by the dedicated xref:{s-path}/ocs.adoc[ocs] service.

With the upcoming Infinite Scale release after 4.0.1, an ocs event handler and a new functionality for auto-accepting shares will be added, see the sections below.  

==== Event Handler

The `frontend` service contains an eventhandler for handling `ocs` related events. As of now, it only listens to the `ShareCreated` event.

== Caching

The `frontend` service can use a configured store via `FRONTEND_OCS_STAT_CACHE_STORE`. Possible stores are:

include::partial$multi-location/caching-list.adoc[]
// you must not have one or more blank lines here as it breaks continuous numbering!
. When using `redis-sentinel`, the Redis master to use is configured via `FRONTEND_OCS_STAT_CACHE_STORE_NODES` in the form of `<sentinel-host>:<sentinel-port>/<redis-master>` like `10.10.0.200:26379/mymaster`.

== Configuration

include::partial$deployment/services/env-and-yaml.adoc[]
