= Graph Service Configuration
:toc: right
:description: The graph service provides the Graph API which is a RESTful web API used to access Infinite Scale resources.

:service_name: graph

include::partial$multi-location/compose-version.adoc[]

== Introduction

{description} It is inspired by the https://learn.microsoft.com/en-us/graph/use-the-api[Microsoft Graph API,window=_blank] and can be used by clients or other services or extensions. Visit the https://owncloud.dev/libre-graph-api/[Libre Graph API,window=_blank] for a detailed specification of the API implemented by the graph service.

== Default Values

* Graph listens on port 9120 by default.

== Restrict Username Patterns

Usernames can be restricted to follow certain patterns. Such patterns can be neccessary when using the xref:{s-path}/idm.adoc[internal IDM,window=_blank] for example to align with local Unix username restrictions. Username restrictions can also be handled with an external IDM like Keycloak. The environment variable `GRAPH_USERNAME_MATCH` can be set to the following values to define where and how these restriction are handled:

* `none` +
There is no internal username checking. Restrictions, if any, are defined in the _external_ IDM like Keycloak.

* `default` +
Usernames are restricted by the following criteria:
** ASCII standard charset, no UTF-8
** The username _must_ start with either
*** an `_` (underscore) or
*** a letter where there is no distinction between lower- and uppercase.
** More characters from the ASCII charset including numbers, aligning to the Unix user namespace. 
** optionally an `@` character followed by a domain name 

== Manual Filters

Using the API, you can manually filter like for users. See the https://owncloud.dev/libre-graph-api/#/users/ListUsers[Libre Graph API,window=_blank] for examples in the https://owncloud.dev[developer documentation,window=_blank]. Note that you can use `and` and `or` to refine results.

== Sequence Diagram

The following image gives an overview of the scenario when a client requests to list available spaces the user has access to. To do so, the client is directed with his request automatically via the proxy service to the graph service.

// referencing: https://github.com/owncloud/ocis/pull/3816 ([docs-only] add client protocol overview)

image::deployment/services/graph/mermaid-graph.svg[width=600]

== Users and Groups API

The graph service provides endpoints for querying users and groups. It features two different backend implementations:

* *ldap*: +
This is currently the default backend. It queries user and group information from an LDAP server. Depending on the configuration, it can also be used to manage (create, update, delete) users and groups provided by an LDAP server.

* *cs3*: +
This backend queries users and groups using the CS3 identity APIs as implemented by the `users` and `groups` service. This backend is currently still experimental and only implements a subset of the Libre Graph API. It should not be used in production.

=== LDAP Configuration

The LDAP backend is configured using a set of environment variables. A detailed list of all the available configuration options can be found in the xref:configuration[configuration section] below. The LDAP related options are prefixed with `OCIS_LDAP_` (or `GRAPH_LDAP_` for settings specific to the graph service).

==== Read-Only Access to Existing LDAP Servers

To connect the graph service to an existing LDAP server, set `OCIS_LDAP_SERVER_WRITE_ENABLED` to `false` to prevent the graph service from sending write operations to the LDAP server. Also set the various `OCIS_LDAP_*` environment variables to match the configuration of the LDAP server you are connecting to. An example configuration for connecting Infinite Scale to an instance of Microsoft Active Directory is available https://owncloud.dev/ocis/identity-provider/ldap-active-directory/[here,window=_blank].

==== Using a Write Enabled LDAP Server

To use the graph service for managing (create, update, delete) users and groups, a write enabled LDAP server is required. In the default configuration, the graph service will use the simple LDAP server that is bundled with infinite Scale in the xref:{s-path}/idm.adoc[idm] service which provides all the required features. It is also possible to setup up an external LDAP server with write access for use with Infinite Scale. It is recommended to use OpenLDAP for this. The LDAP server needs to fulfill a couple of requirements with respect to the available schema:

* The LDAP server must provide the `inetOrgPerson` object class for users and the `groupOfNames` object class for groups.

* The graph service maintains a few additional attributes for users and groups that are not available in the standard LDAP schema. A schema file (ldif), ready to use with OpenLDAP defining those additional attributes, is available: {compose_url}v{compose_version}{compose_final_path}/ocis_ldap/config/ldap/schemas/[here,window=_blank].

== Query Filters Provided by the Graph API

Some API endpoints provided by the graph service allow query filters to be specified. The filter syntax is based on the https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter[OData Specification,window=_blank]. See the https://owncloud.dev/libre-graph-api/#/users/ListUsers[Libre Graph API,window=_blank] for examples on the filters supported when querying users.

== Keycloak Configuration for the Personal Data Export

If Keycloak is used for authentication, GDPR regulations require to add all personal identifiable information that Keycloak has about the user to the personal data export. To do this, the following environment variables must be set:

[width=100%,cols="15%,85%",options=header]
|===
| Environment Variable
| Description

| `OCIS_KEYCLOAK_BASE_PATH`
| The URL to the Keycloak instance.

| `OCIS_KEYCLOAK_CLIENT_ID`
| The client ID of the client that is used to authenticate with Keycloak. This client has to be able to list users and get the credential data. 

| `OCIS_KEYCLOAK_CLIENT_SECRET`
| The client secret of the client that is used to authenticate with Keycloak.

| `OCIS_KEYCLOAK_CLIENT_REALM`
| The realm the client is defined in.

| `OCIS_KEYCLOAK_USER_REALM`
| The realm Infinite Scale users are defined in.

| `OCIS_KEYCLOAK_INSECURE_SKIP_VERIFY`
| If set to true, the TLS certificate of the Keycloak instance is not verified.
|===

=== Keycloak Client Configuration

The client that is used to authenticate with Keycloak has to be able to list users and get the credential data. To do this, the following  roles have to be assigned to the client and they have to be about the realm that contains the Infinite Scale users:

*   `view-users`
*   `view-identity-providers`
*   `view-realm`
*   `view-clients`
*   `view-events`
*   `view-authorization`

Note that these roles are only available to assign if the client is in the `master` realm.


:envvar_name: GRAPH_TRANSLATION_PATH
include::partial$deployment/services/translations.adoc[]

== Caching

// renders dependent on is_cache or is_stat
:is_cache: true

include::partial$multi-location/caching-list.adoc[]

== Event Bus Configuration

include::partial$multi-location/event-bus.adoc[]

== Configuration

include::partial$deployment/services/env-and-yaml.adoc[tag=envvars-yaml]
