= Graph Service Configuration
:toc: right
:description: The Infinite Scale Graph service provides a simple graph world API which can be used by clients or other services or extensions.

:ext_name: graph

== Introduction

{description}

// fixme: source description is still missing, and a better description is needed

== Default Values

* Graph listens on port 9120 by default.

== Manual Filters

Using the API, you can manually filter like for users. See the https://owncloud.dev/libre-graph-api/#/users/ListUsers[Libre Graph API] for examples in the https://owncloud.dev[developer documentation]. Note that you can use `and` and `or` to refine results.

== Sequence Diagram

The following image gives an overview of the scenario when a client requests to list available spaces the user has access to. To do so, the client is directed with his request automatically via the proxy service to the graph service.

// referencing: https://github.com/owncloud/ocis/pull/3816 ([docs-only] add client protocol overview)

image::deployment/services/graph/mermaid-graph.svg[width=600]

== Caching

The `graph` service can use a configured store via `GRAPH_STORE_TYPE`. Possible stores are:

[width=100%,cols="15%,85%",options=header]
|===
| Store Type
| Description

| `memory`
| Basic in-memory store and the default.

| `ocmem`
| Advanced in-memory store allowing max size.

| `Redis`
| Stores data in a configured Redis cluster.

| `redis-sentinel`
| Stores data in a configured redis sentinel cluster.

| `etcd`
| Stores data in a configured etcd cluster.

| `nats-js`
| Stores data using the key-value-store feature of https://docs.nats.io/nats-concepts/jetstream/key-value-store[NATS JetStream].

| `noop`
| Stores nothing. Useful for testing. Not recommended in productive environments.
|===

1. Note that in-memory stores are by nature not reboot persistent.
2. Though usually not necessary, a database name and a database table can be configured for event stores if the event store supports this. Generally, this does not apply to stores of type `in-memory`. These settings are blank by default which means that the standard settings of the configured store applies.
3. The `graph` service can be scaled if it's not using `in-memory` stores and the stores are configured identically over all instances.
4.  When using `redis-sentinel`, the Redis master to use is configured via `GRAPH_CACHE_STORE_NODES` in the form of `<sentinel-host>:<sentinel-port>/<redis-master>` like `10.10.0.200:26379/mymaster`.

== Configuration

include::partial$deployment/services/env-and-yaml.adoc[]
