= Graph Service Configuration
:toc: right
:description: The Infinite Scale Graph service provides a simple graph world API which can be used by clients or other services or extensions.

:service_name: graph

== Introduction

{description}

// fixme: source description is still missing, and a better description is needed

== Default Values

* Graph listens on port 9120 by default.

== Restrict Username Patterns

Usernames can be restricted to follow certain patterns. Such patterns can be neccessary when using the xref:{s-path}/idm.adoc[internal IDM] for example to align with local Unix username restrictions. Username restrictions can also be handled with an external IDM like Keycloak. The environment variable `GRAPH_USERNAME_MATCH` can be set to the following values to define where and how these restriction are handled:

* `none` +
There is no internal username checking. Restrictions, if any, are defined in the _external_ IDM like Keycloak.

* `default` +
Usernames are restricted by the following criteria:
** ASCII standard charset, no UTF-8
** The username _must_ start with either
*** an `_` (underscore) or
*** a letter where there is no distinction between lower- and uppercase.
** More characters from the ASCII charset including numbers, aligning to the Unix user namespace. 
** optionally an `@` character followed by a domain name 

== Manual Filters

Using the API, you can manually filter like for users. See the https://owncloud.dev/libre-graph-api/#/users/ListUsers[Libre Graph API] for examples in the https://owncloud.dev[developer documentation]. Note that you can use `and` and `or` to refine results.

== Sequence Diagram

The following image gives an overview of the scenario when a client requests to list available spaces the user has access to. To do so, the client is directed with his request automatically via the proxy service to the graph service.

// referencing: https://github.com/owncloud/ocis/pull/3816 ([docs-only] add client protocol overview)

image::deployment/services/graph/mermaid-graph.svg[width=600]

== Caching

// renders dependent on is_cache or is_stat
:is_cache: true

include::partial$multi-location/caching-list.adoc[]

== Keycloak Configuration for the Personal Data Export

If Keycloak is used for authentication, GDPR regulations require to add all personal identifiable information that Keycloak has about the user to the personal data export. To do this, the following environment variables must be set:

[width=100%,cols="15%,85%",options=header]
|===
| Environment Variable
| Description

| `OCIS_KEYCLOAK_BASE_PATH`
| The URL to the Keycloak instance.

| `OCIS_KEYCLOAK_CLIENT_ID`
| The client ID of the client that is used to authenticate with Keycloak. This client has to be able to list users and get the credential data. 

| `OCIS_KEYCLOAK_CLIENT_SECRET`
| The client secret of the client that is used to authenticate with Keycloak.

| `OCIS_KEYCLOAK_CLIENT_REALM`
| The realm the client is defined in.

| `OCIS_KEYCLOAK_USER_REALM`
| The realm Infinite Scale users are defined in.

| `OCIS_KEYCLOAK_INSECURE_SKIP_VERIFY`
| If set to true, the TLS certificate of the Keycloak instance is not verified.
|===

=== Keycloak Client Configuration

The client that is used to authenticate with Keycloak has to be able to list users and get the credential data. To do this, the following  roles have to be assigned to the client and they have to be about the realm that contains the Infinite Scale users:

*   `view-users`
*   `view-identity-providers`
*   `view-realm`
*   `view-clients`
*   `view-events`
*   `view-authorization`

Note that these roles are only available to assign if the client is in the `master` realm.

== Event Bus Configuration

include::partial$multi-location/event-bus.adoc[]

== Configuration

include::partial$deployment/services/env-and-yaml.adoc[]
