= IDP Service Configuration
:toc: right
:description: The Infinite Scale IDP service provides a built-in minimal OpenID Connect provider.

:service_name: idp

== Introduction

{description}

The IDP service is mainly suitable for smaller installations. The recommendation for larger setups is to replace IDP with and external OpenID Connect Provider. See the xref:deployment/container/orchestration/orchestration.adoc#docker-compose-examples[Docker Compose Examples] (ocis_keycloak) for more details.

By default, the IDP service is configured to use the Infinite Scale xref:{s-path}/idm.adoc[IDM service] as its LDAP backend for looking up and authenticating users. Other backends like an external LDAP server can be configured via a set of environment variables. For details see below.

IMPORTANT: To use the embedded IDP service, it must be accessed with https. Accessing it with http is not possible and generates an error that is logged.

== Default Values

* IDP listens on port 9130 by default.

== Configuration

include::partial$deployment/services/env-and-yaml.adoc[]
