= OCDAV Service Configuration
:toc: right

:ext_name: ocdav

:description: The ocDAV service is responsible for translating ownCloud flavoured WebDAV into CS3 API calls. Note that previews (thumbnails) are provided by the xref:deployment/services/webdav.adoc[WebDAV service].

// references https://github.com/owncloud/ocis/pull/3864 ([docs-only] add PROPFIND sequence diagram examples)
// also see: https://owncloud.dev/architecture/protocol-changes/ 

== Introduction

{description} For more details on CS3 see the xref:architecture/architecture.adoc#reva-and-cs3[REVA and CS3] description in the Architecture and Concepts section.

== Sequence Diagram

// https://github.com/owncloud/ocis/pull/3864
// https://owncloud.dev/architecture/protocol-changes/
 
=== General View

A PROPFIND finds its way to a storage provider like in the image shown below. While this is a simplification to get an understanding of what needs to go where, there are several places where sharding (splitting and distributing) can happen.

image::deployment/services/ocdav/mermaid-ocdav-1.svg[width=600]

=== Proxy-based User Routing

The Infinite Scale proxy authenticates requests and can forward requests to different backends, depending on the logged-in user or cookies. For example, multiple `ocdav` services can be configured to shard users, based on username or affiliation.

image::deployment/services/ocdav/mermaid-ocdav-2.svg[width=600]

=== Gateway-based Path or Storage Provider ID-based Routing

The CS3 gateway acts as a facade to multiple storage providers that can be configured with the storage registry.

image::deployment/services/ocdav/mermaid-ocdav-3.svg[width=600]

=== PROPFIND Request Against Old Webdav Endpoints

This is how the old endpoint with username and a path relative to the user's home looks like: `/dav/files/\{username}`

To route a PROPFIND request against the old webdav endpoints like `/dav/files/username`, ocdav first has to build a CS3 namespace prefix, e.g. `/users/{{.Id.OpaqueId}}` to the user's home.

image::deployment/services/ocdav/mermaid-ocdav-4.svg[width=600]

=== Handling Legacy Global Namespace Webdav Endpoints

The reason Infinite Scale uses a path-based lookup instead of looking up the current user's home using the user ID and a space type filter is, because there are deployments that use a global namespace at the legacy `/webdav` endpoint. To support these use cases, the gateway allows looking up spaces using their mount path.

image::deployment/services/ocdav/mermaid-ocdav-5.svg[width=600]

== Configuration

include::partial$deployment/services/env-and-yaml.adoc[]
