= OCM Configuration
:toc: right
:description: The Infinite Scale OCM service provides federated sharing functionality based on the ScienceMesh and OCM HTTP APIs.

:service_name: ocm

== Introduction

{description}

Overview:

* https://sciencemesh.io[ScienceMesh] is the Federated Science Cloud Mesh that connects existing and heterogeneous sites in a transparent way. It provides a managed white list of trusted federated sites.
* The https://github.com/cs3org/OCM-API[Open Cloud Mesh Protocol] provides the disovery and use of the RESTful API endpoints, request and response headers, possible response codes, request and response formats, hypermedia controls, error handling etc. Using this protocol, consumers do not need to accept a share, the shared resource will be available to them immediately.

Both API's have their roots in CERN where providing resources to trusted partners in an easy way is a key for their daily scientific work.

== Default Values

* OCM listens on port 9280 by default.

== Trust Between Instances

IMPORTANT: For security reasons and data protection, invitations are limited to trusted instances only. These have to be defined by the administrator _before_ setting up any federation.

The OCM service implements an invitation workflow for _trusted_ instances when creating federated shares.

The list of trusted instances is managed by the `ocmproviderauthorizer` service. The only supported backend currently is `json` which stores the list in a json file on disk. Note that the `ocmproviders.json` file, which holds that configuration, is expected to be located in the root of the ocis config directory if not otherwise defined. See the `OCM_OCM_PROVIDER_AUTHORIZER_PROVIDERS_FILE` environment variable for more details.

Example for a `ocmproviders.json` file:

[source,json]
----
[
    {
        "name": "Example",
        "full_name": "Example provider",
        "organization": "ownCloud",
        "domain": "example.com",
        "homepage": "https://example.com",
        "services": [
            {
                "endpoint": {
                    "type": {
                        "name": "OCM",
                        "description": "example.com Open Cloud Mesh API"
                    },
                    "name": "example.com - OCM API",
                    "path": "https://example.com/ocm/",
                    "is_monitored": true
                },
                "api_version": "0.0.1",
                "host": "example.com:port"
            }
        ]
    }
]
----

Note that there is no limit to adding multiple trusted providers.

== Invitation Workflow

Before sharing a resource with a remote user, this user has to be invited by the sharer.

In order to do so, a request is sent to the ScienceMesh API. The generated token is passed on to the receiver, who will then accept the invitation. As a result, remote users will be added on both sides.

The data backend for the workflow, not the data itself, is configurable. The only supported backend is currently `json` which stores the data in a json file on disk.

== Creating Shares

OCM Shares are currently created using the xref:{s-path}/ocs.adoc[OCS] API, just like regular shares.

The data backend for the workflow, not the data itself, is configurable. The only currently supported backend is `json` which stores the data in a json file on disk.

== Configuration

include::partial$deployment/services/env-and-yaml.adoc[tag=envvars-yaml]
