= OCM Configuration
:toc: right
:ocm-api-version: 1.1.0 
:description: The Infinite Scale OCM service provides federated sharing functionality based on ScienceMesh and the OCM {ocm-api-version} HTTP API.

:site-object-url: https://developer.sciencemesh.io/docs/technical-documentation/central-database/#site-object
:service_name: ocm

== Introduction

{description}

Overview:

include::partial$/multi-location/ocm-sciencemesh.adoc[]

See the xref:depl-examples/federation/sciencemesh.adoc[Setting Up Federations Using ScienceMesh] for details on how to set up sharing between users via a federation using OCM, the configuration of which is described here.

== Default Values

* OCM listens on port 9280 by default.

== Enable OCM

To enable OpenCloudMesh, you have to set the following environment variable.

[source,bash]
----
OCIS_ENABLE_OCM=true
----

== Trust Between Instances

IMPORTANT: For security, privacy, and data protection reasons, federation invitations are restricted to trusted instances. These must be defined by the administrator _before_ users create a federation.

The OCM service implements an invitation workflow for _trusted_ instances when creating federated shares.

The list of trusted providers for an instance is defined by a json file. Note that this `ocmproviders.json` file, which contains this configuration, is expected to be in the root of the Infinite Scale _config_ directory, unless otherwise specified. See the `OCM_OCM_PROVIDER_AUTHORIZER_PROVIDERS_FILE` environment variable for more details.

If you want all instances of a federation to trust each other, you can use an `ocmproviders.json` file like this for all instances. The following sample federation consists of two instances: `cloud.owncloud.test` and `cloud.ocis.test`, which can use the xref:invitation-workflow[Invitation Workflow] described below to create, send, and accept invitations.

[source,json,subs="attributes+"]
----
[
    {
        "name": "oCIS Test",
        "full_name": "oCIS Test provider",
        "organization": "oCIS",
        "domain": "cloud.ocis.test",
        "homepage": "https://ocis.test",
        "description": "oCIS Example cloud storage",
        "services": [
            {
                "endpoint": {
                    "type": {
                        "name": "OCM",
                        "description": "cloud.ocis.test Open Cloud Mesh API"
                    },
                    "name": "cloud.ocis.test - OCM API",
                    "path": "https://cloud.ocis.test/ocm/",
                    "is_monitored": true
                },
                "api_version": "{ocm-api-version}",
                "host": "http://cloud.ocis.test"
            },
            {
                "endpoint": {
                    "type": {
                        "name": "Webdav",
                        "description": "cloud.ocis.test Webdav API"
                    },
                    "name": "cloud.ocis.test Example - Webdav API",
                    "path": "https://cloud.ocis.test/dav/",
                    "is_monitored": true
                },
                "api_version": "{ocm-api-version}",
                "host": "https://cloud.ocis.test/"
            }
        ]
    },
    {
        "name": "ownCloud Test",
        "full_name": "ownCloud Test provider",
        "organization": "ownCloud",
        "domain": "cloud.owncloud.test",
        "homepage": "https://owncloud.test",
        "description": "ownCloud Example cloud storage",
        "services": [
            {
                "endpoint": {
                    "type": {
                        "name": "OCM",
                        "description": "cloud.owncloud.test Open Cloud Mesh API"
                    },
                    "name": "cloud.owncloud.test - OCM API",
                    "path": "https://cloud.owncloud.test/ocm/",
                    "is_monitored": true
                },
                "api_version": "{ocm-api-version}",
                "host": "http://cloud.owncloud.test"
            },
            {
                "endpoint": {
                    "type": {
                        "name": "Webdav",
                        "description": "cloud.owncloud.test Webdav API"
                    },
                    "name": "cloud.owncloud.test Example - Webdav API",
                    "path": "https://cloud.owncloud.test/dav/",
                    "is_monitored": true
                },
                "api_version": "{ocm-api-version}",
                "host": "https://cloud.owncloud.test/"
            }
        ]
    }
]
----

NOTE: The `domain` *must not* contain the protocol as it must match the {site-object-url}[GOCDB site object domain].

== Invitation Workflow

After the federation is set up, but before a resource can be shared between remote users, a user must be invited by the sharer. See xref:depl-examples/federation/sciencemesh.adoc[Setting up Federations Using ScienceMesh] for more details.

Internally, a request is sent to the ScienceMesh API. The generated token is passed to the recipient who then accepts the invitation. As a result, remote users are added on both sides and the data for this grant is stored in a file defined by the `OCM_OCM_INVITE_MANAGER_JSON_FILE` environment variable.

== Configuration

include::partial$deployment/services/env-and-yaml.adoc[tag=envvars-yaml]
