= Proxy Service Configuration
:toc: right
:description: The proxy service is an API-Gateway for the ownCloud Infinite Scale microservices.

:service_name: proxy

== Introduction

{description} Every HTTP request goes through this service. Authentication, logging and other preprocessing of requests also happens here. Mechanisms like request rate limiting or intrusion prevention are **not** included in the proxy service and must be set up in front like with an external reverse proxy.

See the https://owncloud.dev/services/proxy/[Developer Documentation] for details if you want to write your own extensions and need to change or add routes to endpoints.

== Default Values

* The proxy listens on port 9200 by default.

== Authentication

The following request authentication schemes are implemented:

-   Basic Auth (Only use in development, **never in production** setups!)
-   OpenID Connect
-   Signed URL
-   Public Share Token

== Automatic Quota Assignments

It is possible to automatically assign a specific quota to new users depending on their role. To do this, you need to configure a mapping between roles defined by their ID and the quota in bytes. The assignment can only be done via a `yaml` configuration and not via environment variables. See the following `proxy.yaml` config snippet for a configuration example.

[source,yaml]
----
role_quotas:
    <role ID1>: <quota1>
    <role ID2>: <quota2>
----

## Automatic Role Assignments

When users log in, they automatically get a role assigned. The automatic role assignment can be
configured in different ways. The `PROXY_ROLE_ASSIGNMENT_DRIVER` environment variable (or the `driver`
setting in the `role_assignment` section of the configuration file) selects which mechanism to use for
the automatic role assignment.

* When `PROXY_ROLE_ASSIGNMENT_DRIVER` is set to `default`, all users that do not have a role assigned at the time of their first login will get the role 'user' assigned. (This is also the default behavior if `PROXY_ROLE_ASSIGNMENT_DRIVER` is unset.

* When `PROXY_ROLE_ASSIGNMENT_DRIVER` is set to `oidc`, the role assignment for a user will happen based on the values of an OpenID Connect Claim of that user. The name of the OpenID Connect Claim to be used for the role assignment can be configured via the `PROXY_ROLE_ASSIGNMENT_OIDC_CLAIM` environment variable. It is also possible to define a mapping of claim values to role names defined in ownCloud Infinite Scale via a `yaml` configuration. See the following `proxy.yaml` snippet for an example.
+
--
[source,yaml]
----
role_assignment:
    driver: oidc
    oidc_role_mapper:
        role_claim: ocisRoles
        role_mapping:
            - role_name: admin
              claim_value: myAdminRole
            - role_name: spaceadmin
              claim_value: mySpaceAdminRole
            - role_name: user
              claim_value: myUserRole
            - role_name: guest
              claim_value: myGuestRole
----

This would assign the role `admin` to users with the value `myAdminRole` in the claim `ocisRoles`.
The role `user` to users with the values `myUserRole` in the claim `ocisRoles` and so on.

Claim values that are not mapped to a specific Infinite Scale role will be ignored.

[NOTE]
====
An Infinite Scale user can only have a single role assigned. If the configured
`role_mapping` and a user's claim values result in multiple possible roles for a user, the order in
which the role mappings are defined in the configuration is important. The first role in the
`role_mappings` where the `claim_value` matches a value from the user's roles claim will be assigned
to the user. So if e.g. a user's `ocisRoles` claim has the values `myUserRole` and
`mySpaceAdminRole` that user will get the ocis role `spaceadmin` assigned (because `spaceadmin`
appears before `user` in the above sample configuration).

If a user's claim values don't match any of the configured role mappings, an error will be logged and
the user will not be able to log in.
====

The default `role_claim` (or `PROXY_ROLE_ASSIGNMENT_OIDC_CLAIM`) is `roles`. The default `role_mapping` is:

[source,yaml]
----
- role_name: admin
  claim_value: ocisAdmin
- role_name: spaceadmin
  claim_value: ocisSpaceAdmin
- role_name: user
  claim_value: ocisUser
- role_name: guest
  claim_value: ocisGuest
----
--

== Recommendations for Production Deployments

* The proxy service is the only service communicating to the outside and therefore needs the usual protection against DDOS, Slow Loris or other attack vectors. All other services are not exposed to the outside, but also need protective measures when it comes to distributed setups like when using container orchestration over various physical servers.

* In a production deployment, you want to have basic authentication (`PROXY_ENABLE_BASIC_AUTH`) _disabled_ which is the default state. You should also set up a firewall to only allow requests to the proxy service or the reverse proxy if you have one. Requests to the other services should be blocked by the firewall.

== Caching

Important, also see section xref:presigned-urls[Presigned Urls] below.

:is_cache: true

include::partial$multi-location/caching-list.adoc[]

== Presigned Urls

Important, also see section xref:caching[caching] above.

To authenticate presigned URLs, the `proxy` service needs to read the signing keys from a store that is populated by the xref:deployment/services/s-list/ocs.adoc[ocs] service.

The following stores can be configured via the `OCS_PRESIGNEDURL_SIGNING_KEYS_STORE` environment variable:

* `nats-js-kv` +
Stores data using key-value-store feature of https://docs.nats.io/nats-concepts/jetstream/key-value-store[nats jetstream].

* `redis-sentinel` +
Stores data in a configured Redis Sentinel cluster.

* `ocisstoreservice` +
Stores data in the _deprecated_ Infinite Scale xref:deployment/services/s-list/store.adoc[store] service. +
Requires setting `OCS_PRESIGNEDURL_SIGNING_KEYS_STORE_NODES` to `com.owncloud.api.store`.

[NOTE]
====
* The `memory` or `ocmem` stores cannot be used as they do not share the memory from the ocs service signing key memory store, even in a single process.

* Make sure to configure the same store in the proxy service.
====

Store specific notes:

* When using `redis-sentinel` +
The Redis master to use is configured via e.g. `OCS_PRESIGNEDURL_SIGNING_KEYS_STORE_NODES` in the form of `<sentinel-host>:<sentinel-port>/<redis-master>` like `10.10.0.200:26379/mymaster`.

* When using `nats-js-kv` +
It is recommended to set `PROXY_PRESIGNEDURL_SIGNING_KEYS_STORE_NODES` to the same value as `OCS_PRESIGNEDURL_SIGNING_KEYS_STORE_NODES`. That way the `proxy` service uses the same nats instance as the xref:deployment/services/s-list/ocs.adoc[ocs] service.

* When using `ocisstoreservice` +
The `OCS_PRESIGNEDURL_SIGNING_KEYS_STORE_NODES` must be set to the service name `com.owncloud.api.store`. It does not support TTL and stores the presigning keys indefinitely. Also, the xref:deployment/services/s-list/store.adoc[store] service needs to be started.

== Special Settings

When using the Infinite Scale xref:{s-path}/idp.adoc[IDP service] instead of an external IDP:

-   Use the environment variable xref:deployment/services/env-vars-special-scope.adoc#global-environment-variables[OCIS_URL] to define how Infinite Scale can be accessed; *mandatory* is the use of `https` as protocol for the URL.
-   If no reverse proxy is set up, the `PROXY_TLS` environment variable *must* be set to `true` because the embedded `libreConnect` shipped with the IDP service has a hard check if the connection is on TLS and uses the HTTPS protocol. If this mismatches, an error will be logged and no connection from the client can be established.
-   `PROXY_TLS` *can* be set to `false` if a reverse proxy is used and the https connection is terminated at the reverse proxy. When setting to `false`, the communication between the reverse proxy and Infinite Scale is not secured. If set to `true`, you must provide certificates.

== Metrics

For details on monitoring see the xref:monitoring/prometheus.adoc[Metrics for Prometheus] documentation.

== Configuration

include::partial$deployment/services/env-and-yaml.adoc[]
