= Settings Service Configuration
:toc: right
:description: The Infinite Scale Settings service provides functionality for other services to register new settings as well as storing and retrieving the respective settings' values.

:service_name: settings

== Introduction

{description}

== Default Values

* Settings listens on port 9190 by default.

== Settings Managed

The settings service is currently used for managing the:

* users' `profile` settings like the language and the email notification settings,
* possible user roles and their respective permissions,
* assignment of roles to users.

As an example, user profile settings that can be changed in the Web UI must be persistent.  

The settings service supports two different backends for persisting the data. The backend can be set via the `SETTINGS_STORE_TYPE` environment variable. Supported values are:

* `metadata`: The default. This backend persists the settings data via the `storage-system` service.
* `filesystem`: This backend persists the settings data in a directory on the local filesystem.
  The directory can be configured with `SETTINGS_DATA_PATH`. This backend is **not** suitable for running
  multiple intances of the `settings` service in a scale-out deployment and should be therefore considered
  deprecated.

== Settings Management

Infinite Scale services can register *settings bundles* with the settings service.

== Settings Usage

Services can set or query Infinite Scale *setting values* of a user from settings bundles.

== Service Accounts

The settings service needs to know the IDs of service accounts but it doesn't need their secrets. Currently only one service account can be configured which has the admin role. This can be set with the `SETTINGS_SERVICE_ACCOUNT_ID_ADMIN` envvar, but it will also pick up the global `OCIS_SERVICE_ACCOUNT_ID` envvar. Also see the xref:{s-path}/auth-service.adoc[auth-service] service description for additional details.

== Default Language

The default language can be defined via the `OCIS_DEFAULT_LANGUAGE` environment variable. If this variable is not defined, English will be used as default. The value has the ISO 639-1 format ("de", "en", etc.) and is limited to the list of supported languages. This setting can be used to set the default language for notification and invitation emails.

The `OCIS_DEFAULT_LANGUAGE` setting impacts the `notification` and `userlog` services and the WebUI. Note that translations must exist for all named components to be presented correctly.

* If  `OCIS_DEFAULT_LANGUAGE` **is not set**, the expected behavior is:
** The `notification` and `userlog` services and the Web UI use English by default, until a user sets another language in the Web UI via menu:Account[Language].
** If a user sets another language in the Web UI in menu:Account[Language], then the `notification` and `userlog` services and Web UI use the language defined by the user. If no translation is found, it falls back to English.

* If  `OCIS_DEFAULT_LANGUAGE` **is set**, the expected behavior is:
** The `notification` and `userlog` services and the Web UI use `OCIS_DEFAULT_LANGUAGE` by default, until a user sets another language in the Web UI via menu:Account[Language].
** If a user sets another language in the Web UI in menu:Account[Language], the `notification` and `userlog` services and Web UI use the language defined by the user. If no translation is found, it falls back to `OCIS_DEFAULT_LANGUAGE` and then to English.

== Custom Roles

It is possible to *replace* the default Infinite Scale roles (`admin`, `user`) with custom roles that contain custom permissions. One can set `SETTINGS_BUNDLES_PATH` to the path of a `json` file containing the new role definition.

.Role Example (shortned):
[source,json]
----
[
    {
        "id": "38071a68-456a-4553-846a-fa67bf5596cc", // ID of the role. Recommendation is to use a random uuidv4. But any unique string will do.
        "name": "user-light",                         // Internal name of the role. This is used by the system to identify the role. Any string will do here, but it should be unique among the other roles.
        "type": "TYPE_ROLE",                          // Always use `TYPE_ROLE`
        "extension": "ocis-roles",                    // Always use `ocis-roles`
        "displayName": "User Light",                  // DisplayName of the role used in webui
        "settings": [
        ],                                            // Permissions attached to the role. See Details below.
        "resource": {
            "type": "TYPE_SYSTEM"                     // Always use `TYPE_SYSTEM`
        }
    }
]
----

To create custom roles:

* Copy the role example to a `json` file.
* Change `id`, `name`, and `displayName` according your requirements.
* Copy the desired permissions from the `user-all-permissions` example to the `settings` array of the role.
* Set the `SETTINGS_BUNDLE_PATH` environment variable to the path/json-file and (re)start Infinite Scale.

See the full https://owncloud.dev/services/settings/#custom-roles[Custom Roles] json example in the developer documentation for more details.

== Caching

// renders dependent on is_cache or is_stat
:is_cache: true

When using `SETTINGS_STORE_TYPE=metadata`, the `settings` service caches the results of queries against the storage backend to provide faster responses. The content of this cache is independent of the cache used in the `storage-system` service as it caches directory listing and settings content stored in files.

include::partial$multi-location/caching-list.adoc[]

== Event Bus Configuration

include::partial$multi-location/event-bus.adoc[]

== Configuration

include::partial$deployment/services/env-and-yaml.adoc[tag=envvars-yaml]
