= Storage-Users Service Configuration
:toc: right
:tus-url: https://tus.io

:ext_name: storage-users

:description: The Infinite Scale Storage-Users service

== Introduction

{description}

// fixme: source description is still missing, and a better description is needed

== Manage Unfinished Uploads

// referencing: [oCIS FS] clean up aborted uploads https://github.com/owncloud/ocis/issues/2622

When using Infinite Scale as user storage, a directory named `storage/users/uploads` can be found in the Infinite Scale data folder. This is an intermediate directory based on {tus-url}[TUS] which is an open protocol for resumable uploads. Each upload consists of a _blob_ and a _blob.info_ file. Note that the term _blob_ is just a placeholder.

* **If an upload succeeds**, the _blob_ file will be moved to the target and the _blob.info_ file will be deleted.

* **In case of incomplete uploads**, the _blob_ and _blob.info_ files will continue to recieve data until either the upload succeeds in time or the upload expires based on the `STORAGE_USERS_UPLOAD_EXPIRATION` variable, see the table below for details.

* **In case of expired uploads**, the _blob_ and _blob.info_ files will _not_ be removed automatically. Thus a lot of data can pile up over time wasting storage space.

{empty}

Example cases for expired uploads::
* When a user uploads a big file but the file exceeds the user-quota, the upload can't be moved to the target after it has finished. The file stays at the upload location until it is manually cleared.
* If the bandwith is limited and the file to transfer can't be transferred completely before the upload expiration time is reached, the file expires and can't be processed. 

There are two commands available to manage unfinished uploads::
[source,bash]
----
ocis storage-users uploads
----
[source,plaintext]
----
...
COMMANDS:
   list     Print a list of all incomplete uploads
   clean    Clean up leftovers from expired uploads
...
----

=== Command Examples

Command to identify incomplete uploads::
[source,bash]
----
ocis storage-users uploads list
----
[source,plaintext]
----
Incomplete uploads:
 - 455bd640-cd08-46e8-a5a0-9304908bd40a (file_example_PPT_1MB.ppt, Size: 1028608, Expires: 2022-08-17T12:35:34+02:00)
----

Command to clear expired uploads::
[source,bash]
----
ocis storage-users uploads clean
----
[source,plaintext]
----
Cleaned uploads:
- 455bd640-cd08-46e8-a5a0-9304908bd40a (Filename: file_example_PPT_1MB.ppt, Size: 1028608, Expires: 2022-08-17T12:35:34+02:00)
----

== Configuration

include::partial$deployment/services/env-and-yaml.adoc[]
