= Userlog Service Configuration
:toc: right
:description: The Infinite Scale userlog service is a mediator between the eventhistory service and clients who want to be informed about user-related events. It provides an API to retrieve those.

:oc10-api-url: https://doc.owncloud.com/server/next/developer_manual/core/apis/ocs-notification-endpoint-v1.html#get-user-notifications

:service_name: userlog

== Introduction

{description} 

== Default Values

* The userlog service listens on port 9210 by default.

include::partial$deployment/services/log-service-ecosystem.adoc[]

== Prerequisites

Running the `userlog` service without running the xref:{s-path}/eventhistory.adoc[eventhistory] service is not possible.

== Configuring Events

Currently, the configuration which user-related events are of interest is hard-coded and cannot be changed.

== Retrieving

The `userlog` service provides an API to retrieve configured events. For now, this API is mostly following the {oc10-api-url}[ownCloud Server notification GET API, window=_blank].

== Subscribing

The `userlog` service provides an `/sse` (Server-Sent Events) endpoint to be informed by the server when an event happens. See https://medium.com/yemeksepeti-teknoloji/what-is-server-sent-events-sse-and-how-to-implement-it-904938bffd73[What is Server-Sent Events, window=_blank] for a simple introduction and examples to server-sent events. The `sse` endpoint will respect language changes of the user without needing to reconnect. Note that SSE have the limitation of six open connections per browser which can be reached if one has opened various tabs of the Web UI pointing to the same Infinite Scale instance.

== Posting

The userlog service is able to store global messages that will be displayed in the Web UI to all users. If a user deletes the message in the Web UI, it reappears on reload. Global messages use the endpoint `/ocs/v2.php/apps/notifications/api/v1/notifications/global` and are activated by sending a `POST` request. Note that sending another `POST` request of the same type overwrites the previous one. For the time being, only the type `deprovision` is supported.

=== Authentication

`POST` and `DELETE` endpoints provide notifications to all users. Therefore only certain users can configure them. Two authentication methods for this endpoint are provided:

* Users with the `admin` role can always access these endpoints.
* Additionally, a static secret via the `USERLOG_GLOBAL_NOTIFICATIONS_SECRET` can be defined to enable access for users knowing this secret, which has to be sent with the header containing the request.

=== Deprovisioning

Deprovision messages announce a deprovision text including a deprovision date of the instance to all users. With this message, users get informed that the instance will be shut down and deprovisioned and no further access to their data is possible past the given date. This implies that users must download their data before the given date. The text shown to users refers to this information. Note that the task to deprovision the instance does not depend on the message. The text of the message can be translated according to the translation settings, see section xref:translations[Translations]. The endpoint only expects a `deprovision_date` parameter in the `POST` request body as the final text is assembled automatically. The string hast to be in `RFC3339` format, however, this format can be changed by using `deprovision_date_format`. See the https://pkg.go.dev/time#pkg-constants[go time formating] for more details.

Also see the xref:{s-path}/graph.adoc#configuration[GRAPH_LDAP_SCHOOL_TERMINATION_MIN_GRACE_DAYS] environment variable for an additional configuration parameter.

== Deleting

* To delete events for an *user*, use a `DELETE` request to:
+
--
[source,plaintext]
----
https://<your-ocis-instance>/ocs/v2.php/apps/notifications/api/v1/notification
----

containing the IDs to delete. 
--

* Sending a `DELETE` request to the *global* endpoint:
+
--
[source,plaintext]
----
https://<your-ocis-instance>/ocs/v2.php/apps/notifications/api/v1/notifications/global
----

to remove a global message is a restricted action, see the xref:authentication[Authentication] section for more details.
--

// include common translations text
:envvar_name: USERLOG_TRANSLATION_PATH
include::partial$deployment/services/translations.adoc[]

== Storing

// renders dependent on is_cache or is_store
:is_store: true

// get the complete .adoc page but do not render any contained tag directive when found in the middle
include::partial$multi-location/cache-store.adoc[tag=**]

== Event Bus Configuration

include::partial$multi-location/event-bus.adoc[]

== Configuration

include::partial$deployment/services/env-and-yaml.adoc[tag=envvars-yaml]
