= Userlog Service Configuration
:toc: right
:description: The Infinite Scale userlog service is a mediator between the eventhistory service and clients who want to be informed about user-related events. It provides an API to retrieve those.

:oc10-api-url: https://doc.owncloud.com/server/next/developer_manual/core/apis/ocs-notification-endpoint-v1.html#get-user-notifications

:service_name: userlog

// remember to REMOVE the corresponding tab if a new ocis release will be published

// :no_second_tab: true
:no_third_tab: true

== Introduction

{description} 

== Prerequisites

Running the `userlog` service without running the xref:{s-path}/eventhistory.adoc[eventhistory] service is not possible.

== Storing

The `userlog` service persists information via the configured store in `USERLOG_STORE`. Possible stores are:

include::partial$multi-location/caching-list.adoc[]
// you must not have one or more blank lines here as it breaks continuous numbering!
.  When using `redis-sentinel`, the Redis master to use is configured via `USERLOG_STORE_NODES` in the form of `<sentinel-host>:<sentinel-port>/<redis-master>` like `10.10.0.200:26379/mymaster`.

== Configuring Events

Currently, the configuration which user-related events are of interest is hard-coded and cannot be changed.

== Retrieving

The `userlog` service provides an API to retrieve configured events. For now, this API is mostly following the {oc10-api-url}[ownCloud Server notification GET API, window=_blank].

== Subscribing

The `userlog` service provides an `/sse` (Server-Sent Events) endpoint to be informed by the server when an event happens. See https://medium.com/yemeksepeti-teknoloji/what-is-server-sent-events-sse-and-how-to-implement-it-904938bffd73[What is Server-Sent Events, window=_blank] for a simple introduction and examples to server-sent events. The `sse` endpoint will respect language changes of the user without needing to reconnect. Note that SSE have the limitation of six open connections per browser which can be reached if one has opened various tabs of the Web UI pointing to the same Infinite Scale instance.

== Posting

The userlog service is able to store global messages that will be displayed in the Web UI to all users. If a user deletes the message in the Web UI, it reappears on reload. Global messages use the endpoint `/ocs/v2.php/apps/notifications/api/v1/notifications/global` and are activated by sending a `POST` request. Note that sending another `POST` request of the same type overwrites the previous one. For the time being, only the type `deprovision` is supported.

=== Authentication

`POST` and `DELETE` endpoints provide notifications to all users. Therefore only certain users can configure them. Two authentication methods for this endpoint are provided:

* Users with the `admin` role can always access these endpoints.
* Additionally, a static secret via the `USERLOG_GLOBAL_NOTIFICATIONS_SECRET` can be defined to enable access for users knowing this secret, which has to be sent with the header containing the request.

=== Deprovisioning

Deprovision messages announce a deprovision text including a deprovision date of the instance to all users. With this message, users get informed that the instance will be shut down and deprovisioned and no further access to their data is possible past the given date. This implies that users must download their data before the given date. The text shown to users refers to this information. Note that the task to deprovision the instance does not depend on the message. The text of the message can be translated according to the translation settings, see section xref:translations[Translations]. The endpoint only expects a `deprovision_date` parameter in the `POST` request body as the final text is assembled automatically. The string hast to be in `RFC3339` format, however, this format can be changed by using `deprovision_date_format`. See the https://pkg.go.dev/time#pkg-constants[go time formating] for more details.

Also see the xref:{s-path}/graph.adoc#configuration[GRAPH_LDAP_SCHOOL_TERMINATION_MIN_GRACE_DAYS] environment variable for an additional configuration parameter.

== Deleting

* To delete events for an *user*, use a `DELETE` request to:
+
--
[source,plaintext]
----
https://<your-ocis-instance>/ocs/v2.php/apps/notifications/api/v1/notification
----

containing the IDs to delete. 
--

* Sending a `DELETE` request to the *global* endpoint:
+
--
[source,plaintext]
----
https://<your-ocis-instance>/ocs/v2.php/apps/notifications/api/v1/notifications/global
----

to remove a global message is a restricted action, see the xref:authentication[Authentication] section for more details.
--

== Translations

The `userlog` service has embedded translations sourced via transifex to provide a basic set of translated languages. These embedded translations are available for all deployment scenarios. In addition, the service supports custom translations, though it is currently not possible to just add custom translations to embedded ones. If custom translations are configured, the embedded ones are not used. To configure custom translations, the `USERLOG_TRANSLATION_PATH` environment variable needs to point to a base folder that will contain the translation files. This path must be available from all instances of the userlog service, a shared storage is recommended. Translation files must be of type https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html#PO-Files[.po] or https://www.gnu.org/software/gettext/manual/html_node/Binaries.html[.mo]. For each language, the filename needs to be `userlog.po` (or `userlog.mo`) and stored in a folder structure defining the language code. In general the path/name pattern for a translation file needs to be:

[source,plaintext]
----
{USERLOG_TRANSLATION_PATH}/{language-code}/LC_MESSAGES/userlog.po
----

The language code pattern is composed of `language[_territory]` where  `language` is the base language and `_territory` is optional and defines a country.

For example, for the language `de`, one needs to place the corresponding translation files to 

[source,plaintext]
----
{USERLOG_TRANSLATION_PATH}/de/LC_MESSAGES/userlog.po
----

include::partial$deployment/services/webui_language_code.adoc[]

=== Translation Rules

*   If a requested language code is not available, the service tries to fall back to the base language if available. For example, if the requested language-code `de_DE` is not available, the service tries to fall back to translations in the `de` folder.
*   If the base language `de` is also not available, the service falls back to the system's default English (`en`),
which is the source of the texts provided by the code.

== Configuration

include::partial$deployment/services/env-and-yaml.adoc[]
