= Web Service Configuration
:toc: right
:description: The web service embeds and serves the static files for the Infinite Scale web client.

:service_name: web

== Introduction

{description} See the xref:{latest-webui-version}@webui:owncloud_web:index.adoc[ownCloud Web] description for more details.

Note that clients will respond with a connection error if the web service is not available.

The web service also provides a minimal API for branding functionality like changing the logo shown.

== Default Values

* Web listens on port 9100 by default.

== Custom Compiled Web Assets

If you want to use your custom compiled web client assets instead of the embedded ones, then you can do that by setting the `WEB_ASSET_PATH` variable to point to your compiled files. See https://owncloud.dev/clients/web/getting-started/[ownCloud Web / Getting Started] and https://owncloud.dev/clients/web/backend-ocis/[ownCloud Web / Setup with oCIS] in the developer documentation for more details.

== Customize the Web UI Configuration

See the xref:deployment/webui/webui.adoc[Web UI] documentation for how to configure theming, customization and when you want to embed Web into another application.

// you will find `Web UI Configuration`, `Web UI Options` and `Embedding Web` from the dev docs in that link.

== Configuration

include::partial$deployment/services/env-and-yaml.adoc[]
