= Getting Started
:toc: right
:toclevels: 3


== Requirements

We want contribution to oCIS and the creation of extensions to be as easy as possible.
So we are trying to reflect this in the tooling. It should be kept simple and quick to be set up.

Besides standard development tools like git and a text editor, you need the following software for development:

- Go >= v1.22 (link:https://golang.org/doc/install[install instructions])
- pnpm (link:https://pnpm.io/installation[install instructions])
- docker (link:https://docs.docker.com/get-docker/[install instructions])
- docker-compose (link:https://docs.docker.com/compose/install/[install instructions])

If you find tools needed besides the mentioned above, please feel free to open an issue or open a PR.

== Repository structure

oCIS consists of multiple microservices, also called extensions. We started by having standalone repositories for each of them, but quickly noticed that this adds a time-consuming overhead for developers. So we ended up with a monorepo housing all the extensions in one repository.

Each extension lives in a subfolder (e.g. `accounts` or `settings`) within this repository as an independent Go module, following the link:https://github.com/golang-standards/project-layout[golang-standard project-layout]. They have common Makefile targets and can be used to change, build and run individual extensions. This allows us to version and release each extension independently.

The `ocis` folder contains our link:https://github.com/asim/go-micro/[go-micro] and link:https://github.com/thejerf/suture[suture] based runtime. It is used to import all extensions and implements commands to manage them, similar to a small orchestrator. With the resulting oCIS binary you can start single extensions or even all extensions at the same time.

The `docs` folder contains the source for the xref:../.adoc[oCIS documentation].

The `deployments` folder contains documented deployment configurations and templates. On a single node, running a single ocis runtime is a resource efficient way to deploy ocis. For multiple nodes docker compose or helm charts for kubernetes examples can be found here.

The `scripts` folder contains scripts to perform various build, install, analysis, etc. operations.

== Starting points

Depending on what you want to develop there are different starting points. These will be described below.

=== Developing oCIS

If you want to contribute to oCIS:

- see link:https://github.com/owncloud/ocis#contributing[contribution guidelines]
- make sure the tooling is set up by xref:build.adoc[building oCIS] and xref:build-docs.adoc[building the docs]
- create or pick an link:https://github.com/owncloud/ocis/issues[open issue] to develop on and mention in the issue that you are working on it
- open a PR and get things done

=== Developing extensions

If you want to develop an extension, start here: xref:extensions.adoc[Extensions]
