= Security Aspects of ownCloud Infinite Scale
:toc: right

:description: This document gives you an overview of the different security measures of ownCloud Infinite Scale.

== Introduction

{description}

== Operational aspects

=== API Gateway

oCIS makes use of a microservice architecture. But instead handling authorization and authentication in each service, we have implemented an API Gateway (the xref:deployment/services/proxy.adoc[proxy service]) which handles authentication and authorization. All requests have to go through this service. This has the nice effect that all other services can be hidden behind a firewall, which reduces the attack surface dramatically.

=== Reverse Proxy

Through the help of a reverse proxy in front of the API gateway, it's possible to implement further protection mechanisms like request rate limiting or blocking requests from sources which seem to be doing malicious actions like DOS or Slowloris attacks.

=== Monitoring (Tracing, Log Aggregation)

All oCIS services support request tracing. This means, you can visualize the path a request takes, which services are involved etc. In addition to that, all logs can be aggregated by common software like graylog, splunk, etc. This not only helps with administrating the services, but can also aid to detect malicious behavior by analyzing the logs or traces.

=== OpenID Connect

oCIS does not rely on a propriatary user management, instead it makes use of OpenID Connect. For small instances or testing purposes, a xref:deployment/services/idm.adoc[minimal LDAP Service named IDM] is included. For anything else, it is recommended that customers hook to their own OpenID Connect provider unsing the xref:deployment/services/idp.adoc[IDP service]. If an own OpenID Connect provider is not available, use secure standard software like Keycloak to connect to the existing user management system like Active Directory or any LDAP server.

== Technological Aspects

=== Role System

oCIS provides a flexible role system which allows to customize the permissions of roles or to define custom roles in the system. This way, permissions for certain roles can be restricted to the absolute minimum.

=== Extension System

Compared to the apps/extensions in ownCloud 10, the oCIS extension/services system is more secure because they are developed and deployed as standalone services. They communicate via APIs with the core services and therefore can only use specific interfaces instead of having direct access to storages and data. A single malicious extension cannot corrupt the whole system.

=== File based storage

oCIS is designed to work without a database. This means, there are much fewer services required and therefor have a smaller attack surface.

=== Golang

When developing oCIS from the ground up, it was decided to switch from PHP to Golang. This eliminates a bunch of security risks which one has with PHP like: _Remote File Inclusion_, _Local File Inclusion_ and others. Golang also has a good file system API so that it's easy to protect against directory traversal issues.

The fact, that Golang is statically typed, helps reduce the amount of logic errors.

=== Vuejs

The web client xref:{latest-webui-version}@webui:owncloud_web:index.adoc[ownCloud Web] of oCIS is implement with Vuejs. This supports securely displaying user input, since everything which is displayed is being escaped per default.

== Developmental Aspects

=== Dependency Monitoring

Development has a processes in place to automatically monitor the dependencies in the projects used. This helps to detect vulnerable dependencies in an early stage and enables patching as soon as possible.

=== Process for Patches

When any security issues have been fixed, development makes sure to release a patched version as soon as possible and notifies our customers via several communication channels like the security advisories on our website, via E-mail or the {oc-central-url}[Community Forum] web page.

=== Development Best Practices

ownCloud follows development best practices which include:

* All code is being reviewed by multiple people.
* The code is statically analyzed by various tools to find bugs or security issues in an early stage.
* Development makes use of defensive development patterns like input validation and proper error handling.
