= Backup Considerations
:toc: right
:toclevels: 3

This small guide aims to shed some light on the internal Infinite Scale data structure. You can refer to it when you are trying to optimize your backups or if you are just curious about how Infinite Scale stores its data.

Note, as a prerequisite backing up Infinite Scale, the instance has to be fully shut down for the time being.

== Ocis Data Structure

Ocis stores its data in a folder that can be configured via the environment variable `OCIS_BASE_DATA_PATH`. Without further configuration, services derive from that path when they store data, though individual settings for certain data types can be configured.

The default value for the `OCIS_BASE_DATA_PATH` variable is `$HOME/.ocis` (or `/var/lib/ocis` when using the docker container. Note: Configuration data is by default stored in `/etc/ocis/` in the container.).

Inside this folder, Infinite Scale will store all its data in separate subdirectories. That includes metadata, configurations, queues and stores etc. The actual bytes of files (blobs) are handled by a so called blobstore, which also stores here by default. Depending on the used blobstore, the blobs need to be backed up separately, for example if S3 is used. Note: See special case for the `config` folder in a docker container.

=== Base Data Path Overview

Listing the contents of the folder will return the following:
[source,bash]
----
    ~/.ocis/:tree -L 1
.
в”њв”Ђв”Ђ config
в”њв”Ђв”Ђ idm
в”њв”Ђв”Ђ idp
в”њв”Ђв”Ђ nats
в”њв”Ђв”Ђ proxy
в”њв”Ђв”Ђ search
в”њв”Ђв”Ђ storage
в”њв”Ђв”Ђ thumbnails
в””в”Ђв”Ђ web

10 directories, 0 files
----

The following sections describe the content and background of the subdirectories to decide if a backup is required or recommended and its effect when it is not backed up.

=== `config`

Contains basic Infinite Scale configuration created by `ocis init`(Note: The location of the configuration folder can be specified with the `OCIS_CONFIG_DIR` environment variable, but for this document we will assume this variable is not set and the default is used.)

[source,bash]
----
    ~/.ocis/config/:tree
.
в””в”Ђв”Ђ ocis.yaml

1 directory, 1 file
----

* `ocis.yaml`:\
BACKUP RECOMMENDED. Holds Infinite Scale configuration data. The contents can vary depending on your environment variables. In general, most of this file can be recreated again by running `ocis init`. This will recreate secrets and certificates. However, if not backed up completely, some fields MUST be copied over from the old config manually to regain data access after a restore:

| Field Name | Envvar Name | Description | If not backed up |
| --- | --- | --- | --- |
| `idp.ldap.bind_password` | `OCIS_LDAP_BIND_PASSWORD` | Password for the idp | no logins possible |
| `idm.service_user_passwords.idp_password`| `IDM_IDPSVC_PASSWORD` | Same as above | no logins possible |
| `system_user_id` | `OCIS_SYSTEM_USER_ID` | The id of storage-system user | no logins possible |
| `idm.service_user_passwords.reva_password`| `IDM_REVASVC_PASSWORD` | The reva password | no logins possible |
| `auth_basic.auth_providers.ldap.bind_password` | `AUTH_BASIC_LDAP_BIND_PASSWORD` | Same as above | no logins possible |
| `users.drivers.ldap.bind_password` | `USERS_LDAP_BIND_PASSWORD` | Same as above | no logins possible |
| `groups.drivers.ldap.bind_password` | `GROUPS_LDAP_BIND_PASSWORD` | Same as above | no logins possible |
| `storage_users.mount_id` | `STORAGE_USERS_MOUNT_ID` | The mountid of the storage_users service | sharing data lost |
| `gateway.storage_registry.storage_users_mount_id` | `GATEWAY_STORAGE_USERS_MOUNT_ID` | Same as above | sharing data lost |

=== `idm`

Note: This folder will not appear if you use an external idm. Refer to your idms documentation for backup details in this case.

Contains the data for the internal Infinite Scale identity management. See the xref:../services/idm/index.adoc[IDM README] for more details.

[source,bash]
----
    ~/.ocis/idm/:tree
.
в”њв”Ђв”Ђ ldap.crt
в”њв”Ђв”Ђ ldap.key
в””в”Ђв”Ђ ocis.boltdb

1 directory, 3 files
----

* `ocis.boltdb`:\
BACKUP REQUIRED. This is the boltdb database that stores user data. Use `IDM_DATABASE_PATH` to specify its path. If not backed up, Infinite Scale will have no users, therefore also all data is lost.
* `ldap.crt`:\
BACKUP OPTIONAL. This is the certificate for the idm. Use `IDM_LDAPS_CERT` to specify its path. Will be auto-generated if not backed up.
* `ldap.key`:\
BACKUP OPTIONAL. This is the certificate key for the idm. Use `IDM_LDAPS_KEY` to specify its path. Will be auto-generated if not backed up.


=== `idp`

Note: This folder will not appear if you use an external idp. Refer to your idp's documentation for backup details in this case.

Contains the data for the internal Infinite Scale identity provider. See the xref:../services/idp/index.adoc[IDP README] for more details.

[source,bash]
----
    ~/.ocis/idp/:tree
.
в”њв”Ђв”Ђ encryption.key
в”њв”Ђв”Ђ private-key.pem
в””в”Ђв”Ђ tmp
    в””в”Ђв”Ђ identifier-registration.yaml

2 directories, 3 files
----

* `encryption.key`:\
BACKUP RECOMMENDED. This is the encryption secret. Use `IDP_ENCRYPTION_SECRET_FILE` to specify its paths. Not backing this up will force users to relogin.
* `private-key.pem`:\
BACKUP RECOMMENDED. This is the encryption key. Use `IDP_SIGNING_PRIVATE_KEY_FILES` to specify its paths. Not backing this up will force users to relogin.
* `identifier-registration.yml`:\
BACKUP OPTIONAL. It holds configuration for oidc clients (web, desktop, ios, android). Will be recreated if not backed up.

=== `nats`

Note: This folder will not appear if you use an external nats installation. In that case, data has to secured in alignment with the external installation.

Contains nats data for streams and stores. See the xref:../services/nats/index.adoc[NATS README] for more details.

[source,bash]
----
    ~/.ocis/nats/:tree -L 1
.
в””в”Ђв”Ђ jetstream

----

* `jetstream`:\
BACKUP RECOMMENDED. This folder contains nats data about streams and key-value stores. Use `NATS_NATS_STORE_DIR` to specify its path. Not backing it up can break history for multiple (non-vital) features such as history or notifications. The Infinite Scale functionality is not impacted if omitted.

=== `proxy`

Contains proxy service data. See the xref:../services/proxy/index.adoc[PROXY README] for more details.

[source,bash]
----
    ~/.ocis/proxy/:tree
.
в”њв”Ђв”Ђ server.crt
в””в”Ђв”Ђ server.key

1 directory, 2 files
----

* `server.crt`:\
BACKUP OPTIONAL. This is the certificate for the http services. Use `PROXY_TRANSPORT_TLS_CERT` to specify its path.
* `server.key`:\
BACKUP OPTIONAL. This is the certificate key for the http services. Use `PROXY_TRANSPORT_TLS_KEY` to specify its path.

=== `search`

Contains the search index. See the xref:../services/search/index.adoc[SEARCH README] for more details.

[source,bash]
----
    ~/.ocis/search/:tree -L 1
.
в””в”Ђв”Ђ bleve

2 directories, 0 files
----

* `bleve`:\
BACKUP RECOMMENDED/OPTIONAL. This contains the search index. Can be specified via `SEARCH_ENGINE_BLEVE_DATA_PATH`. If not backed up, the search index needs to be recreated. This can take a long time depending on the amount of files.

=== `storage`

Contains Infinite Scale meta (and blob) data, depending on the blobstore. See the xref:../services/storage-users/index.adoc[STORAGE-USERS README] for more details.

[source,bash]
----
    ~/.ocis/storage/:tree -L 1
.
в”њв”Ђв”Ђ metadata
в”њв”Ђв”Ђ ocm
в””в”Ђв”Ђ users

4 directories, 0 files
----

* `metadata`:\
BACKUP REQUIRED. Contains system data. Path can be specified via `STORAGE_SYSTEM_OCIS_ROOT`. Not backing it up will remove shares from the system and will also remove custom settings.
* `ocm`:\
BACKUP REQUIRED/OMITABLE. Contains ocm share data. When not using ocm sharing, this folder does not need to be backed up.
* `users`:\
BACKUP REQUIRED. Contains user data. Path can be specified via `STORAGE_USERS_OCIS_ROOT`. Not backing it up will remove all spaces and all files. As result, you will have a configured but empty Infinite Scale instance, which is fully functional accepting new data. Old data is lost.

=== `thumbnails`

Contains thumbnails data. See the xref:../services/thumbnails/index.adoc[THUMBNAILS README] for more details.

[source,bash]
----
    ~/.ocis/thumbnails/:tree -L 1
.
в””в”Ђв”Ђ files
----

* `files`:\
OPTIONAL/RECOMMENDED. This folder contains prerendered thumbnails. Can be specified via `THUMBNAILS_FILESYSTEMSTORAGE_ROOT`. If not backed up, thumbnails will be regenerated automatically on access which leads to some load on the thumbnails service.

=== `web`

Contains web assets such as custom logos, themes etc. See the xref:../services/web/index.adoc[WEB README] for more details.

[source,bash]
----
    ~/.ocis/web/:tree -L 1
.
в””в”Ђв”Ђ assets

2 directories, 0 files
----

* `assets`:\
BACKUP RECOMMENDED/OMITABLE. This folder contains custom web assets. Can be specified via `WEB_ASSET_CORE_PATH`. If no custom web assets are used, there is no need for a backup. If those exist but are not backed up, they need to be reuploaded.

=== `external services`

When using an external idp/idm/nats or blobstore, its data needs to be backed up separately. Refer to your idp/idm/nats/blobstore documentation for backup details.

== Backup Consistency Command

Infinite Scale now allows checking an existing backup for consistency. Use the command:
[source,bash]
----
ocis backup consistency -p "<path-to-base-folder>"
----

`path-to-base-folder` needs to be replaced with the path to the storage providers base path. Should be same as the `STORAGE_USERS_OCIS_ROOT`

Use the `-b s3ng` option when using an external (s3) blobstore. Note: When using this flag, the path to the blobstore must be configured via envvars or a yaml file to match the configuration of the original instance. Consistency checks for other blobstores than `ocis` and `s3ng` are not supported at the moment.
