= Setup with Docker
:toc: right

:docker-ocis-url: https://hub.docker.com/r/owncloud/ocis
:install-docker-url: https://docs.docker.com/engine/install/#server
:install-d-compose-url: https://docs.docker.com/compose/install/
:docker-cli-url: https://docs.docker.com/engine/reference/commandline/run/
:docker-logs-url: https://docs.docker.com/engine/reference/commandline/logs/
:docker-stop-url: https://docs.docker.com/engine/reference/commandline/stop/
:docker-ps-url: https://docs.docker.com/engine/reference/commandline/ps/
:docker-restart-url: https://docs.docker.com/engine/reference/commandline/restart/

:swarm-v-kub-url: https://circleci.com/blog/docker-swarm-vs-kubernetes/#c-consent-modal

:description: Docker images for oCIS are available on {docker-ocis-url}[Docker Hub]. You can easily download and start an image with only a few commands. 

== Introduction

{description}

== Docker Prerequisites

To fetch and run oCIS in a Docker container, make sure the following packages are installed:

* docker,
* docker-compose,
* optionally kubernetes for more sophisticated container management.

=== Check if You Have Docker Installed

Use the following command to check if `docker` is installed on your system:

[source,bash]
----
which docker
----

If Docker is installed, you'll be informed. If not, you may get no output at all or a message that it couldn't be found. In that case you need to install docker first.

Use the following command to check if `docker-compose` is installed on your system:

[source,bash]
----
which docker-compose
----

=== Install Docker and Docker-Compose

On most Linux distributions you can simply install Docker and Docker-Compose via the package manager.

Alternatively, install docker depending on your OS from the Docker site. See {install-docker-url}[Install Docker Engine] and {install-d-compose-url}[Install Docker Compose] for details.

== Download the oCIS Image

// fixme: things are gonna change: after a call with mbarz and cdegen it turns out that latest is not a good idea to use as latest will always point to the master (!) but not to a stable version. atm to use a stable version you would need to use a tag! most likely a "stable" tag will be introduced pointing to the latest stable release and latest will point to the latest master release. this will also be anncounced/described on dockerhub. this means that we have to review the commands below regarding installation, version and upgrade.

To give some terminology guidance, images are unchangeable snapshots of live containers while containers are running (or stopped) instances of an image.

* To download the latest oCIS image, run the following command:
+
[source,bash]
----
sudo docker pull owncloud/ocis
----

* Check your oCIS image with:
+
[source,bash]
----
sudo docker images
----
+
[caption=]
.Example output
[source,plaintext]
----
REPOSITORY      TAG       IMAGE ID       CREATED       SIZE
owncloud/ocis   latest    fc4151802141   9 hours ago   98.3MB
----

* Check you oCIS version with the following command. Note that you need to have `jq` installed:
+
[source,bash]
----
sudo docker inspect owncloud/ocis:latest | \
   jq '.[] | .Config.Labels."org.opencontainers.image.version"'
----
+
[caption=]
.Example output
[source,plaintext]
----
latest
----

== Remove an oCIS Image

If you want to remove an oCIS image, run the following command:

[source,bash]
----
sudo docker images
----

[caption=]
.Example output
[source,plaintext]
----
REPOSITORY      TAG       IMAGE ID       CREATED        SIZE
owncloud/ocis   latest    22c455afc445   46 hours ago   98.3MB
----

Replace <image-id> with the ID you want to remove from the above printout:
[source,bash]
----
sudo docker rmi <image-id>
----

== Start the oCIS Runtime

When you run the oCIS docker container, you _must_ specify at least the `OCIS_URL` as environment variable to have browser access. This is  because `localhost` would point to a location inside the container and not to the server being accessed. For details see: xref:deployment/general/general-info.adoc#configurations-to-access-the-webui[Configurations to Access the WebUI].

In the example below, replace `<your-hostname>` with the host name or IP address of your server.

To run the docker container, simply type:

[source,bash]
----
sudo docker run \
    --name ocis_runtime \
    --rm \
    -it \
    -p 9200:9200 \
    -e OCIS_INSECURE=true \
    -e PROXY_HTTP_ADDR=0.0.0.0:9200 \
    -e OCIS_URL=https://<your-hostname>:9200 \
    owncloud/ocis
----

You may also see xref:deployment/general/general-info.adoc#define-the-ocis-data-path[Define the oCIS Data Path] for another important basic environment variable.

WARNING: With docker you can run containers multiple times concurrently. With oCIS you have to define different ports and data paths for each of the containers you run to avoid any unexpected behaviour. 

The following {docker-cli-url}[docker command-line options] are quite helpful to know:

-e: Set environment variables::
Use this to hand over only a few environment variables to the run command.

-i: Keep STDIN open even if not attached::
This keeps STDIN open to the container.

-t: Allocate a pseudo-TTY::
Allocate a virtual terminal session within the container.

-p: Publish a container's port(s) to the host::
Defines the port mapping `<hostPort>:<containerPort>`. Use the port mapping which is necessary if you want to access the dockerized oCIS web user interface.

--rm: Automatically remove the container when it exits::
Tell the docker daemon to clean up the container and remove the file system after the container exits.

--env-file: Read in a file of environment variables::
If you have more environment variables to hand over, put them all in a file and use this command-line option. Preferably have `/etc/ocis` as location. See xref:deployment/general/general-info.adoc#configuration-rules[Configuration Rules] for more details.

--name: Assign a name to the container::
By default, containers created with docker run are given a random name like `small_roentgen` which may not be suitable to identify their purpose properly. Giving containers a meaningful name helps identifying them more easily.

== Common Useful Docker Commands

=== Start the Container Detached

Note that the docker run command will bind the container to the shell you are running. If you want to detatch it and avoid it gets stopped when closing the shell or the shell gets disconnected (SIGHUP), use the following docker run commandline option:

-d or --detach: Run container in background and print container ID::
The docker container runs in the background of your terminal. It does not receive input or display output.

=== List Running Containers

To {docker-ps-url}[list] all _running_ containers type:

[source,bash]
----
docker ps
----

[caption=]
.Example output
[source,plaintext,options="nowrap"]
----
CONTAINER ID   IMAGE           COMMAND                  CREATED         STATUS         PORTS                                       NAMES
a0e4db3e91e8   owncloud/ocis   "/usr/bin/ocis server"   8 seconds ago   Up 6 seconds   0.0.0.0:9200->9200/tcp, :::9200->9200/tcp   ocis_runtime
----

=== Stop a Running Container

To {docker-stop-url}[stop] a runnig detached container, you first need the container ID which you will get with the above command. Then type the following command and replace <container-id> with the ID of the container you want to stop:

[source,bash]
----
docker stop <container-id>
----

=== Restarting a Container

To {docker-restart-url}[restart] a container, type the following and replace the <container-id> accordingly:

[source,bash]
----
docker restart <container-id>
----

=== Print Logs From Detached Container

The {docker-logs-url}[docker logs] command shows information logged by a running container which is useful if you have detached it. To show the logs and follow log output, type the following and replace the <container-id> accordingly:

[source,bash]
----
docker logs -f <container-id>
----
