= General Information
:toc: right
:description: This document covers general aspects of Infinite Scale like start modes, services, important minimum configuration etc. for a common understanding.

include::partial$multi-location/compose-version.adoc[]

== Introduction

{description}

IMPORTANT: We highly recommend reading this document first before you start setting up your system. Many obstacles can be avoided when knowing the basic concepts. Though it is tempting to just give things a try - which is totally ok, you will quickly realize that you may have to start again from scratch before the setup meets your requirements.

The example commands shown need to be adjusted depending on whether you are using the xref:depl-examples/minimal-bare-metal.adoc[Minimal Bare Metal Deployment] or a xref:deployment/container/container-setup.adoc[Container Setup].

When using global options on startup, you can always use command line options or environment variables. Run `ocis help` and see xref:starting-infinite-scale-with-environment-variables[] for details.

== Embedded Supervisor (Runtime)

Infinite Scale has an xref:architecture/architecture.adoc#infinite-scale-microservice-runtime[embedded supervisor] for managing the runtime and reducing the memory footprint. In addition, this supervisor takes care that a service will be restarted automatically if it fails. When using an external supervisor like systemd, Kubernetes or others, the embedded supervisor is not needed, the services are managed by the external supervisor.

== Deciding the Startup Mode

The following two mode types do not predefine a particular installation method like the manual or container setup. When using Kubernetes, the embedded supervisor is not necessary, the supervisor of the underlying system is used.

Starting Infinite Scale using the embedded supervisor::
This mode can be used when scaling is not the primary focus and can be the case if you have a:
* testing and/or development environment, or
* small production environment (xref:availability_scaling/availability_scaling.adoc#single-server-setup[Single Server Setup]).
* See: xref:depl-examples/minimal-bare-metal.adoc[Minimal Bare Metal Deployment] and xref:deployment/container/container-setup.adoc[Container Setup] for more details.

Starting Infinite Scale in unsupervised mode::
This mode is used when _availability, scaling and the adjustment to dynamically changing requirements_ have a xref:availability_scaling/availability_scaling.adoc#deployment-evolution[high priority]. In this case, an external supervisor like Kubernetes is used to deploy and run Infinite Scale with its services.
* See: xref:deployment/container/orchestration/orchestration.adoc[Container Orchestration] for more details.

== Managing Services

Services are built as microservices which can be started, stopped or instantiated. xref:{s-path}/services_rules.adoc[Services Rules] documentation has been added to explain some background. Read this carefully to avoid unwanted behavior. For details of each service see the xref:deployment/services/services.adoc[Services] documentation.

=== List Available Services

Just type `ocis` to get a list of commands and available services.

When typing `ocis <service-name> --help`, you will get detailed help regarding the specified service.

=== Manage Instances of Services

==== Infinite Scale Supervised Services

In supervised mode, all services are started with one command as you can see below in the example when using the binary setup. Note that the services started with the runtime share the same PID.

Start the Infinite Scale Runtime::

[source,bash]
----
ocis server
----

List running services::

[source,bash]
----
ocis list
----

Stopping the Infinite Scale Runtime::
In supervised mode, you have to stop the `ocis server` which also stops all services. See xref:depl-examples/minimal-bare-metal.adoc#stopping-infinite-scale[Stopping Infinite Scale] for more details.

==== Unsupervised Services

At any time, you can create unsupervised instances of a service with `ocis [service-name] server`, for example `ocis proxy server`. _These services are independent of services in supervised mode and have their own PID_. The Instances are managed with classic OS methods or e.g. via Kubernetes.

Note that you need configuration for and access to the service instances like with a load balancer when you scale.

=== Configuring Services

To configure services, see the xref:deployment/services/services.adoc[Services] section in the _Deployment_ documentation.

== Configuration Rules

// taken from: https://owncloud.dev/ocis/config/

NOTE: Administrators must be aware of the sources, the location and order applied (the _configuration file arithmetics_). Mismanaging them can be a source of confusion leading to undesired results on the final configuration created and applied.

* Infinite Scale uses a hierarchical structure for its configuration, *where each element overwrites its precedent*. These are:

** Infinite Scale environment variables.
** Services configuration files. +
like xref:{s-path}/app-registry.adoc[app-registry.yaml] or xref:{s-path}/proxy.adoc[proxy.yaml]
** Infinite Scale configuration file. +
xref:deployment/general/ocis-init.adoc[ocis.yaml]

Configurations must be located in the xref:default-paths[OCIS_CONFIG_DIR] path.

=== Configuration File Naming

The configuration files for Infinite Scale are YAML-based (a human-friendly data serialization language).

The filename to define a config has the following namespace:

[source,plaintext]
----
ocis.yaml
 or
[service name].yaml
----

When using `ocis.yaml` and you configure a service, the topic for the service configuration must be the service name.

You can list the available services names by typing:

[source,bash]
----
ocis list
----

=== Special Configuration Settings

Special configuration settings can be the following:

* Configurations that can only be made with yaml but not with environment variables.
* yaml configurations that use an OS environment variable for the value.

.yaml only settings
There are certain situations where multiple settings using the same keys apply for a configuration set. This can be like in the xref:{s-path}/app-registry.adoc[app-registry] service where default apps for mimetypes are defined. A single environment variable cannot hold all that information. For this case, a yaml configuration is the only way possible. Note that both installation methods, binary and container, can deal with yaml configuration files.

.Using OS environment variables in yaml files
OS environment variables can be used in yaml config files for Infinite Scale services which will be replaced by the actual value of the environment variable at runtime. This method allows defining a standardized setup, but parameterize it for different use cases.

{empty}

.Example:
--
[source,yaml]
----
web:
  http:
    addr: ${SOME_HTTP_ADDR}
----

In the example above, the value of the OS environment variable `SOME_HTTP_ADDR` will be used at runtime for the key `addr`.
--

== Default Paths

As you will read below, the config directory and the base directory for storing metadata must be located on POSIX filesystems. Consider for the ease of backup and restore, to keep both directories on the same filesystem.

Note that the term _blob_ is used for file data the user uploads, while _metatdata_ refers to all data that describes the blob.

[width="100%",cols="30%,70%",options="header"]
|===
| Environment variable
| Description

a| xref:deployment/services/env-vars-special-scope.adoc#extended-environment-variables[OCIS_CONFIG_DIR]
| Path to config files.

a| xref:deployment/services/env-vars-special-scope.adoc#extended-environment-variables[OCIS_BASE_DATA_PATH]
| Path to system relevant data.

a| xref:{s-path}/storage-users.adoc[STORAGE_USERS_OCIS_ROOT]
a| Path to blobs and metadata if POSIX is used. +
Derives from `OCIS_BASE_DATA_PATH` if not set otherwise. +
Used if `STORAGE_USERS_DRIVER` is set to `ocis`

a| xref:{s-path}/storage-users.adoc[STORAGE_USERS_S3NG_ROOT]
a| Path to metadata if S3 is used. +
Derives from `OCIS_BASE_DATA_PATH` if not set otherwise. +
Used if `STORAGE_USERS_DRIVER` is set to `s3ng`. +
See xref:using-s3-for-blobs[Using S3 for Blobs] for the S3 configuration.
|===

=== Configuration Directory

* The configuration directory has a default location for _config_ files, which *must be* on a POSIX storage:

** For container images (inside the container) +
`/etc/ocis/`
+
** For binary releases +
`$HOME/.ocis/config/`
+
[NOTE]
====
* Do not replace `$HOME` with `~` (tilde).
** The code does not resolve `~` to the users home directory.
* Check that `$HOME` resolves to a valid directory.
** When using a system user for the runtime, which has no login and therefore no home directory, like in the scenario xref:depl-examples/bare-metal.adoc#setup-the-systemd-service[Setup the systemd Service], you *must* specify a configuration file location.
====

* You can deviate from the default location and define a custom configuration directory on startup using the environment variable `OCIS_CONFIG_DIR`.

=== Base Data Directory

Because Infinite Scale does not use a database for storing information like users, groups, spaces, internal data, etc., it saves all this data to a permanent file location. Depending on the system setup, the base directory contains not only the metadata but also blobs. See xref:prerequisites/prerequisites.adoc#filesystems-and-shared-storage[Filesystems and Shared Storage] for more details.

* When only using a supported POSIX filesystem, blobs and metadata are stored on POSIX.  
* When using S3 and POSIX, blobs are stored on S3, while metadata is stored on POSIX. See the xref:deployment/storage/s3.adoc[S3] documentation for more details.

{empty}

Path for System Data::
The environment variable `OCIS_BASE_DATA_PATH` sets the base path in a generic way. It has a xref:default-location[default location] but can also be manually defined. It is the root for many services which automatically add a subdirectory to that root for storing their data. Some services can manually define that path if necessary. Defining them independently can be required like when using a xref:deployment/container/orchestration/orchestration.adoc[Container Orchestration] setup or recommended for using the xref:{s-path}/search.adoc[search service] or xref:{s-path}/thumbnails.adoc[thumbnails service].

// ocis/services$ grep -r 'OCIS_BASE_DATA_PATH' --include=*.go **/pkg/config
// https://docs.asciidoctor.org/asciidoc/latest/subs/apply-subs-to-blocks/

[#services_using_base_path]
Services That Can Deviate from the Base Data Path::
The following environment variables can overwrite the base data path if required:
+
--
[source,subs="+callouts,macros,attributes+"]
----
• xref:{s-path}/auth-basic.adoc[OCIS_LDAP_CACERT;AUTH_BASIC_LDAP_CACERT, window=_blank]
• xref:{s-path}/graph.adoc[OCIS_LDAP_CACERT;GRAPH_LDAP_CACERT, window=_blank]
• xref:{s-path}/groups.adoc[OCIS_LDAP_CACERT;GROUPS_LDAP_CACERT, window=_blank]
• xref:{s-path}/idm.adoc[IDM_LDAPS_CERT, window=_blank]
• xref:{s-path}/idm.adoc[IDM_LDAPS_KEY, window=_blank]
• xref:{s-path}/idm.adoc[IDM_DATABASE_PATH, window=_blank]
• xref:{s-path}/idp.adoc[IDP_ENCRYPTION_SECRET_FILE, window=_blank]
• xref:{s-path}/idp.adoc[IDP_SIGNING_PRIVATE_KEY_FILES, window=_blank]
• xref:{s-path}/idp.adoc[IDP_TRANSPORT_TLS_CERT, window=_blank]
• xref:{s-path}/idp.adoc[IDP_TRANSPORT_TLS_KEY, window=_blank]
• xref:{s-path}/nats.adoc[NATS_NATS_STORE_DIR, window=_blank]
• xref:{s-path}/nats.adoc[NATS_TLS_CERT, window=_blank]
• xref:{s-path}/nats.adoc[NATS_TLS_KEY, window=_blank]
• xref:{s-path}/ocm.adoc[OCM_OCM_INVITE_MANAGER_JSON_FILE, window=_blank]
• xref:{s-path}/ocm.adoc[OCM_OCM_PROVIDER_AUTHORIZER_PROVIDERS_FILE, window=_blank]
• xref:{s-path}/ocm.adoc[OCM_OCM_CORE_JSON_FILE, window=_blank]
• xref:{s-path}/ocm.adoc[OCM_OCM_SHAREPROVIDER_JSON_FILE, window=_blank]
• xref:{s-path}/proxy.adoc[PROXY_TRANSPORT_TLS_KEY, window=_blank]
• xref:{s-path}/search.adoc[SEARCH_ENGINE_BLEVE_DATA_PATH, window=_blank] <1>
• xref:{s-path}/settings.adoc[SETTINGS_DATA_PATH, window=_blank]
• xref:{s-path}/sharing.adoc[SHARING_USER_JSON_FILE, window=_blank]
• xref:{s-path}/sharing.adoc[SHARING_PUBLIC_JSON_FILE, window=_blank]
• xref:{s-path}/store.adoc[STORE_DATA_PATH, window=_blank]
• xref:{s-path}/storage-system.adoc[STORAGE_SYSTEM_OCIS_ROOT, window=_blank]
• xref:{s-path}/storage-users.adoc[STORAGE_USERS_OCIS_ROOT, window=_blank]
• xref:{s-path}/storage-users.adoc[STORAGE_USERS_S3NG_ROOT, window=_blank]
• xref:{s-path}/storage-users.adoc[STORAGE_USERS_OWNCLOUDSQL_DATADIR, window=_blank]
• xref:{s-path}/storage-users.adoc[STORAGE_USERS_OWNCLOUDSQL_UPLOADINFO_DIR, window=_blank]
• xref:{s-path}/thumbnails.adoc[THUMBNAILS_FILESYSTEMSTORAGE_ROOT, window=_blank] <1>
• xref:{s-path}/users.adoc[OCIS_LDAP_CACERT;USERS_LDAP_CACERT, window=_blank]
----
<1> Note that it is recommended for these services to configure an individual path due to expected higher data quantities on larger installations, see the important note on possible impacts below.
--

==== Default Location

* The base path has a default location for metadata and service dependent data (xref:#services_using_base_path[see above]) which *must be* on a POSIX storage. If not otherwise defined when using xref:deployment/storage/s3.adoc[S3], it is also used to store blobs using that path:

** For container images (inside the container) +
`/var/lib/ocis`

** For binary releases +
`$HOME/.ocis/`
+
[NOTE]
====
* Do not replace `$HOME` with `~` (tilde).
** The code does not resolve `~` to the users home directory.

* Check that `$HOME` resolves to a valid directory.
** When using a system user for the runtime, which has no login and therefore no home directory, like in the generic binary setup scenario xref:depl-examples/bare-metal.adoc#setup-the-systemd-service[Setup the systemd Service] or in the deployment example xref:depl-examples/small-scale.adoc[Small-Scale with systemd], you *must* specify a base directory location because a system user has no logon and therefore no home directory!
====

* You can deviate from the default location and define a custom base directory on startup using the environment variable `OCIS_BASE_DATA_PATH`.

* More Important Notes
+
--
IMPORTANT: When setting the base directory manually, it will be used automatically for the xref:#services_using_base_path[services described above] - if they are not otherwise manually defined. 

WARNING: The location must be used by Infinite Scale exclusively. Writing into this location not using Infinite Scale is discouraged to avoid any unexpected behavior. 
--

=== Using S3 for Blobs

When using S3 for storing user data (blobs), metadata must reside on POSIX. The environment variable responsible for storaing metadata in S3 is `STORAGE_USERS_S3NG_ROOT` and derives, if not otherwise defined, from the base directory `OCIS_BASE_DATA_PATH`. For more details see the section xref:base-data-directory[Base Data Directory] above.

Read the xref:deployment/storage/s3.adoc[S3] documentation for more details on how to configure Infinite Scale for the with S3.

== Initialize Infinite Scale

Infinite Scale can be run by manually defining the environment like you do when using xref:deployment/container/orchestration/orchestration.adoc[Container Orchestration]. When using the xref:depl-examples/minimal-bare-metal.adoc[Minimal Bare Metal Deployment] or the xref:deployment/container/container-setup.adoc[Container Setup], you can prepare Infinite Scale for further configuration and recurring starts. After reading xref:deployment/general/ocis-init.adoc[The ocis init Command] for important details, start the initialization. To do so, run:

[source,bash]
----
ocis init
----

You can add command line parameters. To see which ones are available, type:

[source,bash]
----
ocis init --help
----

Command line parameters are beneficial if you e.g. want to hand over all necessary parameters without getting to any questionnaire or if you want to define the admin password yourself not getting a random one assigned.

IMPORTANT: The command line option `--force-overwrite` is only intended for developer usage. If you set this option, your config will be overwritten, your data, if any is present, will persist, but it will not be accessible anymore. This is, among other things, because the issuer (short _iss_ part of openID Connect) will be overwritten.

To reinitialize Infinite Scale, you have to delete your config and your data and start from scratch.

== Start Infinite Scale With All Predefined Services

When you type `ocis server`, the embedded supervisor is automatically used and starts available predefined services automatically. The supervisor starts by default on port 9250 and listens for commands regarding the lifecycle of the supervised services.

To list the started predefined services, type:

[source,bash]
----
ocis list
----

This will print an output like:

[source,plaintext]
----
+--------------------+
|      SERVICE       |
+--------------------+
| app-provider       |
| app-registry       |
| auth-basic         |
| auth-machine       |
| auth-service       |
| clientlog          |
| eventhistory       |
| frontend           |
| gateway            |
| graph              |
| groups             |
| idm                |
| idp                |
| nats               |
| notifications      |
| ocdav              |
| ocm                |
| ocs                |
| postprocessing     |
| proxy              |
| search             |
| settings           |
| sharing            |
| sse                |
| storage-publiclink |
| storage-shares     |
| storage-system     |
| storage-users      |
| thumbnails         |
| userlog            |
| users              |
| web                |
| webdav             |
| webfinger          |
+--------------------+
----

=== Starting Infinite Scale With Environment Variables

You can use environment variables to define or overwrite config parameters which will be used when starting Infinite Scale like:

[source,bash]
----
PROXY_HTTP_ADDR=0.0.0.0:5555 ocis server
----

or when using multiple environment variables like:

[source,bash]
----
PROXY_HTTP_ADDR=0.0.0.0:5555 \
PROXY_DEBUG_ADDR=0.0.0.0:6666 \
ocis server
----

=== Globally Shared Logging Values

When running in supervised mode (`ocis server`), it is beneficial to have common values for logging so that the log output is correctly formatted or everything is piped to the same file without duplicating config keys and values all over the place. This is possible using the global log config key with the following example:

.ocis.yaml
[source,yaml]
----
log:
  level: error
  color: true
  pretty: true
  file: /var/tmp/ocis_output.log
----

NOTE: In case of a service overwriting its shared logging config received from the main ocis.yaml file, you must specify *all* values.

==== Log Config Keys

These are the necessary log keys and the available values:

[source,yaml]
----
log:
  level:  [ error | warning | info | debug ]
  color:  [ true | false ]
  pretty: [ true | false ]
  file:   [ path/to/log/file ] # MUST not be used with pretty = true
----

== Configurations to Access the Web UI

You can easily access Infinite Scale via ownCloud Web with minimal configuration needs. Without going into too much detail, you need to provide the following two environment variables. See also the section about xref:handling-certificates[] and xref:demo-users-and-groups[].

OCIS_URL::
+
--
Expects a URL including _protocol_, _host_ and optionally _port_ to simplify configuring all the different services. Other service xref:deployment/services/env-vars-special-scope.adoc[environment variables] also using an URL still take precedence if set, but will fall back to this URL if not set.

NOTE: If you need to access Infinite Scale running on a VM or a remote machine via a host name other than localhost or in a container, you *must* configure the host name with `OCIS_URL`. The same applies if you are not using host names but an IP address (e.g. 192.168.178.25) instead.

NOTE: By default, Infinite Scale enforces https for web and client access. If necessary, this can be changed in particular setups to http, which is *not* recommended for production. For details see xref:deployment/services/tls.adoc#tls-for-the-http-frontend[TLS for the HTTP Frontend] and xref:deployment/services/s-list/proxy.adoc#special-settings[Proxy Service Configuration].

include::partial$multi-location/idm-https-reverse-proxy.adoc[]
--

PROXY_HTTP_ADDR::
When using `0.0.0.0:9200`, the proxy will listen to all available interfaces. If you want or need to change that based on your requirements, you can use a different address e.g. to bind the proxy to an interface.

IMPORTANT: The bind address for `PROXY_HTTP_ADDR` must be on the same interface where the configured URL from the `OCIS_URL` environment variable is reachable. 

.Common reasons binding to a particular IP address
{empty}
--
* Multiple network interfaces configured for specific tasks like web, storage, administration.
* Binding SSL certificates to IP addresses.
* ...
--

.Examples
{empty}
--
* `PROXY_HTTP_ADDR=127.0.0.0:9200` +
This causes Infinite Scale to *only* bind to the local network interface.
* `PROXY_HTTP_ADDR=0.0.0.0:9200` +
This tells Infinite Scale to bind it to *all* available network interfaces.
--

Also see the xref:deployment/general/general-info.adoc#using-the-embedded-idp-service[Using the Embedded IDP Service] for configuration notes.

=== Handling Certificates

Certificates are necessary to secure browser access. Infinite Scale can run with embedded self-signed certificates mainly used for testing purposes or signed certificates provided by the admin. To tell Infinite Scale which kind of certificates you are using, the environment variable `OCIS_INSECURE` is used.

[NOTE]
====
* When clients have direct access to the Infinite Scale instance:
** Use signed certificates, see below.
** When using unsigned certificates, _depending on the browser used_, errors may get logged like: +
`TLS handshake error from IP:PORT: remote error: tls: unknown certificate`
* When using a reverse proxy:
** Browser access terminates at the webserver and certificates are handled there.
** You can additionally secure the communication using (un)signed certificates for communication between the reverse proxy and infinite Scale.
====

=== Embedded Self-Signed Certificates

In order to run Infinite Scale with automatically generated and self-signed certificates, set `OCIS_INSECURE=true`.

[source,bash]
----
OCIS_INSECURE=true \
PROXY_HTTP_ADDR=0.0.0.0:9200 \
OCIS_URL=https://localhost:9200 \
ocis server
----

=== Provided Signed Certificates

==== Self-Signed Certificates

If your certificates are self-signed, set `OCIS_INSECURE=true` like in the example of embedded self-signed certificates above.

==== Certificates Signed by a Trusted CA

If you have your own certificates already in place, make Infinite Scale use them by adding the following environment variables to the command. Replace the certificates path and file names according to your needs:

[source,bash]
----
OCIS_INSECURE=false \
PROXY_HTTP_ADDR=0.0.0.0:9200 \
OCIS_URL=https://localhost:9200 \
PROXY_TRANSPORT_TLS_KEY=./certs/your-host.key \
PROXY_TRANSPORT_TLS_CERT=./certs/your-host.crt \
ocis server
----

== Default Users and Groups

Default users and groups are only created when you initialize Infinite Scale as first task. The same is true for demo users and groups which need an environment variable to be set _on initializing Infinite Scale_ to get created.

NOTE: If you have not declared demo user creation during initializing, you can for the time being only empty the xref:base-data-directory[Base Data Directory] and remove the xref:configuration-rules[ocis.yaml] file which resets the system. Then you can start from scratch and enable demo user creation.

// fixme: the current implementation of the bootstrap creates the admin user and if set the demo users and adds them to the idm/boltdb file, see the idm service. BUT if you have started ocis without demo user creation, you cant let ocis create them POST first start... https://github.com/owncloud/ocis/issues/3593 

=== Admin User

An admin user will be created when running the `ocis init` command with the following credentials:

[caption=]
.Admin user and group created on first ocis start
[width="100%",cols="25%,70%,45%,25%,25%",options="header"]
|===
| Username
| Password
| Email
| Role
| Group

| admin
| Printed by the output of `ocis init`
| \admin@example.org
| admin
| users
|===

Login to the webinterface with this admin user and change relevant data according your needs or create new users. As an example to reach out the webinterface use `\https://localhost:9200`.

=== Password Reset for the Admin User

The admin password can be reset via command line if it has been forgotten and the admin can't enter the webUI anymore. Note that the admin user must already exist which happens if you have xref:deployment/general/ocis-init.adoc[initialized Infinite Scale].

After running the respective command and entering a new password, the admin can relogin using the new password.

Note that when Infinite Scale gets initialized with xref:deployment/general/ocis-init.adoc[The ocis init Command], an admin password is created and stored in the `ocis.yaml` file. The lifespan of this admin password is up to the point when it either gets changed in the webUI or via the resetpassword command. Any admin password changes are NOT written back to the `ocis.yaml` file nor manual changes to the `admin_password` are considerd as a new password.

[source,yaml]
----
idm:
  service_user_passwords:
    admin_password: ....
    idm_password: ....
    ...
----

[NOTE]
====
To reset the admin password, you either must:

* Shutdown Infinite scale if you are using the binary setup.
* Stop the container if you are using a docker setup.
* Stop the xref:{s-path}/idm.adoc[IDM] service if you are using a orchestrated setup.

This is because the IDM service needs exclusive access to particular backend information. If the IDM service is running, an error message will be logged and the admin password can't be changed.
====

==== Binary Setup

Run the following command to reset the admin password:

[source,bash]
----
ocis idm resetpassword
----

==== Container and Orchestrated Setup

The use of `sudo` depends on if docker has been setup rootless or not.

Replace the following placeholders according your setup:

* `<ocis-path>` +
This is the local path the where Infinite Scale stores all data except the configuration.

* `<ocis-config-path>` +
This is the local path where the Infinite Scale configuration is stored. 

* `<ocis-version>` +
The Infinite Scale version used like `latest` or `{compose_version}` or ... .

[source,bash]
----
sudo docker run -it \
  -v <ocis-path>:/var/lib/ocis \
  -v <ocis-config-path>/config:/etc/ocis \
  owncloud/ocis:<ocis-version> idm resetpassword
----

Note that depending on your setup, you can add `--rm` to your `docker run` command which removes the container afterwards.

=== Demo Users and Groups

==== Create Demo Users and Groups

// https://owncloud.dev/ocis/getting-started/index
// https://owncloud.dev/ocis/getting-started/demo-users/

WARNING: You can let Infinite Scale create demo users and groups for testing purposes. Because these demo users and groups can be a significant security issue, _you should remove them before going into production or your system is exposed to the outside world_, for details see xref:deployment/security/security.adoc[Securing Infinite Scale].

To let Infinite Scale create these demo users and groups for you, start the _runtime_ the very first time with:

[source,bash]
----
IDM_CREATE_DEMO_USERS=true \
ocis init
----

include::partial$deployment/demo_user_table.adoc[]

You can now login with one of the demo users created using the `OCIS_URL` in you browser like `\https://localhost:9200`. 

=== Manage Users and Groups

If you have enabled demo users and groups and you want to manage or delete them, use the web UI, e.g. `\https://localhost:9200`.

== Default Ports

See xref:deployment/services/ports-used.adoc[Used Port Ranges] at the _Services_ description for details.

== Logging

See xref:deployment/services/logging.adoc[Logging] at the _Services_ description for details.

== Using the Embedded IDP Service

See the xref:{s-path}/proxy.adoc#special-settings[Special Settings] section in the Proxy service for configuration details when using the Infinite Scale xref:{s-path}/idp.adoc[IDP service] instead of an external IDP.

== Using a Reverse Proxy

If you are using a reverse proxy like Traefik and the reverse proxy manages the certificates to secure the client access, you can use extra certificates between the proxy and Infinite Scale, although this is not mandatory. See the section xref:handling-certificates[Handling Certificates] for more details.

include::partial$multi-location/idm-https-reverse-proxy.adoc[]

== Maintenance Commands

There are multiple commands available to maintain the Infinite Scale instance. See the xref:maintenance/commands/commands.adoc[Maintenance Commands] document for more details.
