= General Info
:toc: right

:description: This document covers general aspects of Infinite Scale like start modes, services, important minimum configuration etc. for a common understanding.

== Introduction

{description}

We highly recommend to read this document first before you start setting up your system.

The example commands shown need to be adjusted depending on whether you are using the xref:deployment/binary/binary-setup.adoc[Binary Setup] or a xref:deployment/container/container-setup.adoc[Container Setup].

When using global options on startup, you can always use command line options or environment variables. Run `ocis help` and see xref:starting-infinite-scale-with-environment-variables[] for details.

== Embedded Supervisor (Runtime)

Infinite Scale has an xref:architecture/architecture.adoc#infinite-scale-microservice-runtime[embedded supervisor] for managing the runtime and reducing the memory footprint. In addition, this supervisor takes care that a service will be restarted automatically if it fails. When using an external supervisor like systemd, Kubernetes or others, the embedded supervisor is not needed.

== Deciding the Startup Mode

The following two mode types do not predefine a particular installation method like the manual or container setup. When using Kubernetes, the embedded supervisor is not necessary, the supervisor of the underlying system is used.

Starting Infinite Scale using the embedded supervisor::
This mode can be used when scaling is not the primary focus and can be the case if you have a:
* when you do testing and/or development
* small productive environment (xref:availability_scaling/availability_scaling.adoc#single-server-setup[Single Server Setup]) or 

Starting Infinite Scale in unsupervised mode::
This mode is used when _availability, scaling and the adjustment to dynamically changing requirements_ have a xref:availability_scaling/availability_scaling.adoc#deployment-evolution[high priority]. In this case, an external supervisor like Kubernetes is used to deploy and run Infinite Scale with its services.

== Start Infinite Scale With All Predefined Services

When you type `ocis server`, the embedded supervisor is automatically used and starts available predefined services automatically. The supervisor starts by default on port 9250 and listens for commands regarding the lifecycle of the supervised services.

To list the started predefined services, type:

[source,bash]
----
ocis list
----

This will print an output like:

[source,plaintext]
----
+--------------------+
|      SERVICE       |
+--------------------+
| app-provider       |
| app-registry       |
| auth-basic         |
| auth-bearer        |
| auth-machine       |
| frontend           |
| gateway            |
| graph              |
| graph-explorer     |
| groups             |
| idm                |
| idp                |
| nats               |
| notifications      |
| ocdav              |
| ocs                |
| proxy              |
| search             |
| settings           |
| sharing            |
| storage-publiclink |
| storage-shares     |
| storage-system     |
| storage-users      |
| store              |
| thumbnails         |
| users              |
| web                |
| webdav             |
+--------------------+
----

== Managing Services

Services are built as microservices which can be started, stopped or instantiated. An xref:deployment/services/services_rules.adoc[Services Rules] documentation as been added to explain some background. Please read this carefully to avoid unwanted behavior. For details of each service see the xref:deployment/services/services.adoc[Services] documentation.

=== List Available Services

Just type `ocis` to get a list of commands and available services.

When typing `ocis <service-name> --help`, you will get detailed help regarding the specified service.

=== Manage Instances of Services

==== Infinite Scale Supervised Services

In supervised mode, all services are started with one command as you can see below in the example when using the binary setup. Note that the services started with the runtime share the same PID.

Start the Infinite Scale Runtime::

[source,bash]
----
ocis server
----

List running services::

[source,bash]
----
ocis list
----

Stopping the Infinite Scale Runtime::
In supervised mode, you have to stop the `ocis server` which also stops all services. See xref:deployment/binary/binary-setup.adoc#stopping-infinite-scale[Stopping Infinite Scale] for more details.

==== Unsupervised Services

At any time, you can create unsupervised instances of a service with `ocis [service-name] server`, for example `ocis proxy server`. _These services are independent of services in supervised mode and have their own PID_. The Instances are managed with classic OS methods or e.g. via Kubernetes.

Note that you need configuration for and access to the service instances like with a load balancer when you scale.

=== Configuring Services

To configure services, see the section xref:deployment/services/services.adoc[Services] in the _Deployment_ documentation.

== Configuration Rules

// taken from: https://owncloud.dev/ocis/config/

NOTE: Administrators must be aware of the sources, the location and order applied (the _configuration file arithmetics_). Mismanaging them can be a source of confusion leading to undesired results on the final configuration created and applied.

. Infinite Scale uses a hierarchical structure for its configuration, *where each element overwrites its precedent*. These are:
+
.. Environment variables
.. Services configuration file
.. Infinite Scale configuration file

. The default locations for config files are:
+
* For container images (inside the container) +
`/etc/ocis/`
+
* For binary releases +
`$HOME/.ocis/config/`
+
NOTE: You can deviate from the default location and define a custom configuration file location on startup using the environment variable `OCIS_CONFIG_FILE`.
+
NOTE: When using a system user for the runtime which has no login and therefore no home directory like when used xref:deployment/binary/binary-setup.adoc#setting-up-systemd-for-infinite-scale[Setting up systemd for Infinite Scale], you _must_ specify a configuration file location.

=== Configuration File Naming

The configuration files for Infinite Scale are YAML-based (a human-friendly data serialization language).

The filename to define a config has the following namespace:

[source,plaintext]
----
ocis.yaml
 or
[services name].yaml
----

You can list the possible services names by typing:

[source,bash]
----
ocis list
----

=== Starting Infinite Scale With Environment Variables

You can use environment variables to define or overwrite config parameters which will be used when starting Infinite Scale like:

[source,bash]
----
PROXY_HTTP_ADDR=localhost:5555 ocis server
----

or when using multiple environment variables like:

[source,bash]
----
PROXY_HTTP_ADDR=localhost:5555 \
PROXY_DEBUG_ADDR=localhost:6666 \
ocis server
----

=== Globally Shared Logging Values

When running in supervised mode (`ocis server`), it is beneficial to have common values for logging so that the log output is correctly formatted or everything is piped to the same file without duplicating config keys and values all over the place. This is possible using the global log config key with the following example:

.ocis.yaml
[source,yaml]
----
log:
  level: error
  color: true
  pretty: true
  file: /var/tmp/ocis_output.log
----

NOTE: In case of a service overwriting its shared logging config received from the main ocis.yaml file, you must specify *all* values.

==== Log Config Keys

These are the necessary log keys and the available values:

[source,plaintext]
----
log:
  level: [ error | warning | info | debug ]
  color: [ true | false ]
  pretty: [ true | false ]
  file: [ path/to/log/file ] # MUST not be used with pretty = true
----

== Configurations to Access the WebUI

You can easily access Infinite Scale via ownCloud Web with minimal configuration needs. Without going into too much detail, you need to provide the following two environment variables. See also the section about xref:handling-certificates[] and xref:demo-users-and-groups[].

OCIS_URL::
Expects a URL including _protocol_, _host_ and optionally _port_ to simplify configuring all the different services. Other service environment variables also using an URL still take precedence if set, but will fall back to this URL if not set.
+
NOTE: If you need to access Infinite Scale running on a VM or a remote machine via a host name other than localhost or in a container, you need to configure the host name with `OCIS_URL`. The same applies if you are not using host names but an IP address (e.g. 192.168.178.25) instead.

PROXY_HTTP_ADDR::
When using `0.0.0.0:9200`, the proxy will listen to all available interfaces. If you want or need to change that based on your requirements, you can use a different address e.g. to bind the proxy to an interface. 

// fixme: explain the proxy - but on a different page.

=== Handling Certificates

// https://owncloud.dev/ocis/deployment/basic-remote-setup/

Certificates are necessary to secure browser access. Infinite Scale can run with embedded self-signed certificates mainly used for testing purposes or signed certificates provided by the admin. To tell Infinite Scale which kind of certificates you are using, the environment variable `OCIS_INSECURE` is used.

=== Embedded Self-Signed Certificates

In order to run Infinite Scale with automatically generated and self-signed certificates, set `OCIS_INSECURE=true`.

[source,bash]
----
OCIS_INSECURE=true \
PROXY_HTTP_ADDR=0.0.0.0:9200 \
OCIS_URL=https://localhost:9200 \
ocis server
----

=== Provided Signed Certificates

==== Self-Signed Certificates

In case your certificates are self-signed, set `OCIS_INSECURE=true` like in the example of embedded self-signed certificates above.

==== Certificates Signed by a Trusted CA

If you have your own certificates already in place, make Infinite Scale use them by adding the following environment variables to the command. Replace the certificates path and file names according to your needs:

[source,bash]
----
OCIS_INSECURE=false \
PROXY_HTTP_ADDR=0.0.0.0:9200 \
OCIS_URL=https://localhost:9200 \
PROXY_TRANSPORT_TLS_KEY=./certs/your-host.key \
PROXY_TRANSPORT_TLS_CERT=./certs/your-host.crt \
ocis server
----

== Define the Infinite Scale Data Path

Because Infinite Scale does not use a database for storing information like users, groups, spaces, internal data, etc., it saves all this data to a permanent file location. This location is also used for storing user-generated data and must be a supported filesystem as described in xref:prerequisites/prerequisites.adoc#filesystems-and-shared-storage[Filesystems and Shared Storage].

The environment variable used to define this path is `OCIS_BASE_DATA_PATH`.

The following rules apply:

* If you do NOT define this environment variable, the following applies:
** The base path is by default `$HOME/.ocis/` after performing a _manual setup_.
** The base path is by default `/var/lib/ocis` inside the container when using the _container setup_.
* The directory must exist and the user used for Infinite Scale must have full access and permissions.

NOTE: You must set this environment variable to a valid path when using the manual installation having a system user for Infinite Scale, because a system user has no logon and therefore no home directory!

WARNING: The location must exclusively be used by Infinite Scale. Writing into this location not using Infinite Scale is strictly discouraged to avoid any unexpected behaviour. 

== Initialize Infinite Scale

To prepare Infinite Scale for further configuration and recurring starts, you have to initialize it first. To do so, run:

[source,bash]
----
ocis init
----

You can add command line parameters. To see which ones are available, type:

[source,bash]
----
ocis init --help
----

Command line parameters are beneficial if you e.g. want to hand over all necessary parameters without getting to any questionnaire or if you want to define the admin password yourself not getting a random one assigned.

IMPORTANT: The command line option `--force-overwrite` is only intended for developer usage. If you set this option, your config will be overwritten, your data, if any is present, will persist, but it will not be accessible anymore. This is, among other things, because the issuer (short _iss_ part of openID Connect) will be overwritten.

To reinitialize Infinite Scale, you have to delete your config and your data and start from scratch.

== Default Users and Groups

Default users and groups are only created when you initialize Infinite Scale as first task. The same is true for demo users and groups which need an environment variable to be set _on initializing Infinite Scale_ to get created.

NOTE: If you have not declared demo user creation during initializing, you can for the time being only empty the xref:define-the-infinite-scale-data-path[Infinite Scale base directory] and remove the xref:configuration-rules[ocis.yaml] file which resets the system. Then you can start from scratch and enable demo user creation.

// fixme: the current implementation of the bootstrap creates the admin user and if set the demo users and adds them to the idm/boltdb file, see the idm service. BUT if you have started ocis without demo user creation, you cant let ocis create them POST first start... https://github.com/owncloud/ocis/issues/3593 

=== Admin User

An admin user will be created when running the `ocis init` command with the following credentials:

[caption=]
.Admin user and group created on first ocis start
[width="100%",cols="25%,70%,45%,25%,25%",options="header"]
|===
| Username
| Password
| Email
| Role
| Group

| admin
| Printed by the output of `ocis init`
| \admin@example.org
| admin
| users
|===

Login to the webinterface with this admin user and change relevant data according your needs or create new users. As an example to reach out the webinterface use `\https://localhost:9200`.

=== Demo Users and Groups

==== Create Demo Users and Groups

// https://owncloud.dev/ocis/getting-started/index
// https://owncloud.dev/ocis/getting-started/demo-users/

WARNING: You can let Infinite Scale create demo users and groups for testing purposes. Because these demo users and groups can be a significant security issue, _you should remove them before going productive or your system is exposed to the outside world_, for details see xref:deployment/security/security.adoc[Securing Infinite Scale].

To let Infinite Scale create these demo users and groups for you, start the _runtime_ the very first time with:

[source,bash]
----
IDM_CREATE_DEMO_USERS=true \
ocis init
----

include::partial$deployment/demo_user_table.adoc[]

You can now login with one of the demo users created using the `OCIS_URL` in you browser like `\https://localhost:9200`. 

=== Manage Users and Groups

If you have enabled demo users and groups and you want to manage or delete them, use the web UI, e.g. `\https://localhost:9200`.

== Using a Reverse Proxy

// https://owncloud.dev/ocis/deployment/ocis_individual_services/

If you are using a reverse proxy like Traefik and the reverse proxy manages the certificates to secure the access, there is no need to use certificates between the reverse proxy and Infinite Scale again. You can therefore set `OCIS_INSECURE=false` or remove it completely. Also see: xref:handling-certificates[Handling Certificates].

== Manage Unfinished Uploads

See xref:deployment/services/storage-users.adoc#manage-unfinished-uploads[Manage Unfinished Uploads] at the _Storage Users_ service for details. 
