= General Info
:toc: right

:description: This document covers general aspects of oCIS like start modes, extensions, important minimum configuration etc. for a common understanding.

== Introduction

{description}

The example commands shown need to be adjusted depending on whether you are using the manual installation or a docker environment. See the xref:deployment/manual/manual-setup.adoc[Manual Setup] and the xref:deployment/docker/docker-setup.adoc[Docker Setup] for more details.  

When using global options on startup, you can always use command line options or environment variables. Run `ocis --help` and see xref:starting-ocis-with-environment-variables[] for details.

== Embedded Supervisor (Runtime)

oCIS has an xref:architecture/index.adoc#ocis-microservice-runtime[embedded supervisor] for managing the runtime und reducing the memory footprint. In addition, this supervisor takes care that an extension will be restarted automatically if it fails. When using an external supervisor like systemd, Kubernetes or others, the embedded supervisor is not needed.

== Deciding the Startup Mode

The following two mode types do not predefine a particular installation method like the manual or docker installation. When using Kubernetes, the embedded supervisor is not necessary, the supervisor of the underlaying system is used.  

Starting oCIS using the embedded supervisor::
This mode can be used when scaling is not the primary focus and can be the case if you have a:
* small productive environment (xref:availability_scaling/index.adoc#single-server[Single Server Setup]) or 
* when you do testing and/or development

Starting oCIS in unsupervised mode::
This mode is used when _availability, scaling and the adjustment to dynamically changing requirements_ have a xref:availability_scaling/index.adoc#deployment-evolution[high priority]. In this case, an external supervisor like Kubernetes is used to deploy and run oCIS with its extensions.

== Start oCIS With All Predefined Extensions

When you type `ocis server`, the embedded supervisor is automatically used and starts available predefined extensions automatically. The supervisor starts on port 9250 (by default) and listens for commands regarding the lifecycle of the supervised extensions.

To list the started predefined extensions, type:

[source,bash]
----
ocis list
----

This will print an output like:

[source,plaintext]
----
+------------------------+
|       EXTENSION        |
+------------------------+
| accounts               |
| glauth                 |
| graph                  |
| graph-explorer         |
| idp                    |
| ocs                    |
| onlyoffice             |
| proxy                  |
| settings               |
| storage-authbasic      |
| storage-authbearer     |
| storage-frontend       |
| storage-gateway        |
| storage-groupsprovider |
| storage-home           |
| storage-metadata       |
| storage-public-link    |
| storage-sharing        |
| storage-users          |
| storage-users-provider |
| store                  |
| thumbnails             |
| web                    |
| webdav                 |
+------------------------+
----

== Managing Extensions

=== List Available Extensions

Type `ocis --help` to get a list of available extensions.

=== Manage Instances of Extensions

==== oCIS Supervised Extensions

You can start, list or kill available extensions in supervised mode with the `ocis` command. _These extensions share the same PID_. To manage supervised extensions, you need to run `ocis server` first or an error will be thrown.

[NOTE]
====
When an extension runs supervised, is killed and started again, the only way to provide or overwrite configuration values will be through an *extension config file*. This is because the parent process has already started in its own environment with the configuration already loaded. See the example below:

[source,bash]
----
ocis run proxy --config-file=/path/proxy.yaml
----
====

NOTE: This configuration file must contain *ALL* configuration details as no xref:configuration-of-ocis[configuration arithmetics] is applied. 

List running extensions::
[source,bash]
----
ocis list
----

Kill a running extension::
[source,bash]
----
ocis kill [extension name]
----

Start an extension::
[source,bash]
----
ocis run [extension name]
----

==== Unsupervised Extensions

At any time, you can create unsupervised instances of an extension with `ocis [extension name]`, for example `ocis proxy`. _These extensions are independent of extensions in supervised mode and have their own PID_. The Instances are managed with classical OS methods or e.g. via Kubernetes.

Creating multiple instances of an extension is used for scaling. Note that you may need configuration for and access to the extension instances like with a load balancer when you scale.

== Default Runtime Error Response

If you have not started up `ocis server` but try to file a runtime command except `run` and `version`, a default error message like the following will be printed:

[source,plaintext]
----
Failed to connect to the runtime. Has the runtime been started and did you configure the right runtime address (localhost:9200)?
----

To fix this, start the runtime with `ocis server` first and redo the command.

== Configuration of oCIS

// taken from: https://owncloud.dev/ocis/config/

oCIS uses a hierachical structure for its configuration, *where each element overwrites its precedent*. These are:

. Environment variables
. Extension configuration file
. oCIS configuration file

The expected locations are:

. `$HOME/.ocis/config/`
. `/etc/ocis/`
. `.config/`

// fixme: this is according to willy going to be changed. There should a PR in ocis coming and we will get notified (hopefully). 

You can define a nonstandard configuration file location on startup either with an:

* command option (`--config-file value`) or with an
* environment variable (`OCIS_CONFIG_FILE`)

NOTE: Administrators must be aware of these sources and the order applied (the _configuration file arithmetics_). Mismanaging them can be a source of confusion leading to undesired results on the final configuration created and applied.

=== Configuration File Naming

The configuration files for oCIS are YAML-based (a human-friendly data serialization language).

The filename to define a config has following namespace:

[source,plaintext]
----
ocis.yaml
 or
[extension name].yaml
----

You can list the possible extension names by typing:

[source,bash]
----
ocis list
----

=== Starting oCIS With Environment Variables

You can use environment variables to define or overwrite config parameters which will be used when starting oCIS like:

[source,bash]
----
PROXY_HTTP_ADDR=localhost:5555 ocis server
----

or when using multiple environment variables like:

[source,bash]
----
PROXY_HTTP_ADDR=localhost:5555 \
PROXY_DEBUG_ADDR=localhost:6666 \
ocis server
----

Remember the note in xref:ocis-supervised-extensions[] when killing/restarting extensions in supervised mode.

=== Globally Shared Logging Values

When running in supervised mode (`ocis server`), it is beneficial to have common values for logging so that the log output is correctly formatted or everything is piped to the same file without duplicating config keys and values all over the place. This is possible using the global log config key with the following example:

.ocis.yaml
[source,yaml]
----
log:
  level: error
  color: true
  pretty: true
  file: /var/tmp/ocis_output.log
----

NOTE: In case of an extension overwriting its shared logging config received from the main ocis.yaml file, you *MUST* specify all values.

==== Log Config Keys

These are the necessary log keys and the available values:

[source,plaintext]
----
log:
  level: [ error | warning | info | debug ]
  color: [ true | false ]
  pretty: [ true | false ]
  file: [ path/to/log/file ] # MUST not be used with pretty = true
----

== Accessing oCIS Via the WebUI

You can easily access oCIS via ownCloud Web with minimal configuration needs. Without going into too much detail, you need to provide the following two environment variables. See also the section about xref:handling-certificates[] and xref:login-with-demo-users[].

OCIS_URL::
Expects a URL including _protocol_, _host_ and optionally _port_ to simplify configuring all the different services. Other extension environment variables also using an URL still take precedence if set, but will fall back to this URL if not set.
+
NOTE: If you need to access oCIS running in a docker container, on a VM or a remote machine via a host name other than localhost, you need to configure the host name with `OCIS_URL`. The same applies if you are not using host names but an IP address (e.g. 192.168.178.25) instead.

PROXY_HTTP_ADDR::
When using `0.0.0.0:9200`, the proxy will listen to all available interfaces. If you want or need to change that based on your requirements, you can use a different address e.g. to bind the proxy to an interface. 

// fixme: explain the proxy - but on a different page.

== Handling Certificates

// https://owncloud.dev/ocis/deployment/basic-remote-setup/

Certificates are necessary to secure browser access. oCIS can run with embedded self-signed certificates mainly used for testing purposes or signed certificates provided by the admin. To tell oCIS which kind of certificates you are using, the environment variable `OCIS_INSECURE` is used.

=== Using a Reverse Proxy

// https://owncloud.dev/ocis/deployment/ocis_individual_services/

When using a reverse proxy like Traefik and the reverse proxy manages the certificates, there is no need to use these certificates between the reverse proxy and oCIS again. Therefore set `OCIS_INSECURE=false` or remove it completely.

=== Embedded Self-Signed Certificates

In order to run oCIS with automatically generated and self-signed certificates, set `OCIS_INSECURE=true`.

[source,console]
----
OCIS_INSECURE=true \
PROXY_HTTP_ADDR=0.0.0.0:9200 \
OCIS_URL=https://localhost:9200 \
ocis server
----

=== Provided Signed Certificates

==== Self-Signed Certificates

In case your certificates are self-signed, set `OCIS_INSECURE=true` like in the example of embedded self-signed certificates above.

==== Certificates Signed by a Trusted CA

If you have your own certificates already in place, make oCIS use them by adding the following environment variables to the command. Replace the certificates path and file names according to your needs:

[source,console]
----
OCIS_INSECURE=false \
PROXY_HTTP_ADDR=0.0.0.0:9200 \
OCIS_URL=https://localhost:9200 \
PROXY_TRANSPORT_TLS_KEY=./certs/your-host.key \
PROXY_TRANSPORT_TLS_CERT=./certs/your-host.crt \
ocis server
----

== Login With Demo Users

// https://owncloud.dev/ocis/getting-started/index
// fixme: https://github.com/owncloud/ocis/pull/3474 ([full-ci] set demo users to default off)

With a fresh installation of oCIS, you can log in via the web interface at `\https://localhost:9200` (or the URL you defined) using one of the demo users provided for testing purposes:

[width="70%",cols="30%,30%,60%,30%",options="header"]
|===
| Username
| Password
| email
| Role

| admin
| admin
| \admin@example.org
| admin

| einstein
| relativity
| \einstein@example.org
| user

| marie
| radioactivity
| \marie@example.org
| user

| moss
| vista
| \moss@example.org
| admin

| richard
| superfluidity
| \richard@example.org
| user
|===

NOTE: You should remove these demo users in a productive environment.

== Define the oCIS Data Path

Because oCIS does not use a database for storing information like users, groups, spaces, internal data, etc., it saves all this data to a permanent file location. This location is also used for storing user-generated data and must be a supported filesystem as described in xref:prerequisites/index.adoc#filesystems-and-shared-storage[Filesystems and Shared Storage].

The environment variable used to define this path is `OCIS_BASE_DATA_PATH`.

The following rules apply:

* If you do NOT define this environment variable, the following applies:
** The base path is by default the `home directory` of the user after performing a manual installation.
** The base path is by default `/var/lib/oics` when using the docker installation.
* The directory must exist and the user used for oCIS must have full access and permissions.

NOTE: You must set this environment variable to a valid path when using the manual installation having a system user for oCIS, because a system user has no logon and therefore no home directory!

WARNING: The location used must be exclusively used by oCIS. Writing into this location from outside oCIS is strictly forbidden to avoid any inconsistencies or damages to the oCIS environment. 
