= ownCloud
:toc: right
:toclevels: 3


== Admin Documentation

Before you start reading, if you are interested in:

- learning ocis from an admin perspective,
- different deployment scenarios,
- deployment examples,
- detailed settings and more

we would recommend to continue with the link:https://doc.owncloud.com/ocis/latest/[ownCloud Admin Documentation for Infinite Scale].

== Developer Documentation

Welcome to our developer documentation. Here you find documentation with focus for _developers_:

- xref:./ocis.adoc[oCIS] server
- oCIS Services
- Clients like:
    - link:https://github.com/owncloud/web[ownCloud Web] - the new web frontend for oCIS and ownCloud
    - link:https://github.com/owncloud/android[ownCloud Android app]
    - link:https://github.com/owncloud/ios-app[ownCloud iOS app]
    - link:https://github.com/owncloud/client[ownCloud Desktop Syncing Client]
- Integrations

== We love open source

The oCIS server is Apache v2 licensed.
The lower storage layer of oCIS is defined by the CS3 APIs and implemented in the REVA project. Our goal is to develop the CS3 APIs to an open standard and collaborate on the open source REVA reference implementation for CS3 APIs.

You can also find all client sources on link:https://github.com/owncloud/[GitHub].

== Join the oCIS Community

The link:https://github.com/owncloud/ocis[server repository] on link:https://www.github.com[GitHub] is a good entry point to the oCIS project. In addition to that there are also ownCloud projects for clients for link:https://github.com/owncloud/ios-app[iOS], link:https://github.com/owncloud/android[Android], the major link:https://github.com/owncloud/desktop[Desktop] platforms and link:https://github.com/owncloud/web[ownCloud Web].

To chat about development, join our public chat on link:https://matrix.to/#/#ocis:matrix.org[matrix: ownCloud Infinite Scale].

If you want to help and improve ownCloud or oCIS, start coding or open issues on GitHub in the related repository.

We are very happy to hear your feedback and ideas!
