= Container Orchestration
:toc: right
:toclevels: 3
:description: This document provides guidelines for container orchestration tools suitable for Infinite Scale.

////
on new helmchart releases, check for attributes `no_second_tab` and `no_third_tab` to enable tab rendering.
if all blocks are allowed to be rendered, you can safely remove the attributes and the queries from the block.
////

:docker-compose-url: https://docs.docker.com/get-started/08_using_compose/
:docker-compose-install-url: https://docs.docker.com/compose/install/
:docker-compose-evolution-url: https://docs.docker.com/compose/compose-v2/
:docker-hub-url: https://hub.docker.com/r/owncloud/ocis/tags?page=1&ordering=last_updated
:docker-swarm-url: https://docs.docker.com/engine/reference/commandline/swarm/
:kubernetes-url: https://kubernetes.io
:swarm-v-kub-1-url: https://circleci.com/blog/docker-swarm-vs-kubernetes/#c-consent-modal
:swarm-v-kub-2-url: https://vexxhost.com/blog/kubernetes-vs-docker-swarm-containerization-platforms/
:helm-charts-ocis-url: https://github.com/owncloud/ocis-charts
:download-gh-directory-url: https://download-directory.github.io

:ocis_individual_services-url: https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_individual_services
:ht-pwd-url: https://htpasswdgenerator.de/

:why-K8s-url: https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/#why-you-need-kubernetes-and-what-can-it-do
:eli5-K8s-url: https://dev.to/miguelmota/comment/filh
:wunderlich-K8s-url: http://deaddy.net/introduction-to-kubernetes-pt-1.html

:12factor-url: https://12factor.net/
:K8s-setup-url: https://kubernetes.io/docs/setup/
:helm-install-url: https://helm.sh/docs/intro/install/

:minikube-url: https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/
:minikube-start-url: https://minikube.sigs.K8s.io/docs/start/
:kubeadm-url: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
:kubectl-url: https://kubernetes.io/docs/tasks/tools/
:helm-url: https://helm.sh/
:helm-guide-url: https://helm.sh/docs/intro/install/
:cert-manager-url: https://cert-manager.io/docs/installation/helm/
:ocis-helm-charts-url: https://github.com/owncloud/ocis-charts

:minikube-kubectl-url: https://minikube.sigs.K8s.io/docs/handbook/kubectl/
:kubernetes-pod-url: https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-intro/

:prometheus-operator-url: https://github.com/prometheus-operator/prometheus-operator

// note the attributes `tab_xxx` definition needed for the tab definitions are in antora.yaml

== Introduction

{description}  These are {docker-compose-url}[Docker-Compose] and {kubernetes-url}[Kubernetes]. Other container orchestration tools like {docker-swarm-url}[Docker Swarm] can be derived from these.

Container orchestration tools are necessary to meet the requirements described in the xref:availability_scaling/availability_scaling.adoc#container[Availability and Scalability] guide starting at the _Container_ section.

The pages

* {swarm-v-kub-1-url}[Docker Swarm vs Kubernetes: how to choose a container orchestration tool] and
* {swarm-v-kub-2-url}[Kubernetes Vs. Docker Swarm: A Comparison of Containerization Platforms]

give a brief overview of features and characteristics of both tools.

For Kubernetes, ownCloud provides basic {helm-charts-ocis-url}[Helm Charts] that can be used and adjusted.

IMPORTANT: ownCloud highly recommends reading the xref:deployment/general/general-info.adoc[General Info] as it contains valuable information about configuration rules, managing services and default paths - just to mention some of the useful topics.

== Docker Compose

Similar to using _docker run_ and handing over command-line parameters for a single container, you can use a `docker-compose.yml` yaml file which defines all the settings and environment variables for each container in one or more files. This is the next step when having multi-container environments.

* Consider that when planning to run Infinite Scale via Docker Compose, the degree of freedom is not the same as when using Kubernetes with Helm as you are limited to the same server and other limitations but it usually offers more than running the pure binary when it comes to ease of configuration and maintaining your environment.

* Use Docker Compose if you aim at an extended degree of freedom compared to the binary installation but don't need the full capabilities of Kubernetes and Helm.

=== Prerequisites

Check if the package `docker-compose` is installed in addition to docker:

[source,bash]
----
which docker-compose
----

If `docker-compose` is installed, you'll be informed. If not, you may get no output at all or a message that it couldn't be found. In that case you need to install `docker-compose` first. On most Linux distributions, you can simply use the package manager to do so.

Note that in many cases, this will install a 1.x version (python-based) only supported until June 2023. Version 2.x (go-based) is available from Docker. Follow the {docker-compose-install-url}[Install Docker Compose] guide to install a 2.x version. Familiarize yourself with the {docker-compose-evolution-url}[differences between versions] particularly with regard to syntax changes. Most of our examples are still based on Compose-V1. One major difference is, that compose is now a plugin of docker, even if there is still a standalone version. If the check above fails, you might also want to test:

[source,bash]
----
docker compose version
----

When done, create a project directory like `ocis-compose` in your home directory to have a common location for your Infinite Scale Compose files.

=== Docker Compose Examples

* See the xref:deployment/services/services.adoc[services section] for details about available environment variables and yaml files.

* See below for example service configurations using Docker Compose, to get a first impression of how this can be achieved. Both _ocis environment variables_ and _ocis service configuration_ yaml files are used.
+
[tabs]
====
{compose_tab_1_tab_text}::
+
--
{composer-url}{compose_tab_1}{composer-final-path}[Docker Compose deployment examples directory,window=_blank]

Using git version name: `{compose_tab_1}`
--
====
+
--
Note that github will not let you download a single directory easily. You can get the examples using the following methods requiring minimum space. For stable releases, check or update the version accordingly like when there is a new patch release available:

* Using a shallow git clone which minimizes the required clone space like:
+
[source,bash,subs="attributes+"]
----
git clone --depth 1 https://github.com/owncloud/ocis.git -b {compose_tab_1_tab_text}
----

// https://stackoverflow.com/questions/7106012/download-a-single-folder-or-directory-from-a-github-repo

* Using an external page providing you the folder to download as zip file like:
+
[source,plaintext,subs="attributes+"]
----
{download-gh-directory-url}?url={composer-url}{compose_tab_1}{composer-final-path}
----
--
