////
The attribute 'service_name' (mandatory) and 'no_yaml' (not mandatory) will be handed over by the calling page.
If no_yaml is set, it will exclude rendering yaml files because it does not exist.

Print a dependent explanation line:

* no_yaml is not set = standard service
* no_yaml is set     = special scope envvars

Conditional tab printing, example:

* no_second_tab = based on first appearance of the service (defined in a service),
  must overrule service tab. If there is no second, there is also no third.

* Note to make a tab hidden by no_xxx_tab showing up again, just comment it.

The included deprecation file just has an attribute necessary for rendering deprecations.
This is necessary as attributes that are defined INSIDE a tabset will not get recognized, attributes need to be defined OUTSIDE the tabset definition. example content:

:show-deprecation: true

The file contains the attribute too to be used outside of tabsets.

To exclude a deprecation file if not wanted - like when the file will just not exist, manually unset the attribute if required via:

* :!no_deprecation:

////

////
Important: The xxx_deprecation.adoc does not exist for extended or global envvars. It may change for global envvars! Therefore we need to query 'no_deprecation' to skip importing - or if we explicitly don't want to show deprecated content.
When rendering an included content in a table, any attribute set in the included file is dropped and can't be queried. Therefore we read upfront xxx_deprecation.adoc where only the deprecation state is set. Having this extra, we set 'show-deprecation' outside the tab but with the same value which is taken for building.
////

:show-deprecation: false

ifndef::no_deprecation[]
// deprecation test tab 1, uncomment for testing
include::{ocis-services-raw-url}{service_tab_1}{ocis-services-final-path}adoc/{service_name}_deprecation.adoc[]
endif::no_deprecation[]

// define the text to be printed as tab text for the envvar table in services
// this is only relevant for master as it prints the rolling version additionally
// branched versions are not affected
:tab_text: {service_tab_1_tab_text}
ifeval::["{service_tab_1_tab_text}" == "master"]
:tab_text: {service_tab_1_tab_text} + Rolling {ocis-rolling-version}
endif::[]


// conditionally render the envvar entry text, either with or without section header

// text version 1

ifndef::no_yaml[]
=== Environment Variables

The `{service_name}` service is configured via the following environment variables. Read the xref:deployment/services/envvar-types-description.adoc[Environment Variable Types] documentation for important details.
endif::no_yaml[]

// text version 2

ifdef::no_yaml[]
The `{service_name}` variables are defined in the following way. Read the xref:deployment/services/envvar-types-description.adoc[Environment Variable Types] documentation for important details.
endif::no_yaml[]

// create the tabs in any case

[tabs]
====
{tab_text}::
+
--
include::{ocis-services-raw-url}{service_tab_1}{ocis-services-final-path}adoc/{service_name}_configvars.adoc[]
--
====

ifndef::no_yaml[]
=== YAML Example

* Note that the filename shown below has been chosen on purpose.
* See the xref:deployment/general/general-info.adoc#configuration-file-naming[Configuration File Naming] for details when setting up your own configuration.
* See the xref:deployment/services/env-var-note.adoc[Notes for Environment Variables] if you want to use environment variables in the yaml file.

[tabs]
====
{tab_text}::
+
--
[source,yaml]
----
include::{ocis-services-raw-url}{service_tab_1}{ocis-services-final-path}{service_name}-config-example.yaml[]
----
--
====
endif::no_yaml[]
