////
The attribute 'service_name' (mandatory) and 'no_yaml' (not mandatory) will be handed over by the calling page.
If no_yaml is set, it will exclude rendering yaml files because it does not exist.

Print a dependent explanation line:

* no_yaml is not set = standard service
* no_yaml is set = special scope envvars

Conditional tab printing, example:

* no_second_tab = based on first appearance of the service (defined in a service),
  must overrule service tab. If there is no second, there is also no third.

* use_service_tab_2 = release based (defined in antora.yaml)

*   Note to make a tab hidden by no_xxx_tab showing up again, just comment it.

The included deprecation file just has an attribute necessary for rendering deprecations.
This is necessary as attributes that are defined INSIDE a tabset will not get recognized, attributes need to be defined OUTSIDE the tabset definition. example content:

:show-deprecation: true

The file contains the attribute too to be used outside of tabsets.

To exclude a deprecation file if not wanted - like when the file will just not exist, manually unset the attribute if required via:

* :!no_deprecation:
////

// evaluate deprecations if set in any tab, but only if no_deprecation is not set
// if set, it will show the deprecation table in all tabs, independent if that tab has one or not
ifndef::no_deprecation[]

include::{ocis-services-raw-url}{service_tab_1}{ocis-services-final-path}adoc/{service_name}_deprecation.adoc[]
ifeval::["{show-deprecation}" == "true"]
:has_deprecation_tab_1: true
endif::[]

ifndef::no_second_tab[]
ifdef::use_service_tab_2[]
include::{ocis-services-raw-url}{service_tab_2}{ocis-services-final-path}adoc/{service_name}_deprecation.adoc[]
ifeval::["{show-deprecation}" == "true"]
:has_deprecation_tab_2: true
endif::[]
endif::use_service_tab_2[]

ifndef::no_third_tab[]
ifdef::use_service_tab_3[]
include::{ocis-services-raw-url}{service_tab_3}{ocis-services-final-path}adoc/{service_name}_deprecation.adoc[]
ifeval::["{show-deprecation}" == "true"]
:has_deprecation_tab_3: true
endif::[]
endif::use_service_tab_3[]
endif::no_third_tab[]
endif::no_second_tab[]

// if one tab deprecation is set to true, set it generally. ifdef with comma uses or (with + uses and)
ifdef::has_deprecation_tab_1,has_deprecation_tab_2,has_deprecation_tab_3[]
:show-deprecation: true
endif::[]

endif::no_deprecation[]

// conditionally render the variable entry text, either with or without section header

ifndef::no_yaml[]

=== Environment Variables

The `{service_name}` service is configured via the following environment variables:
endif::no_yaml[]

ifdef::no_yaml[]
The `{service_name}` variables are defined in the following way:
endif::no_yaml[]

// create the tabs. note that if no_second_tab is set, the third tab is also not shown

[tabs]
====
{service_tab_1_tab_text}::
+
--
include::{ocis-services-raw-url}{service_tab_1}{ocis-services-final-path}adoc/{service_name}_configvars.adoc[]
--
ifndef::no_second_tab[]
ifdef::use_service_tab_2[]
{service_tab_2_tab_text}::
+
--
include::{ocis-services-raw-url}{service_tab_2}{ocis-services-final-path}adoc/{service_name}_configvars.adoc[]
--
endif::use_service_tab_2[]
ifndef::no_third_tab[]
ifdef::use_service_tab_3[]
{service_tab_3_tab_text}::
+
--
include::{ocis-services-raw-url}{service_tab_3}{ocis-services-final-path}adoc/{service_name}_configvars.adoc[]
--
endif::use_service_tab_3[]
endif::no_third_tab[]
endif::no_second_tab[]
====

ifndef::no_yaml[]

=== YAML Example

Note that the filename shown below has been chosen on purpose. +
See the xref:deployment/general/general-info.adoc#configuration-file-naming[Configuration File Naming] for details when setting up your own configuration.

[tabs]
====
{service_tab_1_tab_text}::
+
--
[source,yaml]
----
include::{ocis-services-raw-url}{service_tab_1}{ocis-services-final-path}{service_name}-config-example.yaml[]
----
--
ifndef::no_second_tab[]
ifdef::use_service_tab_2[]
{service_tab_2_tab_text}::
+
--
[source,yaml]
----
include::{ocis-services-raw-url}{service_tab_2}{ocis-services-final-path}{service_name}-config-example.yaml[]
----
--
endif::use_service_tab_2[]
ifndef::no_third_tab[]
ifdef::use_service_tab_3[]
{service_tab_3_tab_text}::
+
--
[source,yaml]
----
include::{ocis-services-raw-url}{service_tab_3}{ocis-services-final-path}{service_name}-config-example.yaml[]
----
--
endif::use_service_tab_3[]
endif::no_third_tab[]
endif::no_second_tab[]
====

endif::no_yaml[]
