= Listing Space IDs
:toc: right
:description: There are rare situations like when using shell commands that require the space ID as parameter. This page shows how to get it.

== Introduction

{description} As an example of a use case, see the xref:deployment/services/s-list/storage-users.adoc#manage-trash-bin-items[Manage Trash-Bin Items] command set or the xref:{s-path}/search.adoc#manually-trigger-re-indexing-spaces[Manually Trigger Re-Indexing Spaces].

. Via the web UI +
Users can enable seeing WebDAV URLs via their personal preferences of the Infinite Scale WebUI. This URL contains the space ID.

. Via CLI +
Alternatively, administrators can impersonate the respective user and get the space ID via shell commands using an authenticated curl GET accessing the Infinite Scale https://owncloud.dev/apis/[API].
+
--
The following prerequisites apply:

* The administrator must have shell access where Infinite Scale runs.
* The administrator needs to use the active bearer token in the request described below.
* For ease of reading the result, the https://jqlang.github.io/jq/[jq] library should be installed on the OS where the shell command is executed. It is used in the examples.

Note that the life span of the bearer token is short, in  particular less than a minute. If the token expires, the curl command will fail with an unauthorized message. So it is important to be prepared.
--

== Via the web UI

When the user has enabled in his personal preferences menu:Show WebDAV information in details view[], the space ID can be identified the following:

* Select a space and toggle the sidbar button on the top right to show the details.

* The WebDAV URL shows: + 
`<your host url>/remote.php/dav/spaces/c7763488-...-20badd5126b4/<optional file name>`

* The space ID is `c7763488-...-20badd5126b4`.

* Copy the ID *and* embed it in single quotes for any tasks that require a space ID as parameter.
+
--
Example:

`c7763488-...-20badd5126b4` -> `'c7763488-...-20badd5126b4'`

Single quotes are necessary because the ID can contain a `$` sign which is a special character the shell.
--

== Via CLI

include::partial$multi-location/get-bearer-token.adoc[tags=explanation,leveloffset=+1]

:curl_url_1: /graph/v1.0/drives?%24orderby=name%20asc&%24filter=driveType%20eq%20%27personal%27
include::partial$multi-location/get-bearer-token.adoc[tags=common_prep,leveloffset=+1]

=== Get Space IDs

:curl_url_1: /graph/v1.0/drives?%24orderby=name%20asc&%24filter=driveType%20eq%20%27personal%27
:curl_url_2: /remote.php/dav/spaces/59ee3b90-3231-4621-81aa-4531d33e7671%24fb9e2625-cdb0-4f21-8a34-db775a976707
include::partial$multi-location/get-bearer-token.adoc[tags=command_prep,leveloffset=+2]

include::partial$multi-location/get-bearer-token.adoc[tags=command_exec,leveloffset=+2]

==== Output

Personal Space::
+
--
[source,json]
----
{
  "value": [
    {
      "driveAlias": "personal/admin",
      "driveType": "personal",
      "id": "59ee3b90-3231-4621-81aa-4531d33e7671$fb9e2625-cdb0-4f21-8a34-db775a976707",
      "lastModifiedDateTime": "2024-03-14T12:55:21.538631978+01:00",
      "name": "Admin",
      "owner": {
        "user": {
          "displayName": "",
          "id": "fb9e2625-cdb0-4f21-8a34-db775a976707"
        }
      },
  ...
}
----
--

{empty} +

Project Space::
+
--
[source,json]
----
{
  "value": [
    {
      "driveAlias": "project/my-project-space",
      "driveType": "project",
      "id": "59ee3b90-3231-4621-81aa-4531d33e7671$ee008d1d-b17d-4c61-a7f5-4e5435d2b4e8",
      "lastModifiedDateTime": "2024-03-14T15:55:41.418616154+01:00",
      "name": "My Project Space",
      "owner": {
        "user": {
          "displayName": "",
          "id": "ee008d1d-b17d-4c61-a7f5-4e5435d2b4e8"
        }
      },
 ...
}
----
--

=== Output Interpretation and Usage

* For any *personal* or *project* space, find the name of the space in the `name` or the `driveAlias` field. The ID identifying the space is under `driveType` named `id` like:
+
--
[source,json]
----
"id": "59ee3b90-3231-4621-81aa-4531d33e7671$ee008d1d-b17d-4c61-a7f5-4e5435d2b4e8",
----

* Copy the ID
** _excluding_ the surrounding double quotes and
** _embed_ it in single quotes for any tasks that require a space ID as parameter.

Example:

`"59ee3b90-...-a7f5-4e5435d2b4e8"` -> `'59ee3b90-...-a7f5-4e5435d2b4e8'`

Single quotes are necessary because the ID can contain a `$` sign which is a special character the shell.
--
