= Integrating Office Applications
:toc: right
:description: If you configure the Infinite Scale collaboration service, you can integrate major office applications like Collabora, ONLYOFFICE or Microsoft Online.

:traefik_url: https://traefik.io/traefik/

== Introduction

{description}

NOTE: See the xref:deployment/wopi/wopi.adoc#special-ms-note[Office Applications Using WOPI] documentation for special notes on Microsoft Office.

The docker compose stack provided consists of several containers where only a few settings need to be configured via a central configuration file:

* {traefik_url}[Traefik], is a modern HTTP reverse proxy and load balancer which is terminating SSL and forwards the requests to Infinite Scale in the internal Docker network.
* Then there is Infinite Scale,
* the collaboration service,
* the Collabora and/or OnlyOffice containers that can be individually enabled,
* supplemental containers with extended functionalities or to enhance the web UI with web-applications.

== Configuration

See the xref:depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc[Local Production Setup] guide for details how to install and configure it.

