= Deployment
:toc: right
:toclevels: 3


== Deployments scenarios and examples
This section handles deployments and operations for admins and people who are interested in how versatile oCIS is. If you want to just try oCIS you may also follow xref:../getting-started.adoc[Getting started].

=== Setup oCIS on your server
oCIS deployments are super simple, yet there are many configurations possible for advanced setups.

- xref:basic-remote-setup.adoc[Basic oCIS setup] - configure domain, certificates and port
- xref:ocis_keycloak.adoc[oCIS setup with Keycloak as identity provider]
- xref:ocis_full.adoc[Flexible oCIS setup with WebOffice and Search capabilities]
- xref:oc10_ocis_parallel.adoc[Parallel deployment of oC10 and oCIS]
- xref:ocis_hello.adoc[oCIS with the Hello extension example]


== Secure an oCIS instance

oCIS no longer has any default secrets in versions later than oCIS 1.20.0. Therefore you're no
longer able to start oCIS without generating / setting all needed secrets.

The recommended way is to use `ocis init` for that. It will generate a secure config file for you.
