= Environment Variables with Special Scopes
:toc: right
:description: Some environment variables have a special, extended or global scope. Variables with special scope are related to a deployment method only.

== Introduction

{description} Variables with an extended scope do not directly configure services but functions underneath. Variables with a global scope can configure more than one service.

Examples:

* The global environment variable `OCIS_LOG_LEVEL` is available in multiple services.
* The extended environment variable `OCIS_CONFIG_DIR` can be used with `ocis init`.
* The special environment variable `OCIS_RUN_SERVICES` defines services to start when the container is started.


== Special Environment Variables

// these envvars cant be gathered automatically and must be maintained manually. they change very rarely!
// their source is in: https://github.com/owncloud/ocis/blob/master/ocis-pkg/config/config.go
// at 'type Runtime struct'

The following environment variables are only available when using a developer version for Infinite Scale. For additional information read the xref:deployment/general/general-info.adoc#start-infinite-scale[Start Infinite Scale] documentation. Read the xref:deployment/services/envvar-types-description.adoc[Environment Variable Types] documentation for important details.

include::partial$deployment/services/env-and-yaml.adoc[tag=special_envvars]


== Extended Environment Variables

////
IMPORTANT: extended envvars currently do not have an extended_deprecation.adoc file. handled in the include.

note that if a description of an extended envvar missing or strange looking envvars present, you need to fix this in:
https://github.com/owncloud/ocis/blob/master/docs/helpers/extended_vars.yaml
see the readme.md file in that folder.
////
 
:service_name: extended

Note, see the xref:deployment/services/registry.adoc[Registry] documentation for details on the Micro Registry and their available settings.

include::partial$deployment/services/env-and-yaml.adoc[tag=envvars-only]


== Global Environment Variables

// IMPORTANT: global envvars currently do not have an global_deprecation.adoc file. handled in the include.

:service_name: global

Note that the descriptions of these environment variables may differ depending on the service context.

include::partial$deployment/services/env-and-yaml.adoc[tag=envvars-only]
