= ownCloud Web with Custom Theming
:toc: right
:toclevels: 2
:description: Just like with other clients (Desktop, Android, iOS), themes can be used with ownCloud Web.

:web_assets_path: /services/web/assets/themes/owncloud/
:example-theme-url: https://github.com/owncloud/web/tree/master/config
:design-tokens-url: https://owncloud.design/#/Design%20Tokens
:gh-webui-url: https://github.com/owncloud/web/issues/new

== Introduction

{description}  As an organization or company you may be interested in theming the ownCloud Web user interface with your brand and slogan and playful individuals may simply enjoy the fun of decorating ownCloud Web the way they like.

This can be achieved by providing a json file that contains text snippets (like brand name and slogan), paths to images (e.g. logos or favicons) and design tokens for various parameters like color, sizing and spacing. In the following, we explain the setup and configuration options and provide an empty template for you to get started.

ownCloud Web can be seen as a hub for extensions like the files extension, the user management extension and others. The central part of ownCloud Web with respect to theming is the web-runtime which holds all general style definitions which can be used by but also be individually set by an extension. This makes it possible to e.g. individually style the general frame independent of an extension.

== Providing a Theme

With Infinite Scale, you can define a theming json file via the `WEB_UI_THEME_PATH` environment variable. This theming json file takes precedence over the `config/config.json` that is used in the development process when building the Web UI. See an example config.json at {example-theme-url}[GitHub, _window=blank].

NOTE: If no theme is provided or the loading of your custom theme fails, the standard Infinite Scale theme will be loaded as a fallback. However, this doesn’t stop you from correctly loading a theme that is wrongly formatted, so please read the instructions below carefully.

== Loading Themes

* Web themes are loaded, if added in the Infinite Scale source code, at build-time from `<ocis_repo>/services/web/assets/themes`.
This cannot be manipulated at runtime.

* Additionally, the administrator can provide custom themes by storing it in the path defined by the environment variable `WEB_ASSET_THEMES_PATH`.

* With the theme root directory defined, the system needs to know which theme to use. This can be done by setting the `WEB_UI_THEME_PATH` environment variable.

* The final theme is composed of the built-in and the custom theme provided by the administrator via `WEB_ASSET_THEMES_PATH` and `WEB_UI_THEME_PATH`.

* For example, Infinite Scale by default contains a built-in ownCloud theme. If the administrator provides a custom theme via the `WEB_ASSET_THEMES_PATH` directory like, `WEB_ASSET_THEMES_PATH/owncloud/themes.json`, this one will be used instead of the built-in one.

Some theme keys are mandatory, like the `common.shareRoles` settings. Such mandatory keys are injected automatically at runtime if not provided.

== Configuring a Theme

.Sourced from https://github.com/owncloud/ocis/blob/{ocis_repo_url_component}{web_assets_path}theme.json[GitHub, _window=blank]
[source,json]
----
include::{ocis_services_raw_url}{ocis_repo_url_component}{web_assets_path}theme.json[]
----
