= Upgrading Infinite Scale
:toc: right
:toclevels: 2
:description: When upgrading Infinite Scale, migration steps may be required. This document guides thru the necessary steps based on the versions used.

== Introduction

{description}

NOTE: For any Infinite Scale version to upgrade to, see {ocis-downloadpage-url}?sort=time&order=desc[download.owncloud.com,window=_blank] or {docker-ocis-url}[Infinite Scale image] to get the right version.

IMPORTANT: Before starting any upgrade, make a xref:maintenance/b-r/backup.adoc[backup] first.

IMPORTANT: If not explicitly mentioned, any upgrade is forward only and a backstep is neither supported nor recommended and will most likely break the instance.

IMPORTANT: When upgrading from an older release to the desired one, *ALL* upgrade steps from each release must be taken in order and none can be skipped.  

== Version 3.0.0 to 3.1.0

=== Notable Changes Requiring Manual Intervention

* The space index of the decomposedFS will be automatically migrated from symlinks to messagepack. This migration needs preparation to run successfully.
* The xref:deployment/container/orchestration/orchestration.adoc#using-our-helm-charts-with-infinite-scale[Helm Chart] has been upgraded.

=== Upgrade Steps

For a detailed description of the steps to upgrade see the xref:migration/upgrading_3.0.0_3.1.0.adoc[Upgrading from 3.0.0 to 3.1.0] documentation.

== Version 2.0.0 to 3.0.0

=== Notable Changes Requiring Manual Intervention

* A new `GRAPH_APPLICATION_ID` environment variable has been added that must be populated.
* Automatic Role Assignments have been introduced that need a settings review.
* A new `OCIS_LDAP_DISABLE_USER_MECHANISM` environment variable has been introduced that needs a settings review.
* The search index needs to be deleted as the layout has been changed.
* The xref:prerequisites/prerequisites.adoc#backend-for-metadata[metadata backend] has changed.
* The xref:deployment/container/orchestration/orchestration.adoc#using-our-helm-charts-with-infinite-scale[Helm Chart] has been upgraded.

=== Upgrade Steps

For a detailed description of the steps to upgrade see the xref:migration/upgrading_2.0.0_3.0.0.adoc[upgrading from 2.0.0 to 3.0.0] documentation.
