= Upgrading from 5.0.x to 7.0.0
:toc: right
:description: This document describes the necessary steps when upgrading Infinite Scale from release 5.0.x to 7.0.0.

include::partial$multi-location/compose-version.adoc[]

== Introduction

{description}

IMPORTANT: Read the important notes in the xref:migration/upgrading-ocis.adoc#introduction[Upgrading Infinite Scale] documentation before you start.

IMPORTANT: Check below, if you are affected by breaking changes and prepare all steps mentioned before you start the upgrade.

== Upgrade Steps

. Shut down the Infinite Scale instance
. Download and install Infinite Scale +
*Do not start it after downloading the binary or image*!
. Manage Breaking Changes
. Start Infinite Scale

== Download and Install Infinite Scale

Download and install Infinite Scale via:

* *Binary* +
Follow the xref:depl-examples/minimal-bare-metal.adoc#installation[Installation] section of the bare metal deployment example.

* *Image Based Deployments*
+
[source,bash,subs="attributes+"]
----
docker pull owncloud/ocis:7.0.0
----

** When using `docker run`
*** Update the image version used in the docker run command.

** When using `docker compose`
*** Update _every_ compose file where the `ocis image` is referenced accordingly.
*** If you have used the deployment examples based on _rolling releases version 6.x_ either for xref:depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc[Local Production Setup] or xref:depl-examples/ubuntu-compose/ubuntu-compose-hetzner.adoc[Deployment on Hetzner], read the *Updating* section of those pages carefully. 

** When using `Kubernetes - Helm`
*** Update `{{ .Values.image.tag }}` and/or `{{ .Chart.AppVersion }}` accordingly.

== Manage Breaking Changes

* All environment variables that were marked for deprecation in Infinite Scale release 5.0.x have finally been removed.
* A new mandatory Infinite Scale config setting for the `activitylog` service named `service_account` has been added.

=== How to Identify if You Are Affected

* If you are using deprecated environment variables in your config.
** See the xref:deployment/services/env-var-changes.adoc[Added and Removed Environment Variables] documentation.

* Because the xref:{s-path}/activitylog.adoc[activitylog] service has been added and is started automatically, everyone who upgrades is affected.

=== How to Manage the Change

* Manage deprecated variables
** Environment variables that have been deprecated without successor can safely be removed from the configuration. These envvars do not harm as they are not used anymore.
** Environment variables that have been deprecated with a successor need to be updated accordingly.

* Add new Infnite Scale config settings. +
To do so, the following steps need to be taken, here is the overview:
+
--
. Get the new binary/image, but do not start Infinite Scale
. Get the config diff via command
. Apply the diff created
--
+
See the detailed steps below.

* You can now start Infinite Scale as usual

{empty}

Update Config Settings::
* If not already done, get the new Infinite Scale version as described in xref:download-and-install-infinite-scale[Download and Install Infinite Scale].

* Run the `ocis init --diff` command: +
Because this will now run the new ocis code, it will create two files to help manage the needed changes:
+
--
. `ocis.config.patch` which contains all the changes that can be applied and
. `ocis.yaml.<time-stamp>.backup` containing a backup of the original config.
--
+
The diff option will NOT overwrite anything though questions will be asked. Consider using the correct answer for `certificate checking` as this will influence the respective diff output.
+
Depending on the deployment selected, you need to prepare for this command differently, assuming the location of the config directory is the default:

** *Binary Deployment*:
+
--
[source,bash]
----
ocis init --diff
----
Change into the Infinite Scale config directory located at `$HOME/.ocis/config/` and apply the changes with:

[source,bash]
----
patch < ocis.config.patch
----
{empty}
--

** *Docker Deployment*:
+
--
This will open a shell in a temporary container using the new Infinite Scale image. Note that you *MUST* provide the mount/volume definition where the configuration settings are stored to make the `ocis init` command work. The bind mount from below is just an example and fails if the local directory does not exist!

[source,bash]
----
sudo docker run --rm -it \
    owncloud/ocis:7.0.0 \
    --mount type=bind,source=$HOME/ocis/ocis-config,target=/etc/ocis \
    sh
----

Then, when the containers shell is available, type:

[source,bash]
----
ocis init --diff
----
Change into the containers config directory `/etc/ocis` and apply the changes with:

[source,bash]
----
patch < ocis.config.patch
----
{empty}
--

** *Docker Compose Deployment*:
+
--
This will open a shell in a temporary container using the new Infinite Scale image. Note that you *MUST* provide the volume definition where the configuration settings are stored defined in the compose file to make the `ocis init` command work. The named volume from below is just an example and uses the volume name from our docker compose deployment examples.

[source,bash]
----
sudo docker run --rm -it \
    owncloud/ocis:7.0.0 \
    -v ocis-config:/etc/ocis \
    sh
----

Then, when the containers shell is available, type:

[source,bash]
----
ocis init --diff
----
Change into the containers config directory `/etc/ocis` and apply the changes with:

[source,bash]
----
patch < ocis.config.patch
----
{empty}
--

** *Any Other Image Based Deployment*:
+
--
Use one of the Docker based examples from above and derive from. 
--

== Changed or Added CLI Commands

See the link for a detailed description of the respective CLI command if available. If a command has been backported to version 5, always use the latest production version of that release.

* xref:maintenance/commands/commands.adoc#purge-expired-space-trash-bin-items[Purge Expired Space Trash-Bin Items]  +
The `ocis storage-users uploads` got restructured. +
The deprecated `list` option is now removed, the `clean` option is now part of the `sessons command`.

* xref:maintenance/commands/commands.adoc#reset-password-for-idm-users[Reset Password for IDM Users] +
The `ocis idm resetpassword` can now specify the user name via the `--user-name` (`-u`) flag.

* A `health` command was added to each service: `ocis <service-name> health`.

* xref:maintenance/commands/commands.adoc#trash-purge[Trash Purge]. +
The `ocis trash purge-empty-dirs` command has been added.

* xref:maintenance/commands/commands.adoc#revisions-cleanup[Revisions Cleanup] +
The `ocis revisions purge` command allows removing revisions of files in the storage. +
Note that this command has also been backported to version 5.

== Deprecations

* lets see what will come here
