= Upgrading from 4.0.x to 5.0.0
:toc: right
:description: This document describes the necessary steps when upgrading Infinite Scale from release 4.0.x to 5.0.0.

== Introduction

{description}

IMPORTANT: Read the important notes in the xref:migration/upgrading-ocis.adoc#introduction[Upgrading Infinite Scale] documentation before you start.
 
== Upgrade Steps

. Shut down the Infinite Scale instance.
. Update Infinite Scale via:
+
--
* Docker
+
[source,bash]
----
docker pull owncloud/ocis:5.0.0
----

* or get the binary from {ocis-downloadpage-url}?sort=time&order=desc[download.owncloud.com,window=_blank].
--

== Manage Breaking Changes

* All environment variables that were marked for deprecation in Infinite Scale release 4.0.0 have finally been removed.
* The default service registry has been changed.
* Service accounts are now needed for some backend operations.
* Resharing is now disabled by default and will be removed from the product.
* The structure of the `theme.json` file has changed.

=== How to Identify if You Are Affected

* If you are using deprecated environment variables in your config.
** See the xref:deployment/services/env-var-changes.adoc[Added and Removed Environment Variables] documentation.
* If you have changed the default configuration for the xref:deployment/services/env-vars-special-scope.adoc#extended-environment-variables[MICRO_REGISTRY] environment variable.
* If you have used custom theming in your Infinite Scale instance...
** by providing a custom theme.json file.
** by uploading a custom logo without additional changes to the theme.

In all other cases, there is nothing that needs to be done as the new defaults for client pool selectors will be used automatically.

=== How to Manage the Change

* Manage deprecated variables
** Environment variables that have been deprecated without successor can safely be removed from the configuration. These envvars do not harm as they are not used anymore.
** Environment variables that have been deprecated with a successor need to be updated accordingly.

* The `MICRO_REGISTRY` environment variable
** We changed the service registry to use the natsjs key-value store from the `nats` service as a storage.
+
--
{empty}
[width="100%",cols="40%,30%,20%"]
|===
3+^h| Default used value, new and old
h| Global envvar
h| New value
h| Old value

| xref:deployment/services/env-vars-special-scope.adoc#extended-environment-variables[MICRO_REGISTRY]
| nats-js-kv
| memory

| xref:deployment/services/env-vars-special-scope.adoc#extended-environment-variables[MICRO_REGISTRY_ADDR]
| 127.0.0.1:9233
| <was not set>
|===
{empty}
--

** If you have more than one container or process for the Infinite Scale deployment:
+
--
You need to make the same service registry available to all Infinite Scale processes and expose the micro registry in the container or process where you have the `nats` service running and use that from the other processes as a shared registry.

Docker compose example with an app provider:

[source,yaml]
----
---
version: "3.7"

services:
  ocis:
    environment:
      NATS_NATS_HOST: 0.0.0.0 # bind on all interfaces to expose the nats service
  ...
  ocis-appprovider-collabora:
    environment:
      # use the shared registry from the ocis container
      MICRO_REGISTRY_ADDRESS: ocis:9233

----
--
* We introduced service accounts in the area of service-to-service communication. We need this change to properly authenticate backend calls which are not triggered by user interaction like search indexing, auto accepting of shares or timed trashbin cleanup jobs. Instances which are migrated from ocis 4.x need manual steps to avoid becoming non functional.
+
--
Two new global environment variables have been introduced to manually configure the instance: `OCIS_SERVICE_ACCOUNT_ID` and `OCIS_SERVICE_ACCOUNT_SECRET`. Please set the first one to a random uuid and create a strong secret value for the second one.
[source, sh]
----
OCIS_SERVICE_ACCOUNT_ID=<some-uuid-v4>
OCIS_SERVICE_ACCOUNT_SECRET=<some-secret-string>
----

NOTE: For new deployments starting with ocis 5.0.0, these values are autogenerated by running `ocis init`

WARNING: If no values are provided during an upgrade, ocis will not start and log a fatal error.
--

* We have changed the structure of the `theme.json` file. This was done for several reasons:
** To be able to support multiple client platforms,
** to be able to create a fallback chain of theming information and
** to reduce the amount of configuration needed for theming.

+
--
If you have a custom `theme.json` file, you need to update it to the new structure.

* The old structure can be found here: https://doc.owncloud.com/ocis/4.0/deployment/webui/webui-theming.html#example-theme[Infinite Scale 4.0 Example Theme, window=_blank].
* The new structure can be found here: https://owncloud.dev/clients/web/theming/#example-theme[Infinite Scale 5.0 Example Theme, window=_blank].

The most important adjustment is the fact, that the old structure only supported multiple themes on a single platform (web). The new structure defines a `common` and a `clients` section on the root level of the file.

* The `common` section provides defaults for all client platforms.
* The `clients` section provides platform specific general theming information and a list of themes.

Note that the "Desktop", "Android" and "iOS" platforms currently lack support for the themes provided by Infinite Scale.

The theming data from your old `theme.json` file needs to be moved to the "web" section of the new `theme.json` file.
This can be done with copy & paste and only small adjustments, since the structure of a single, web-specific theme within the `theme.json` remains mostly unchanged.

WARNING: If you have uploaded a custom logo without additional changes to the theme, oCIS internally created a custom theme.json anyway which now needs to be deleted. Otherwise any logo upload attempt will fail.
--

=== Deprecations

* Service Registries +
We deprecated some service registries. If your `MICRO_REGISTRY` config is set to one of these values `mdns, nats, kubernetes, etcd, consul` please use `nats-js-kv` in the future (`memory` is only intended for testing environments).

* Micro caches and stores +
We deprecated some micro caches and stores. If one of your `*_CACHE_STORE` variables is using one of there values `redis-sentinel`, `redis`, `etcd`, `nats` or `ocmem`,  use `nats-js-kv` in the future. Note that `memory` is only intended for testing environments.

* Resharing +
We have disabled the resharing feature by default. It will be removed from the product. Existing reshares will still be visible to the original resource owner. Creation of new reshares will not be possible. Make sure that `OCIS_ENABLE_RESHARING` is *not* set to `true` in your deployments.
