= Bare Metal Deployment with systemd 
:toc: right
:toclevels: 3
:page-aliases: depl-examples/small-scale.adoc
:description: This guide describes an installation of Infinite Scale as a systemd service on bare metal. This ranges from a small installation on a Raspberry Pi up to installations on a decent server.

:systemd-url: https://systemd.io/
:nginx-url: https://www.nginx.com/
:apache-url: https://www.apache.org
:certbot-url: https://certbot.eff.org
:certbot-options-url: https://eff-certbot.readthedocs.io/en/stable/using.html#id36
:ssl-labs-url: https://www.ssllabs.com/ssltest/
:apache_http2_url: https://httpd.apache.org/docs/2.4/howto/http2.html

:ocis_bin: /usr/local/bin
:ocis_env: /etc/ocis
:ocis_data: /var/lib/ocis
:ocis_url: ocis.example.com
:ocis_port: 9200

include::partial$multi-location/compose-version.adoc[]

== Introduction

{description}

This deployment example addresses a small production environment without running online office applications etc. For a minimal test and development environment, see the xref:depl-examples/minimal-bare-metal.adoc[Minimal Bare Metal Deployment]. The main differences between the setup described in this document and a minimal test environment is, the use of systemd, letsencrypt and a reverse proxy. If you intend to run a complete setup using online office, full text search etc., see the *Ubuntu with Docker Compose* deployment examples.

Note that this guide expects that prerequisite of a computer with an installed Linux distribution of choice is met and required software other than Infinite Scale is installed and preconfigured. There is no detailed explanation but, where possible, links for more information are provided.

Note that there is a difference in internal thumbnail processing when using binary vs container deployments. For details see the xref:{s-path}/thumbnails.adoc#thumbnailing-performance[thumbnails] service.

This guide was tested on a Debian 11 (bullseye) host but should work on any other modern Linux system with systemd.

NOTE: The embedded IDM service provides a minimal LDAP service for Infinite Scale and does not replace a LDAP server. See the xref:{s-path}/idm.adoc[IDM Service Configuration] for details.

NOTE: Consider to extend the configuration described based on the information given in xref:{s-path}/storage-users.adoc#graceful-shutdown[Graceful Shutdown].

== Requirements

* A supported filesystem according the xref:prerequisites/prerequisites.adoc#filesystems-and-shared-storage[ocis prerequisites,window=_blank].

* {systemd-url}[systemd]
* A HTTP reverse proxy, there are examples using {nginx-url}[nginx,window=_blank] and {apache-url}[Apache,window=_blank]
* {certbot-url}[Certbot,window=_blank] + the nginx or Apache plugin
+
[NOTE]
====
* For certbot, there are many {certbot-options-url}[command line options,window=_blank] available supporting common tasks like increasing security measures or automatic redirection, the example commands are limited to the minimum issuing a certificate. This includes that configuration files and security measures need to be applied manually.
* With respect to security, some of the measures are shown in examples but not all possibilities are covered.
* If using certbot command line options, files may be split by port and content can differ, though the result when combined is the same.
====

== Excluded Tasks

There are a few steps that are recommended but not covered in this guide:

* Automate the Let's Encrypt certificate renewal via cron jobs
* Install and set up a firewall

== Used Settings

The following settings were used in this guide. You can change this according your needs:

* The Infinite Scale binary location: `{ocis_bin}` (OS default)
* The Infinite Scale xref:deployment/general/general-info.adoc#configuration-directory[configuration directory]: `{ocis_env}`
* The Infinite Scale xref:deployment/general/general-info.adoc#base-data-directory[base data directory]: `{ocis_data}`
* The URL accessing Infinite Scale: `{ocis_url}` +
Note that this URL must resolve to the server running this installation.
* The internal port accessing Infinite Scale: {ocis_port} (default)

== Install and Prepare Infinite Scale

=== Install and configure the Infinite Scale Binary

* Download and install the Infinite Scale binary. To get the stable binary from ownCloud, visit {ocis-downloadpage-url}/{download-type}/?sort=time&order=desc[download.owncloud.com,window=_blank], select the version and the platform of choice and copy the link of the file.
+
[source,bash,subs="attributes+"]
----
sudo wget -O {ocis_bin}/ocis <file_url>
----

* Make the binary executable with:
+
[source,bash,subs="attributes+"]
----
sudo chmod +x {ocis_bin}/ocis
----

* Check the version installed:
+
--
[source,bash]
----
ocis version  --skip-services
----

The output looks like this:

[source,plaintext,subs="attributes+"]
----
Version: {compose_version}
Compiled: {ocis-compiled}
----
--

=== Create a Service User

* In your operating system, create a user and group who will run the ocis service and own all the files of the Infinite Scale service but is not allowed to log in, has no shell and no home directory.
+
[source,bash]
----
sudo useradd --system --no-create-home --shell=/sbin/nologin ocis
----

=== Infinite Scale Data Directory

* Create the ocis data directory. All system data will be stored here including all files uploaded by the users.
+
[source,bash,subs="attributes+"]
----
sudo mkdir -p {ocis_data}
----

* Make the service user `ocis` the owner of the data directory.
+
[source,bash,subs="attributes+"]
----
sudo chown ocis:ocis {ocis_data}
----

=== Infinite Scale Configuration File

* Create a directory and config file necessary for ocis. For security reasons, this user should have restricted permissions for this directory:
+
--
[source,bash,subs="attributes+"]
----
sudo mkdir -p {ocis_env}
----

[source,bash,subs="attributes+"]
----
sudo touch {ocis_env}/ocis.env
----

[source,bash,subs="attributes+"]
----
sudo chown -R ocis:ocis {ocis_env}
----
--

* Create the environment file `{ocis_env}/ocis.env` with the following content. Adjust the `OCIS_URL` variable to hold your domain where Infinite Scale will be reachable via `nginx`. Add the correct port to `OCIS_URL` if it deviates from the default port 443 like `\https://{ocis_url}:4242`. See the xref:deployment/general/general-info.adoc[General Information] section for more information about the environment variables used. 
+
--
[source,bash,subs="attributes+"]
----
sudo vi {ocis_env}/ocis.env
----

[source,plaintext,subs="attributes+"]
----
OCIS_URL=https://{ocis_url}
PROXY_HTTP_ADDR=0.0.0.0:{ocis_port}
PROXY_TLS=false
OCIS_INSECURE=false

OCIS_LOG_LEVEL=warn

OCIS_CONFIG_DIR={ocis_env}
OCIS_BASE_DATA_PATH={ocis_data}
----

`PROXY_TLS` is set to `false` because xref:deployment/services/tls.adoc#tls-for-the-http-frontend[TLS termination] will be done by the webserver. Though you also can secure the communication between Infinite Scale and the webserver, this is not covered by this document.
--

* Set `OCIS_CONFIG_DIR` and `OCIS_BASE_DATA_PATH`
+
IMPORTANT: It is important to set both the `config` and `data` directory environment variables in the `ocis.env` file. If this is omitted, ocis shell commands will not work.

* Setting the correct `OCIS_URL` is essential for the built-in openIDConnect IDP as the xref:{s-path}/idp.adoc[IDP service] needs to be reachable under the same host and port as the reverse proxy is configured. If this has not been configured the same, the IDP service will log errors like `origin does not match request URL`. See the xref:deployment/general/general-info.adoc#using-the-embedded-idp-service[Using the Embedded IDP Service] for configuration notes of the `PROXY_TLS` environment variable.
+
IMPORTANT: See the important notes for xref:deployment/general/general-info.adoc#configurations-to-access-the-web-ui[Configurations to Access the Web UI].

* Generate the initial Infinite Scale configuration file, also see xref:deployment/general/ocis-init.adoc[The ocis init Command]:
+
--
[source,bash,subs="attributes+"]
----
sudo -u ocis ocis init --config-path {ocis_env}
----

You will be asked if you want to configure Ininite Scale with certificate checking disabled. You can safely answer `yes`. Infinite Scale is composed of several microservices which encrypt the communication between them with TLS. By answering with `yes` the communication is still encrypted but client and server certificates aren't checked for validity. Usually this is good enough. For an extra secure deployment, provide a verifiable TLS certificate and enable certificate checking.

NOTE: The command when run successfully will show you the initial admin user's password. Write it down somewhere safe so that you can log in when the setup is complete. The password can be changed in the UI later on or be reset if forgotten via xref:deployment/general/general-info.adoc#password-reset-for-the-admin-user[Password Reset for the Admin User].

This command will create the configuration file `{ocis_env}/ocis.yaml`.

IMPORTANT: Do NOT delete the `ocis.yaml` file without creating a backup of it first. When you regenerate the `ocis.yaml` file, it will be out of sync with the stored user data in the ocis data directory `{ocis_data}`. If for some reason you still want to regenerate the config file, you first need to empty the data directory but beware if you already have user files stored there. Also see xref:deployment/general/ocis-init.adoc[The ocis init Command] for more details.
--

== Setup the systemd Service

* {empty}
+
--
include::partial$deployment/systemd.adoc[]
--

include::partial$deployment/dependent_startup.adoc[leveloffset=+2]

== Nginx as Reverse Proxy

NOTE: Whenever a configuration change has been made, you need to do a configuration check and reload the nginx configuration. This can be done with two methods as described below. Select your preferred one. For ease of writing, the examples show `sudo nginx -s reload`.

* {empty}
+
--
[source,bash]
----
sudo nginx -s reload
----
Note that this command includes checking and reloading the config in the same step.
--

* {empty}
+
--
[source,bash]
----
sudo nginx -t
----

[source,bash]
----
sudo systemctl reload nginx
----
Note that using `systemctl reload nginx` alone will NOT validate your configuration but will execute the command in a clean environment and not in the current user environment.
--

=== Prepare nginx for certbot

* To set up nginx as a reverse proxy with Let's Encrypt TLS certificates, create a file called e.g. `ocis` under `/etc/nginx/sites-available` with the following content:
+
include::partial$deployment/nginx_80_example.adoc[]

* Activate the new nginx config:
+
--
[source,bash]
----
sudo ln -s /etc/nginx/sites-available/ocis /etc/nginx/sites-enabled/ocis
----
--

* Check the config and reload nginx:
+
--
[source,bash]
----
sudo nginx -s reload
----
--

=== Issuing a Certificate via certbot for nginx

* Run `certbot` to issue the TLS certificates:
+
[source,bash,subs="attributes+"]
----
sudo certbot --nginx -d {ocis_url}
----

=== Finalize the nginx Configuration

* Adapt the config to redirect automatically to https, use the newly generated certificates and add the required proxy configuration. The full config should look like this:
+
include::partial$deployment/nginx_proxy_example.adoc[]

* Add the following to the SSL definition above if SSL security should be hardened / improved:
+
include::partial$deployment/nginx_harden_ssl.adoc[]

* Check the config and reload nginx:
+
--
[source,bash]
----
sudo nginx -s reload
----
--

If the server is accessible from the web, see the free {ssl-labs-url}[SSL Labs] page to check the sites SSL security. 

Open a web browser, navigate to your Infinite Scale URL `\https://{ocis_url}` and log in as admin user with the password returned by the `ocis init` command.

== Apache as Reverse Proxy

NOTE: Whenever a configuration change has been made, you need to do a configuration check and reload the Apache configuration. This can be done with two methods as described below. Select your preferred one. For ease of writing, the examples show `sudo apache2ctl -k graceful`.

* {empty}
+
--
[source,bash]
----
sudo apache2ctl -k graceful
----
Note that this command includes checking and reloading the config in the same step.
--

* {empty}
+
--
[source,bash]
----
sudo apache2ctl -t
----

[source,bash]
----
sudo systemctl reload apache2
----
Note that using `systemctl reload apache2` alone will NOT validate your configuration but will execute the command in a clean environment and not in the current user environment.
--

=== Prepare Apache for certbot

* To set up Apache as a reverse proxy with Let's Encrypt TLS certificates, create a file called e.g. `ocis` under `/etc/apache2/sites-available` with the following content:
+
include::partial$deployment/apache_80_example.adoc[]

* Activate the new Apache config and reload Apache:
+
--
[source,bash]
----
sudo ln -s /etc/apache2/sites-available/ocis /etc/apache2/sites-enabled/ocis
----

[source,bash]
----
sudo apache2ctl -k graceful
----
--

=== Issuing a Certificate via certbot for Apache

* Run `certbot` to issue the TLS certificates:
+
[source,bash,subs="attributes+"]
----
sudo certbot --apache -d {ocis_url}
----

=== Finalize the Apache Configuration

* Adapt the config to redirect automatically to https, use the newly generated certificates and add the required proxy configuration. The full config should look like this:
+
include::partial$deployment/apache_proxy_example.adoc[]

* Add the following to the SSL definition above if SSL security should be hardened / improved:
+
include::partial$deployment/apache_harden_ssl.adoc[]

* Reload Apache:
+
[source,bash]
----
sudo apache2ctl -k graceful
----

See the linked documentation how to enable the {apache_http2_url}[http2,window=_blank] protocol for Apache.

If the server is accessible from the web, see the free {ssl-labs-url}[SSL Labs] page to check the sites SSL security. 

Open a web browser, navigate to your Infinite Scale URL `\https://{ocis_url}` and log in as admin user with the password returned by the `ocis init` command.

== Updating

ifeval::["{version-type}" == "rolling"]
Note that this deployment can, for the time being, only be updated within Infinite Scale rolling releases.
endif::[]

If new Infinite Scale releases are available, you *must not* skip any version in between the current running and the latest available release for internal upgrade reasons. All versions need to be downloaded and started one time. For more details see the https://owncloud.dev/ocis/release_roadmap/#updating-and-overlap[Updating and Overlap] description in the developer documentation.

* If there is no release gap, you can update by stopping the runtime via systemd (`sudo systemctl stop ocis`), xref:install-and-configure-the-infinite-scale-binary[update the binary and make it executable] and start the runtime with systemd again (`sudo systemctl start ocis`).
* For *any* https://owncloud.dev/ocis/release_roadmap/#dates[release gap], you must follow the procedure described above.
