= Minimal Bare Metal Deployment
:toc: right
:toclevels: 3
:page-aliases: deployment/binary/binary-setup.adoc
:description: This description allows you to have an Infinite Scale system up and running with only a few commands.

:systemd-url: https://systemd.io/
:traefik-url: https://doc.traefik.io/traefik/getting-started/install-traefik/

:ocis_bin: /usr/local/bin
:ocis_env: $HOME/.ocis/config/
:ocis_data: /var/lib/ocis
:ocis_url: localhost or IP
:ocis_port: 9200

include::partial$multi-location/compose-version.adoc[]

== Introduction

{description} It does not cover extended deployment tasks or how to manage trusted certificates etc. and is intended to get a first hands-on experience of the system.

For a small production environment using the binary installation approach, see the xref:depl-examples/bare-metal.adoc[Bare Metal Deployment with systemd]. The main differences between this setup and the small production environment using the binary installation is, in a nutshell, the use of systemd, LetsEncrypt and a reverse proxy.

[IMPORTANT]
====
This minimal bare metal deployment makes the following assumptions:

* Acccessing Infinite Scale only from the server. + 
Use `\https://localhost:{ocis_port}` as URL and no further configuration is neccesary. +
To access Infinite Scale via hostname or IP, see xref:accessing-infinite-scale-other-than-localhost[Accessing Infinite Scale Other Than Localhost].

* You are fine in the first step using Infinite Scales internal unsigned certificates. +
Trusted certificates can be installed later on, see xref:deployment/general/general-info.adoc#handling-certificates[Handling Certificates] for more information. 
====

IMPORTANT: ownCloud highly recommends reading the xref:deployment/general/general-info.adoc[General Information] page first, as it contains valuable information about configuration rules, managing services and default paths - just to mention some of the useful topics.

== Prerequisites

See the xref:prerequisites/prerequisites.adoc#filesystems-and-shared-storage[Prerequisites,window=_blank] section for more details.

== Used Settings

The following settings were used in this guide. You can change this according to your needs:

* The Infinite Scale binary location: `{ocis_bin}` (OS default)
* The Infinite Scale xref:deployment/general/general-info.adoc#configuration-directory[configuration directory]: `{ocis_env}`
* The Infinite Scale xref:deployment/general/general-info.adoc#base-data-directory[base data directory]: `{ocis_data}`
* The URL for accessing Infinite Scale: `localhost`
* The port for accessing Infinite Scale: `{ocis_port}` (default)

== TL;DR

For those who want to skip reading the full document, use this summary of commands to download, start and access Infinite Scale without any additional information provided. For more details and explanations, we recommend taking the step by step process starting with the next section.

IMPORTANT: With this approach, the system you install Infinite Scale on *must* have a GUI present. A headless system has different requirements and needs an extended setup, see xref:accessing-infinite-scale-other-than-localhost[Accessing Infinite Scale Other Than Localhost].

Define a stable binary to use as replacement for `<file_url>` via {ocis-downloadpage-url}/{download-type}/?sort=time&order=desc[download.owncloud.com,window=_blank], replace `<file_name>` in the command accordingly.

[source,bash,subs="attributes+"]
----
sudo wget -P {ocis_bin} <file_url>
----

[source,bash,subs="attributes+"]
----
sudo chmod a+x {ocis_bin}/<file_name>
----

[source,bash,subs="attributes+"]
----

sudo ln -s {ocis_bin}/<file_name> {ocis_bin}/ocis
----

[source,bash]
----
ocis init
----

[source,bash]
----
ocis server
----

Open a browser and use as URL: `\https://localhost:{ocis_port}` and the credentials printed by the `ocis init` command to login.

Congratulations, you now have access to your Infinite Scale instance.

== Installation

* To get the stable binary from ownCloud, visit {ocis-downloadpage-url}/{download-type}/?sort=time&order=desc[download.owncloud.com,window=_blank], select the version and the platform of choice and copy the link of the file. Check the sort order on the modification date to get the most recent releases on top. Depending on your system and preferences, you may want to save the binary in `{ocis_bin}`. Replace `<file_url>` and `<file_name>` in the commands accordingly.
+
--
Download the binary:

[source,bash,subs="attributes+"]
----
sudo wget -P {ocis_bin} <file_url>
----
--

* Make the binary executable with:
+
[source,bash,subs="attributes+"]
----
sudo chmod a+x {ocis_bin}/<file_name>
----

* Create a link from the versioned ocis binary to the final executable named `ocis`: +
Note when using a symbolic link like this, upgrading and/or testing is much easier.
+
[source,bash,subs="attributes+"]
----
sudo ln -s {ocis_bin}/<file_name> {ocis_bin}/ocis
----

* Check the version installed:
+
--
[source,bash,subs="attributes+"]
----
ocis version --skip-services
----

The output looks like this:

[source,plaintext,subs="attributes+"]
----
Version: {compose_version}
Compiled: {ocis-compiled}
----

Note that if you omit `--skip-services`, you will get additional information about services printed.
--

NOTE: If you already have a running instance, you must stop and restart the instance to activate the new version.

== Getting Command Line Help

To get a list of available options and commands type:

[source,bash]
----
ocis
----

or

[source,bash]
----
ocis --help
----

== Starting Infinite Scale

Infinite Scale is started in two steps:

* A first time start to initialize the system and
* a recurring start after initialization.

Refer to the xref:deployment/general/general-info.adoc#default-users-and-groups[Default Users and Groups] section if you want to have demo users created when initializing the system. This step can only be done during initialization.

=== First Time Initializing Infinite Scale

Infinite Scale needs a xref:deployment/general/general-info.adoc#initialize-infinite-scale[first time initialization] to set up the environment. You will need to answer questions as the basis for generating a default `ocis.yaml` file. You can edit this file later. The default location for config files is, if not otherwise defined, `{ocis_env}`. For details see the xref:deployment/general/general-info.adoc#configuration-directory[Configuration Directory] documentation. Type the following command to initialize Infinite Scale.

[source,bash]
----
ocis init
----

On success, you will see a message like:

:init_path: pass:[<your-user>/.ocis/config/ocis.yaml]

include::partial$deployment/ocis_init.adoc[]

[NOTE]
====
If you get an error message like the following:

[source,plaintext]
----
Could not create config: config in /home/<user-name>/.ocis/config/ocis.yaml already exists
----

you already have created a configuration once. As you cannot overwrite the existing configuration, you must delete the old configuration first to proceed. For more details, see: xref:deployment/general/general-info.adoc#initialize-infinite-scale[Initialize Infinite Scale].
====

=== Starting the Infinite Scale Runtime

After initializing Infinite Scale for the first time, you can start the Infinite Scale runtime which includes embedded services.

Starting Infinite Scale::
The example commands shown below have no environment variables or command line options for ease of reading, add them according to your requirements.
+
--
To start the Infinite Scale runtime type:

[source,bash]
----
ocis server
----

Note that this will bind `ocis` to the shell you are running. If you want to detach it and avoid it being stopped when closing the shell or the shell gets disconnected (SIGHUP), use the following command:

.Bash
[source,bash]
----
ocis server & disown -h
----

.ZSH
[source,zsh]
----
ocis server & disown %%
----

See the respective shell documentation for how to manage processes respectively detach and re-attach sessions.
--

=== Configuring Infinite Scale

Infinite Scale can be configured via environment variables, see the following sections for more information and details:

* xref:deployment/general/general-info.adoc#start-infinite-scale-with-environment-variables[Starting Infinite Scale With Environment Variables]
* xref:deployment/general/general-info.adoc#configurations-to-access-the-web-ui[Configurations to Access the Web UI]

NOTE: You cannot instantiate runtime services though you can define which services should start or be excluded from starting. See xref:deployment/general/general-info.adoc#managing-services[Managing Services] for more details.

== Accessing Infinite Scale

When you have configured and started the Infinite Scale runtime as described in the example command above, you can access it via a browser using `\https://localhost:{ocis_port}`. Use the credentials printed from the `ocis init` command.

=== Accessing Infinite Scale Other Than Localhost

include::partial$multi-location/idm-https-reverse-proxy.adoc[]

== List Running Infinite Scale Processes

To list all running ocis processes type:

[source,bash]
----
ps ax | grep ocis | grep -v grep
----

[source,plaintext]
----
 221297 pts/1    Sl     0:04 ocis server
 221706 pts/0    Sl     0:00 ocis notifications
----

== Stopping Infinite Scale

To properly stop Infinite Scale, the signal `SIGTERM` (15) is used. Note that SIGTERM politely asks a process to terminate. It will terminate gracefully, cleaning up all resources (files, sockets, child processes, etc.), deleting temporary files and so on. Do not use `SIGKILL` (9) as this will initiate a dirty shutdown.

The following command stops the runtime with all its services plus any extra started services which are not part of the runtime and have been started manually. Depending on the user you started `ocis` with and which user you are currently logged in as, you may need to use `sudo` for the killall command for proper permissions.

[source,bash]
----
killall -v -s 15 ocis
----
