= Office Applications Using WOPI
:toc: right
:description: Infinite Scale uses the WOPI protocol to integrate office applications. This document describes the general flow and basic settings used.

:wopi_subdir: /ocis_wopi
:office-online-server-url: https://docs.microsoft.com/de-de/officeonlineserver/deploy-office-online-server
:office365-url: https://products.office.com/en-us/business/office
:download-gh-directory-url: https://download-directory.github.io
:wopi-wiki-url: https://en.wikipedia.org/wiki/Web_Application_Open_Platform_Interface
:wopi-ms-url: https://learn.microsoft.com/en-us/openspecs/office_protocols/ms-wopi/6a8bb410-68ad-47e4-9dc3-6cf29c6b046b

// since ocis 4.0 we can use teh second tab
:use_tab_2: true

== Introduction

{description} For more details on possible configuration values see the xref:conf-examples/office/office-integration.adoc[Office Integration] document at the configuration examples. More information about the WOPI protocol can be found on {wopi-wiki-url}[Wikipedia,window=_blank] or {wopi-ms-url}[Microsoft,window=_blank].

For the time being, the supported office applications are:

* Collabora
* OnlyOffice
* Microsoft Office

== General Information

Infinite Scale can be configured to use office applications as web applications via a browser in an iframe using the WOPI protocol. Among other things and depending on the use case, administrators can:

* provide multiple applications from different vendors in parallel,
* define which icons are used for which applications,
* define which app is preferred to open a file.

Configured applications can be selected by users when opening a document via the web UI. The list of available applications to open a file shows an icon and the app name for each entry.

Office applications are:

* provided via the xref:{s-path}/app-provider.adoc[App-Provider Service] because they are not able to register themself, see the xref:#wopi-configuration-examples[docker-compose.yml] file. 

* configured for use with the web UI via the xref:{s-path}/app-registry.adoc[App-Registry Service]. Here, default office apps and their appearance in the list of available apps in the web UI are defined. For more information see the xref:#wopi-configuration-examples[app-registry.yaml] file.

{empty}
[[special-ms-note]]
Special note on Microsoft Office::
--
Microsoft distinguishes between two approaches running an office web application farm where you either need:

- an {office-online-server-url}[Office Online Server] locally installed, or 
- an active {office365-url}[Microsoft 365] subscription including the data provided by ownCloud, see xref:procedure-using-microsoft-365[Procedure using Microsoft 365].
--

== Procedure using Microsoft 365

Apart from licensing, when using Microsoft 365, the following procedure applies, contact {oc-support-url}[ownCloud Support] for more details:

* Customers provide ownCloud with:
** a written statement about their Microsoft 365 entitlement.
** the URL of their ownCloud instance. Only users coming from this URL will be able to use Microsoft 365.
* ownCloud provides customers with a required proxy URL to be used in the settings, see below.
** Among other things, the proxy checks if users originate from the given ownCloud Instance URL.
* When users open an office document via the ownCloud instance and Office 365 for the web is loaded, Microsoft checks if these users are already signed in via a Microsoft 365 business account. If users are not yet signed in, they will be prompted to sign in.

== WOPI Overview

The image below shows the WOPI integration in an overview to get a better understanding of which general components are involved and which basic settings need to be set. It also shows where parts of an URL are defined, how an URL is assembled, and which component is using which part of the URL. Note that only a few configuration options are shown in the image to get the relationships right.

image::deployment/wopi/wopi-overview.svg[WOPI Overview Diagram]

== WOPI Configuration Examples

* See below for an example WOPI configuration using Docker Compose, to get a first impression of how a WOPI configuration can be achieved. Both, _ocis environment variables_ and _ocis service configuration_ yaml files are used. See the xref:conf-examples/office/office-integration.adoc[Office Integration] document for an in depth explanation.
+
[tabs]
====
{compose_tab_1_tab_text}::
+
--
{composer-url}{compose_tab_1}{composer-final-path}{wopi_subdir}[Docker Compose WOPI deployment examples directory,window=_blank]

Using git version name: `{compose_tab_1}`
--
{compose_tab_2_tab_text}::
+
--
{composer-url}{compose_tab_2}{composer-final-path}{wopi_subdir}[Docker Compose WOPI deployment examples directory,window=_blank]

Using git version name: `{compose_tab_2}`
--
{compose_tab_3_tab_text}::
+
--
{composer-url}{compose_tab_3}{composer-final-path}{wopi_subdir}[Docker Compose WOPI deployment examples directory,window=_blank]

Using git version name: `{compose_tab_3}`
--
====
+
--
Note that github will not let you download a single directory easily. You can get the examples using the following methods requiring minimum space. Replace the version accordingly:

* Using a shallow git clone which minimizes the required clone space like:
+
[source,bash,subs="attributes+"]
----
git clone --depth 1 https://github.com/owncloud/ocis.git -b {compose_tab_2}
----

// https://stackoverflow.com/questions/7106012/download-a-single-folder-or-directory-from-a-github-repo

* Using an external page providing you the folder to download as zip file like:
+
[source,plaintext,subs="attributes+"]
----
{download-gh-directory-url}?url={composer-url}{compose_tab_2}{composer-final-path}{wopi_subdir}
----
--
