= Infinite Scale Developer Documentation
:toc: right
:toclevels: 2
:description: Welcome to the Infinite Scale developer documentation. Infinite Scale is a data platform providing tools to integrate, organize, share and govern data and metadata.

## Admin Documentation

Before you start reading, if you are interested in:

- learning ocis from an admin perspective,
- different deployment scenarios,
- deployment examples,
- detailed settings and more

we would recommend to continue with the [ownCloud Admin Documentation for Infinite Scale](https://doc.owncloud.com/ocis/latest/).

## Developer Documentation

Welcome to our developer documentation. Here you find documentation with focus for *developers*:

- [oCIS]({{< ref "./ocis" >}}) server
- oCIS Services
- Clients like:
    - [ownCloud Web](https://github.com/owncloud/web) - the new web frontend for oCIS and ownCloud
    - [ownCloud Android app](https://github.com/owncloud/android)
    - [ownCloud iOS app](https://github.com/owncloud/ios-app)
    - [ownCloud Desktop Syncing Client](https://github.com/owncloud/client)
- Integrations

## We Love Open Source

The oCIS server is Apache v2 licensed.
The lower storage layer of oCIS is defined by the CS3 APIs and implemented in the REVA project. Our goal is to develop the CS3 APIs to an open standard and collaborate on the open source REVA reference implementation for CS3 APIs.

You can also find all client sources on https://github.com/owncloud/[GitHub].

## Join the oCIS Community

The https://github.com/owncloud/ocis[ocis repository] is a good entry point to the oCIS project. In addition to that, there are also ownCloud projects for apps such as https://github.com/owncloud/ios-app[iOS], https://github.com/owncloud/android[Android], the  https://github.com/owncloud/desktop[Desktop] platforms and https://github.com/owncloud/web[ownCloud Web].

To chat about development, join our public chat on https://matrix.to/#/#ocis:matrix.org[matrix: ownCloud Infinite Scale].

If you want to help and improve ownCloud or oCIS, start coding or open issues on GitHub in the related repository.

We are very happy to hear your feedback and ideas!
