= Upgrading from 7.3.0 to 8.0.0
:toc: right
:description: This document describes the necessary steps when upgrading Infinite Scale from release 7.3.0 to 8.0.0.

:actual_seven_version: 8.0.0

include::partial$multi-location/compose-version.adoc[]

== Introduction

{description}

IMPORTANT: Read the important notes in the xref:migration/upgrading-ocis.adoc#introduction[Upgrading Infinite Scale] documentation before you start.

IMPORTANT: Check below, if you are affected by breaking changes and prepare all steps mentioned before you start the upgrade.

== Upgrade Steps

. Download and install Infinite Scale +
*Do not start it after downloading the image*!
. Shut down the Infinite Scale instance
. We strongly recommend doing a backup
. Reconfigure the deployment
. Manage Breaking Changes
. Notabale Changes
. Manage Added/Removed/Deprecated environment variables
. Start Infinite Scale

:sectnums:

== Download and Install Infinite Scale

Download and install Infinite Scale:

* Issue the following command to download the new image:
+
[source,bash,subs="attributes+"]
----
docker pull owncloud/ocis:{actual_seven_version}
----

== Shut Down the Infinite Scale Instance

Depending how you deployed Infinite Scale, you need to shut it down differently.

* *docker compose* +
For deployments using `docker compose` do a graceful shutdown as described in xref:depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc#stop-the-deployment[Stop the Deployment].

* *Any other image based deployment* +
For any other image based deployment, shut down Infinite Scale according the vendors deployment description.

== Backup of Infinite Scale

See the xref:maintenance/b-r/backup_considerations.adoc[Backup Considerations] and the xref:maintenance/b-r/backup.adoc[Backup] documentation for more details.

== Reconfigure the Deployment

Reconfigure the deployment to use the new image:

* For `docker compose`
** Update _every_ compose file where the `ocis image` is referenced accordingly.
** If you have used the deployment examples either for xref:depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc[Local Production Setup] or xref:depl-examples/ubuntu-compose/ubuntu-compose-hetzner.adoc[Deployment on Hetzner], read the *Updating and Upgrading* section of those pages carefully. 

== Manage Breaking Changes

Breaking changes only apply when using OCM. +
These changes mean, that OCM is now fully compatible with other Open Cloud Mesh services and can be federated with them. As drawback, all OCM invitations and shares no longer work and must be resetup.

== Notabale Changes

* A new feature has been implemented to protect against brute-force password attacks when using public links. This feature is enabled by default. See the xref:{s-path}/storage-publiclink.adoc#brute-force-protection[Storage-Publiclink] service for more details.

* Some deprecated environment variables have finally been removed. If you are using them, you can remove them from your config. For details see the xref:#changed-environment-variables[Changed Environment Variables] section below.

== Reconfigure Deployment Examples

The following steps are based on the xref:depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc[Local Production Setup] deployment example. The steps are identical for the xref:depl-examples/ubuntu-compose/ubuntu-compose-hetzner.adoc[Deployment on Hetzner].

* Stop the deployment example

* Backup the the base folder containing the existing deployment example by renaming it. +
You will need your configuration details with the new example.

* Follow the xref:depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc#download-and-transfer-the-example[Download and Transfer Example] link to get the new deployment and extract it as described in the following section of the guide.

* Reconfigure the new `.env` file based on settings made in the `.env` file of the backup.
** Note that defined image versions have changed for: +
`Traefik`, `Collabora` and `OnlyOffice`. +
The provided versions have been tested. Update at your own risk. Note that this applies in particular when using `latest`. The image versions are subject to change if a new deployment example is provided.

** The version of other images using the `latest` tag may also have changed.
** Pull the new image versions with `docker compose pull`.

* Start the deployment example.

== Start Infinite Scale

When you have finished upgrading, you now can start Infinite Scale as usual.

For any deployment used, you now can delete/remove old binaries or images/containers.

:sectnums!:

== Changed or Added CLI Commands

See the xref:maintenance/commands/changed-cli.adoc[Changed or Added CLI Commands] document for details.

== Changed Environment Variables

See the xref:deployment/services/env-var-changes.adoc[Changed Environment Variables in Versions] document for details.
