== Manual Setup
:toc: right
:toclevels: 2

:downloadpage_ocis_url: https://download.owncloud.com/ocis/ocis/
:systemd-url: https://systemd.io/
:traefik-url: https://doc.traefik.io/traefik/getting-started/install-traefik/

:description: oCIS can be downloaded from ownCloud or installed via the package manger of your Linux system. Select the way you prefer most. Note that the download version is more often updated than the package manager version.

== Introduction

{description}

Using the manual method to install oCIS is best when you want to quickly test oCIS without doing additional tasks like docker preperation or kubernetes. Of course you can use it for production in your environment too. See the xref:availability/index.adoc[Availability and Scalability] documentation for impacts. 

== Installation

* To get the binary from ownCloud, visit {downloadpage_ocis_url}[download.owncloud.com], select the version and the platform of choice and copy the link of the file. Depending on your system and preferences, you may want to save the binary in `/usr/bin/`.
+
To download use:
+
[source,bash]
----
sudo wget -O /usr/bin/ocis <link>
----
+
Make the binary executable with
+
[source,bash]
----
sudo chmod +x /usr/bin/ocis
----
+
Check the version installed
+
[source,bash]
----
ocis --version
----
+
Which prints an output like
+
[source,plaintext,subs="attributes+"]
----
ocis version {actual-ocis-version}
----

// fixme: recommended directory possibly to be adjusted when we actually have a recommended or standard location.

* To install oCIS via the package manager of your Linux system, use the package manager commands to search for ocis and install it accordingly.
+
[NOTE]
====
Package manager installation is in preperation and will be available soon.
====

== Getting Command Line Help

To get a list of available options and commands type:

[source,bash]
----
ocis
----

or

[source,bash]
----
ocis --help
----

== Start and Stop oCIS

=== Starting oCIS

When oCIS has been installed, you can start oCIS as follows:

[source,bash]
----
ocis server
----

Note that this will bind `ocis` to the shell you are running. If you want to decouple it from the shell, use the following command:

[source,bash]
----
ocis server &
----

If you want to _add_ instances of an extension like `proxy`, run:

[source,bash]
----
ocis run proxy
----

=== List Running oCIS Processes

To list all running processes type

[source,bash]
----
ps ax | grep ocis | grep -v grep
----

ps -ax | grep ocis | grep -v grep | awk '{ print $1 }'

=== Stopping oCIS


== Basic Setup

You can now start the fullstack oCIS server with the command: `ocis server`. However, if you're using oCIS with self-signed certificates, you need to set the environment variable `OCIS_INSECURE=true`:

[source,console]
----
`OCIS_INSECURE=true ocis server`
----

If you have your own certificates already in place, you may want to make oCIS use them by adding the following environment variables to the command:

[source,console]
----
OCIS_INSECURE=false \
PROXY_HTTP_ADDR=0.0.0.0:9200 \
OCIS_URL=https://your-host:9200 \
PROXY_TRANSPORT_TLS_KEY=./certs/your-host.key \
PROXY_TRANSPORT_TLS_CERT=./certs/your-host.crt \
ocis server
----

In case your certificates are self-signed, better set `OCIS_INSECURE=true` in the above example.

Log in via the web interface at https://localhost:9200 using one of the demo users provided for testing purposes:

[source,console]
----
+----------+---------------+----------------------+-------+
| username | password      | email                | role  |
+----------+---------------+----------------------+------ +
| admin    | admin         | admin@example.org    | admin |
| einstein | relativity    | einstein@example.org | user  |
| marie    | radioactivity | marie@example.org    | user  |
| moss     | vista         | moss@example.org     | admin |
| richard  | superfluidity | richard@example.org  | user  |
+----------+---------------+----------------------+-------+
----


// https://owncloud.dev/ocis/deployment/basic-remote-setup/
// Does not really match my test setup.

=== Setting up the systemd Service

To run oCIS as a {systemd-url}[systemd] service, create the file `/etc/systemd/system/ocis.service` with the following content:

[source,console]
----
[Unit]
Description=OCIS server

[Service]
Type=simple
User=ocisadmin
Group=ocisadmin
EnvironmentFile=/etc/ocis/ocis.env
ExecStart=ocis server
Restart=always

[Install]
WantedBy=multi-user.target
----

The user `ocisadmin` is just a placeholder for any user to run oCIS. We strongly advise against using the user `root` for this purpose. Placing the environment file in `/etc/ocis/` is only a suggestion, but a good one. The directory `/etc/ocis/` needs to be created first with `sudo mkdir /etc/ocis`.

Now create the file `/etc/ocis/ocis.env` with the definitions of environment variables:

[source,console]
----
OCIS_URL=https://some-hostname-or-ip:9200
PROXY_HTTP_ADDR=0.0.0.0:9200
OCIS_INSECURE=false

OCIS_LOG_LEVEL=error

GLAUTH_LDAPS_CERT=/etc/ocis/ldap/ldaps.crt
GLAUTH_LDAPS_KEY=/etc/ocis/ldap/ldaps.key
IDP_TRANSPORT_TLS_CERT=/etc/ocis/idp/server.crt
IDP_TRANSPORT_TLS_KEY=/etc/ocis/idp/server.key
PROXY_TRANSPORT_TLS_CERT=/etc/ocis/proxy/server.crt
PROXY_TRANSPORT_TLS_KEY=/etc/ocis/proxy/server.key
----

Exchange the placeholder `some-hostname-or-ip` with the actual hostname or IP address of your oCIS instance.

If you are using self-signed certificates, you need to set OCIS_INSECURE=true instead of using false like in the above example.

Now you can run oCIS as a systemd service. Start it with `systemctl enable --now ocis`. With this setup, oCIS is restarted automatically if the host got rebooted.

If you need to restart oCIS because of configuration changes in `/etc/ocis/ocis.env`, run `systemctl restart ocis`.

The logs of oCIS can be displayed by issuing `journalctl -f -u ocis`.

// include::{latest-server-version}@server:admin_manual:page$installation/deployment_recommendations/nfs.adoc[leveloffset=+2]



=== Traefik

A reverse proxy is highly recommended for load balancing and security reasons. You'll also need it if you intend to run oCIS and an ownCloud 10 server in parallel before migrating. If you choose Traefik for your deployment, check out the {traefik-url}[documentation]. You'll see several options. In case you want to run it in a Docker container, consider using the version from the oCIS Docker stack.


=== WOPI Server

The Web Application Open Platform Interface (WOPI) protocol allows you to integrate online office software in oCIS, including Microsoft Office Online and Collabora Online. It can be installed with the package manager of your operating system and is also provided as a docker container.
