== Manual Setup
:toc: right
:toclevels: 2

:systemd-url: https://systemd.io/
:traefik-url: https://doc.traefik.io/traefik/getting-started/install-traefik/

=== Basic Setup

Install oCIS via the package manager of your Linux system or download the binary from
`https://download.owncloud.com/ocis/ocis/` and make it executable with `chmod +x ocis`. Depending on your system and preferences, you may want to save the binary as `/usr/bin/ocis`.

// URL with curl/wget command, once we know it. Recommended directory possibly to be adjusted when we actually have a recommended or standard location.

You can now start the fullstack oCIS server with the command: `ocis server`. However, if you're using oCIS with self-signed certificates, you need to set the environment variable `OCIS_INSECURE=true`:

[source,console]
----
`OCIS_INSECURE=true ocis server`
----

If you have your own certificates already in place, you may want to make oCIS use them by adding the following environment variables to the command:

[source,console]
----
OCIS_INSECURE=false \
PROXY_HTTP_ADDR=0.0.0.0:9200 \
OCIS_URL=https://your-host:9200 \
PROXY_TRANSPORT_TLS_KEY=./certs/your-host.key \
PROXY_TRANSPORT_TLS_CERT=./certs/your-host.crt \
ocis server
----

In case your certificates are self-signed, better set `OCIS_INSECURE=true` in the above example.

Log in via the web interface at https://localhost:9200 using one of the demo users provided for testing purposes:

[source,console]
----
+----------+---------------+----------------------+-------+
| username | password      | email                | role  |
+----------+---------------+----------------------+------ +
| admin    | admin         | admin@example.org    | admin |
| einstein | relativity    | einstein@example.org | user  |
| marie    | radioactivity | marie@example.org    | user  |
| moss     | vista         | moss@example.org     | admin |
| richard  | superfluidity | richard@example.org  | user  |
+----------+---------------+----------------------+-------+
----


// https://owncloud.dev/ocis/deployment/basic-remote-setup/
// Does not really match my test setup.

=== Setting up the systemd Service

To run oCIS as a {systemd-url}[systemd] service, create the file `/etc/systemd/system/ocis.service` with the following content:

[source,console]
----
[Unit]
Description=OCIS server

[Service]
Type=simple
User=ocisadmin
Group=ocisadmin
EnvironmentFile=/etc/ocis/ocis.env
ExecStart=ocis server
Restart=always

[Install]
WantedBy=multi-user.target
----

The user `ocisadmin` is just a placeholder for any user to run oCIS. We strongly advise against using the user `root` for this purpose. Placing the environment file in `/etc/ocis/` is only a suggestion, but a good one. The directory `/etc/ocis/` needs to be created first with `sudo mkdir /etc/ocis`.

Now create the file `/etc/ocis/ocis.env` with the definitions of environment variables:

[source,console]
----
OCIS_URL=https://some-hostname-or-ip:9200
PROXY_HTTP_ADDR=0.0.0.0:9200
OCIS_INSECURE=false

OCIS_LOG_LEVEL=error

GLAUTH_LDAPS_CERT=/etc/ocis/ldap/ldaps.crt
GLAUTH_LDAPS_KEY=/etc/ocis/ldap/ldaps.key
IDP_TRANSPORT_TLS_CERT=/etc/ocis/idp/server.crt
IDP_TRANSPORT_TLS_KEY=/etc/ocis/idp/server.key
PROXY_TRANSPORT_TLS_CERT=/etc/ocis/proxy/server.crt
PROXY_TRANSPORT_TLS_KEY=/etc/ocis/proxy/server.key
----

Exchange the placeholder `some-hostname-or-ip` with the actual hostname or IP address of your oCIS instance.

If you are using self-signed certificates, you need to set OCIS_INSECURE=true instead of using false like in the above example.

Now you can run oCIS as a systemd service. Start it with `systemctl enable --now ocis`. With this setup, oCIS is restarted automatically if the host got rebooted.

If you need to restart oCIS because of configuration changes in `/etc/ocis/ocis.env`, run `systemctl restart ocis`.

The logs of oCIS can be displayed by issuing `journalctl -f -u ocis`.

// include::{latest-server-version}@server:admin_manual:page$installation/deployment_recommendations/nfs.adoc[leveloffset=+2]



=== Traefik

A reverse proxy is highly recommended for load balancing and security reasons. You'll also need it if you intend to run oCIS and an ownCloud 10 server in parallel before migrating. If you choose Traefik for your deployment, check out the {traefik-url}[documentation]. You'll see several options. In case you want to run it in a Docker container, consider using the version from the oCIS Docker stack.


=== WOPI Server

The Web Application Open Platform Interface (WOPI) protocol allows you to integrate online office software in oCIS, including Microsoft Office Online and Collabora Online. It can be installed with the package manager of your operating system and is also provided as a docker container.
