== Manual Setup
:toc: right
:toclevels: 2

:downloadpage_ocis_url: https://download.owncloud.com/ocis/ocis/
:systemd-url: https://systemd.io/
:traefik-url: https://doc.traefik.io/traefik/getting-started/install-traefik/

:description: oCIS can either be downloaded from ownCloud or installed via the package manger of your Linux system. Use the way you prefer, but keep in mind that the download version is updated more frequently than the package manager version.

== Introduction

{description}

Installing oCIS manually works well if you want to quickly test oCIS without performing additional tasks like Docker preparation or Kubernetes deployment. Of course you can use it for production in your environment, too. See the xref:availability/index.adoc[Availability and Scalability] documentation for impacts. 

== Installation

* To get the binary from ownCloud, visit {downloadpage_ocis_url}[download.owncloud.com], select the version and the platform of choice and copy the link of the file. Depending on your system and preferences, you may want to save the binary in `/usr/bin/`
+
To download use:
+
[source,bash]
----
sudo wget -O /usr/bin/ocis <link>
----
+
Make the binary executable with:
+
[source,bash]
----
sudo chmod +x /usr/bin/ocis
----
+
Check the version installed:
+
[source,bash]
----
ocis --version
----
+
The output looks like this:
+
[source,plaintext,subs="attributes+"]
----
ocis version {actual-ocis-version}
----

// fixme: recommended directory possibly to be adjusted when we actually have a recommended or standard location.

* To install oCIS via the package manager of your Linux system, use the package manager commands to search for ocis and install it accordingly.
+
[NOTE]
====
Package manager installation is in preperation and will be available soon.
====

== Getting Command Line Help

To get a list of available options and commands type:

[source,bash]
----
ocis
----

or

[source,bash]
----
ocis --help
----

== Start and Stop oCIS

=== Starting oCIS

When oCIS has been installed, you can start the oCIS runtime which includes the available extension as follows:

[source,bash]
----
ocis server
----

Note that this will bind `ocis` to the shell you are running. If you want to detatch it and avoid it gets stopped when closing the shell or the shell gets disconnected (SIGHUP), use the following command:

[source,bash]
----
ocis server & disown -h
----

The same mechanism is true to start or instantinate extensions like:

[source,bash]
----
ocis web & disown -h
----

Note that instantination of runtime extensions is not possible, for more details see: xref:general/general-info.adoc#manage-instances-of-extensions[Manage Instances of Extensions]

=== List Running oCIS Processes

To list all running ocis processes type:

[source,bash]
----
ps ax | grep ocis | grep -v grep
----

[source,plaintext]
----
 221297 pts/1    Sl     0:04 ocis server
 221706 pts/0    Sl     0:00 ocis proxy
----

=== Stopping oCIS

Depending what you want to stop, differnt commands need to be applied.

If a service is being terminated with its PID, the signal `SIGTERM` (-15) is used. Note that SIGTERM politely ask a process to terminate. It shall terminate gracefully, cleaning up all resources (files, sockets, child processes, etc.), deleting temporary files and so on.

Stopping an extension from the runtime::
Note that the ocis runtime (`ocis server`) needs to be active or a default error message will be returned, see xref:general/general-info.adoc#default-runtime-error-response[Default Runtime Error Response]
+
[source,bash]
----
ocis kill [extension name]
----

Stopping the complete runtime with all its running extensions::
Depending on the user you started `ocis` and with which user you are currently logged in, you may need to use `sudo` for proper permissions.
+ 
[source,bash]
----
ps ax | grep "ocis server" | grep -v grep | awk '{ print $1 }' | xargs kill -15
----

Stopping a particular ocis PID::
First identify which PID you want to terminate:
+
[source,bash]
----
ps ax | grep "ocis" | grep -v grep
----
+
This may give an output like the following:
+
[source,plaintext]
----
 221297 pts/1    Sl     0:04 ocis server
 221706 pts/0    Sl     0:00 ocis proxy
----
+
To terminate the `ocis proxy` service, type:
+
[source,bash]
----
kill -15 221706
----

=== Setting up systemd for oCIS

To run the oCIS runtime as a {systemd-url}[systemd] service, create the file `/etc/systemd/system/ocis.service` with the content provided below. The easiest way to do this is with the following command:

[source,bash]
----
sudo systemctl edit ocis.service
----

Then copy the content of the systemd file below into the editor and save it.

* The user `ocisadmin` is just a placeholder for any user to run oCIS, the user must exist or be created first.
+
NOTE: This user can be a system user without e.g. having a home directory.
* We strongly advise *against* using the user `root` for this purpose.
* Placing the environment file in `/etc/ocis/` is only a suggestion, but a good one.
** The directory `/etc/ocis/` must exist and the `ocisadmin` must be able to read it. For security reasons, this user should have restricted permissions. Create and set permissions, adjust the values to your needs:
+
[source,bash]
----
sudo mkdir -p /etc/ocis
sudo chown -R ocisadmin /etc/ocis
sudo chmod 0570 /etc/ocis
----

[caption=]
.systemd file
[source,plaintext]
----
[Unit]
Description=OCIS server

[Service]
Type=simple
User=ocisadmin
Group=ocisadmin
EnvironmentFile=/etc/ocis/ocis.env
ExecStart=ocis server
Restart=always

[Install]
WantedBy=multi-user.target
----

Now create the file `/etc/ocis/ocis.env` with the definitions of environment variables. See the following sections for additional environment variables like xref:deployment/general/general-info.adoc#accessing-ocis-via-the-webui[Accessing oCIS Via the WebUI] or xref:deployment/general/general-info.adoc#define-the-ocis-data-path[Define the oCIS Data Path].

NOTE: This is just an example with a minimal set of environment variables used.

[source,plaintext]
----
OCIS_INSECURE=true
OCIS_URL=https://localhost:9200
PROXY_HTTP_ADDR=0.0.0.0:9200

OCIS_LOG_LEVEL=error
----

Run the following command to apply your changes:

[source,bash]
----
sudo systemctl daemon-reload
----

Now you can run oCIS as a systemd service. Start it with:

[source,bash]
----
sudo systemctl enable --now ocis
----

With this setup, oCIS is restarted automatically after a reboot.

If you need to restart oCIS because of configuration changes in `/etc/ocis/ocis.env`, run:

[source,bash]
----
sudo systemctl restart ocis
----

The logs of oCIS can be displayed by issuing:

[source,bash]
----
sudo journalctl -f -u ocis
----

=== Traefik

A reverse proxy is highly recommended for load balancing and security reasons. You'll also need it if you intend to run oCIS and an ownCloud 10 server in parallel before migrating. If you choose Traefik for your deployment, check out the {traefik-url}[documentation]. You'll see several options. In case you want to run it in a Docker container, consider using the version from the oCIS Docker stack.


=== WOPI Server

The Web Application Open Platform Interface (WOPI) protocol allows you to integrate online office software in oCIS, including Microsoft Office Online and Collabora Online. It can be installed with the package manager of your operating system and is also provided as a docker container.
