name: CI

on:
  push:
    branches:
      - master
      - '8.0'
      - '7.3'
    tags:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  docs-build:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build documentation
        run: npm run antora

